### ISSUE TITLE
EnvironmentError 

### ISSUE THREAD

**Issue by attacker007** [encode/httpx#1007]
I've tried this command on mac OS Catalina:

```

 pip install httpx

```

And Got this Error:

```

ERROR: Could not install packages due to an EnvironmentError: Could not find a suitable TLS CA certificate bundle, invalid path: /usr/local/lib/python2.7/site-packages/pip/_vendor/certifi/cacert.pem

```

**Comment by florimondmanca** [comment]
Hey there,

This is odd, but for optimal usage of everyone’s time we’d need you to provide more information on your setup and environment to be able to help out with this.

You can do so by opening a “bug report” issue and filling in the issue template.

Closing this one for now for housekeeping, happy to discuss on the new issue afterwards.

Thanks!
