### ISSUE TITLE
httpx.URLLib3Transport does not support HTTP/2

### ISSUE THREAD

**Issue by paulchubatyy** [encode/httpx#1014]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

`httpx.URLLib3Transport`  does not support HTTP/2. Probably because of [this hardcoding](https://github.com/encode/httpx/blob/master/httpx/_transports/urllib3.py#L35).

### To reproduce

```
➜ python
Python 3.7.7 (default, Mar 10 2020, 16:11:21)
[Clang 11.0.0 (clang-1100.0.33.12)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import httpx
>>> httpx.__version__
'0.13.3'
>>> client = httpx.Client(http2=True, transport=httpx.URLLib3Transport())
>>> response = client.get("https://google.com")
>>> response.http_version
'HTTP/1.1'
>>> print("It should be:")
It should be:
>>> "HTTP/2"
'HTTP/2'
```

**Comment by florimondmanca** [comment]
Hi there,

This is not a bug, but a known limitation: the `URLLib3Transport` is a lightweight wrapper around `urllib3`, and `urllib3` does not support HTTP/2 (hence the explicit `http2=False`).

If you need HTTP/2 w/ sync, consider using the default transport.

Cheers!
