### ISSUE TITLE
Streaming Get and Post of a File

### ISSUE THREAD

**Issue by michaelschmit** [encode/httpx#1015]
### Checklist

- [x] I searched the [HTTPX documentation](https://www.python-httpx.org) but couldn't find what I'm looking for.
- [x] I looked through similar issues on GitHub, but didn't find anything.
- [x] I looked up "How to do ... in HTTPX" on a search engine and didn't find any information.
- [x] I asked the [community chat](https://gitter.im/encode/community) for help.

### Question

I would like to use httpx to perform a streaming get of a file and then stream that file to another service.  Is that possible with httpx?  Would it require receiving the entire file before making a streaming post to the other service?  It might be a useful example to have within the documentation. Thanks.

**Comment by florimondmanca** [comment]
Hey there!

Sure, sounds feasible to me. Probably a combination of [response streaming][0] with [multipart file upload][1] (which are streaming by default in HTTPX).

[0]: https://www.python-httpx.org/quickstart/#streaming-responses
[1]: https://www.python-httpx.org/advanced/#multipart-file-encoding

(My only doubt is that I’m not sure multipart uploads support async iterators as file inputs.)

Eg would this work?

```python
import httpx

async with httpx.AsyncClient() as client:
    async with client.stream(...) as r:
        files = {"some-field": (None, r.aiter_bytes())}
        resp = await client.post(..., files=files)
        print(resp)
```

**Comment by florimondmanca** [comment]
Also there’s an interesting bit in that multipart implementation currently does _synchronous_ I/O _always_ - so I _assume_ the above snippet won’t work because the response stream is an _async_ iterator.

I think this « always async » is a problem, though it’s possible to fix it to adding async without breaking backward compat, provided we still allow reading from sync files in the async case. (But IMO we should encourage users to defer the reading to the threadpool, or use anyio.)

**Comment by florimondmanca** [comment]
I actually managed to _make it work_ using some hacked async/sync IO wrapper with threading, but it's not pretty, probably of very poor performance, and involves some hacks based on details of the multipart implementation. (In particular the encoder does "if I can't determine the content length by inspecting the fileobj, I will try to read it in full in memory". Hence the seek/tell fake implementation to allow the mulipart encoder to determine the body length w/o consuming the whole thing).

```python
import asyncio
import io
import queue
import threading
from typing import AsyncIterator, BinaryIO, Iterator, cast

import httpx


class AsyncToSyncIO(io.RawIOBase):
    def __init__(self, aiterator: AsyncIterator[bytes], content_length: int) -> None:
        self._aiterator = aiterator
        self._content_length = content_length

    def __iter__(self) -> Iterator[bytes]:
        def worker(q: "queue.Queue[bytes]", done: threading.Event) -> None:
            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)
            while True:
                try:
                    chunk = asyncio.run(self._aiterator.__anext__())
                except StopAsyncIteration:
                    done.set()
                    break
                else:
                    q.put(chunk)

        q: queue.Queue[bytes] = queue.Queue()
        done = threading.Event()
        t = threading.Thread(target=worker, args=(q, done))
        t.start()

        while not done.is_set():
            try:
                chunk = q.get(timeout=0.1)
            except queue.Empty:
                continue
            else:
                q.task_done()
                yield chunk

        q.join()
        t.join()

    def seekable(self) -> bool:
        return False

    def tell(self) -> int:
        return 0

    def seek(self, offset: int, whence: int = 0) -> int:
        return self._content_length


async def main() -> None:
    async with httpx.AsyncClient() as client:
        async with client.stream("GET", "https://httpbin.org/get") as r:
            content_length = int(r.headers["content-length"])
            rfile = cast(BinaryIO, AsyncToSyncIO(r.aiter_bytes(), content_length))
            files = {"some-field": (None, rfile)}
            resp = await client.post("https://httpbin.org/post", files=files)
            print(resp.json())


if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by tomchristie** [comment]
It depends on *exactly* what you want to do. The simplest thing is to use the raw body of the downloaded response in the uploaded request.

For instance either this...

```python
import httpx

client = httpx.Client()

with client.stream("GET", "https://httpbin.org/get") as get_response:
    post_response = client.post("https://httpbin.org/post", data=get_response.iter_bytes())
    print(post_response.text)
```

Or this...

```python
import httpx

async def main():
    client = httpx.Client()

    async with client.stream("GET", "https://httpbin.org/get") as get_response:
        post_response = await client.post("https://httpbin.org/post", data=get_response.aiter_bytes())
        print(post_response.text)
```

As @florimondmanca notes, you *might* alternately be wanting to stream the upload as a multipart file, which is supported for the sync case, but isn't really supported for the async case because there's no equivalent of an async file interface.

**Comment by tomchristie** [comment]
There's potentially a conversation to be had about "should we support an async file interface" wrt. multipart uploads, but I think we should treat that separately. Probably something I'd expect us to want to push back on, since it's *very much* not obvious exactly what we would or wouldn't want to do there.

**Comment by michaelschmit** [comment]
I appreciate the quick responses.  I am trying to perform a multipart file upload.  I first tried using async and then switched to sync using the client context manager.  I wasn't successful trying to essentially use `files = {"some-field": (None, r.iter_bytes())}` because it doesn't represent itself exactly as a file would.  I believe that is partially what you are fixing in the second example.

**Comment by tomchristie** [comment]
@michaelschmit Please don't assume an entitlement onto other peoples time and attention like that. It's not appropriate.

**Comment by michaelschmit** [comment]
That wasn't my intention.  Please don't assume the worst.

The two of you had a good back and forth about possible issues at hand, and it was my fault I didn't provide the information about whether or not I was doing multipart file upload.  However, before I could comment the "question" was closed.  I still had the question of whether using the sync client context manager changed the dynamic at all and wanted to make sure my question was noticed.

It would be nice if the person asking the question is the one who closes it.  However, I understand that people likely don't do that on a regular basis.

Like I said, I do appreciate your time.

**Comment by florimondmanca** [comment]
Hey,

Not sure I understand your question from last time to be honest. I _think_ you’re asking if it’s possible to do what is done in Tom’s sync snippet, but as a multipart file upload.

But answer would mostly be the sale as in the async case, ie « not built in » because files=... expects file-like objects, an interface that responses don’t implement.

You could provably make it work with a custom subclass of io.BytesIO() though, overriding `__iter`__ so that it yields the next chunk in the response bytes iterator. My async workaround example should be helpful there I hope.

**Comment by michaelschmit** [comment]
Yes, that is the confirmation I was looking for.  I just wanted to verify that I can't just do:

`
import httpx

client = httpx.Client()

with client.stream("GET", "https://httpbin.org/get") as get_response:
    files = {"some-field": (None, get_response.iter_bytes())}
    post_response = client.post("https://httpbin.org/post", files=files)
    print(post_response.text)
`

Going to a synchronous call alone doesn't solve the problem of how the stream interface is represented (not as a file).

Essentially I could take your wrapper and swap out the __iter__ section since that is trying to solve the async issue side of the problem and it *should* work.  

I wanted that confirmation because there were two "issues" being discussed as I understood it, one being the response stream interface and the other being representing an async stream in a way that that looks like synchronous IO.

**Comment by samuelcolvin** [comment]
Any chance this could be reopened?

Currently as I understand it there's no solution to uploading multipart forms without blocking IO. Support for `aiofiles` file objects would be great. I know aiofiles isn't official but it's fairly widely used.

I'm using httpx for [aioaws](https://github.com/samuelcolvin/aioaws) and I'd love there to be a way to support uploading large files without either reading them into memory or blocking the event loop.

I guess my alternatives are either use the somewhat hacky queue based solution above, or implement multipart form building myself which seems quite ugly.

**Comment by odie5533** [comment]
Did not figure out how to get this working with httpx. I did find it quite easy to do in aiohttp. https://docs.aiohttp.org/en/stable/client_quickstart.html#streaming-uploads

The interface is exactly as I'd expect and like: you supply an async generator or file-like object to data and it handles the rest.
