### ISSUE TITLE
Recursive fetching with HTTP/2 gets stuck

### ISSUE THREAD

**Issue by rgov** [encode/httpx#1017]
### Checklist

- [x] I searched the [HTTPX documentation](https://www.python-httpx.org) but couldn't find what I'm looking for.
- [x] I looked through similar issues on GitHub, but didn't find anything.
- [x] I looked up "How to do ... in HTTPX" on a search engine and didn't find any information.
- [ ] I asked the [community chat](https://gitter.im/encode/community) for help.

### Question

I admit I'm new to both this library and Python coroutines, so I'm not sure that this isn't just my problem. I'm running 0.13.3.

This issue *only* reproduces with HTTP/2.

Suppose I want to write a web-scraper that extracts links from a page and then recursively fetches and processes those pages:

```python
# client is a shared httpx.AsyncClient(http2=True) instance
async def process(client, url):
    response = await client.get(url)
    new_urls = extract_links(response.text)
    await asyncio.gather(*[process(client, u) for u in new_urls])
```

What I see happening is that the first URL gets fetched and processed. However, at the second level, `client.get(url)` hangs until the server hangs up or a timeout occurs. I confirm this by putting `print` statements before and after.

However when I run with `HTTPX_LOG_LEVEL=trace`, I can clearly see the server responding with headers and content. Is there a reason I am stuck `await`ing forever?

**Comment by rgov** [comment]
I realize recursion isn't the operative bit here.

After investigating more, I do see the `200 OK` responses come through in the debug log, but it does not immediately resume the awaiting coroutine that made the request. Instead it seems to wait until all requests have been completed.

So my theory is that the server is only responding to the first *n* requests I make (*n* = 101 it seems), and then after that it refuses to serve more, and `httpx` is just stalling. Or my failed attempt at asynchronous programming is just stalling.

**Comment by florimondmanca** [comment]
Hi! Not clear to me yet what could be causing the stalling behavior. What does a straight up « gather multiple HTTP/2 requests » look like (i.e. removing the recursive call)?

**Comment by florimondmanca** [comment]
Actually this might be the pool limits kicking in and preventing HTTPX from opening too many connections (len(new_urls) > 100), meaning if the server takes more than 5s to respond the other requests will time out while trying to acquire a connection...

Il thinking you might want to try an alternative design, such as using a queue (with a reasonable max size) and producer/consumer tasks.

**Comment by rgov** [comment]
Thanks. I did try a producer/consumer design originally but thought this was simpler to read. But if I'm not mistaken, even if the pool limit is met, shouldn't the awaiting coroutine resume as soon as the server responds with `200 OK`? I find it weird that the server sends a response but it isn't handed off to my code immediately.

**Comment by yeraydiazdiaz** [comment]
Without code samples or logs is hard to say if HTTPX is doing anything wrong here, @rgov could you put together a very simple script that illustrates the problem?

Removing the bug label as it's not clear to me that HTTPX is misbehaving.

**Comment by tomchristie** [comment]
I think we need to close this off as obsolete, in the absence of a simple runnable example demonstrating an issue on our side.

I *expect* it's probably an issue with the flow of how you're issuing requests vs when you're expecting to get a response back, or something like that but it's a bit hard to say without a really clearly narrowed down example case.
