### ISSUE TITLE
ASGI Lifespan events are not sent when using `app` parameter to `AsyncClient`

### ISSUE THREAD

**Issue by retnikt** [encode/httpx#1024]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

When using the `app` parameter to an `AsyncClient`, 

### To reproduce

```python
# here shown using a Starlette server for simplicity

async def startup():
    print("Starting up!")

app = Starlette(on_startup=[startup])

async def main():
    async with AsyncClient(app=app) as c:
        pass

asyncio.run(main())
```

### Expected behavior

The AsyncClient issues ASGI lifespan events for startup and shutdown (in the example above, resulting in the `Starting Up!` message being printed) when entered and exited as a context manager. This might mean a mechanism for Transports to have startup and shutdown events is needed.

### Actual behavior

No ASGI lifespan events are sent.

### Environment

- OS:  Linux
- Python version:  3.8.3
- HTTPX version:  0.13.3
- Async environment: asyncio, with [pytest-asyncio](https://github.com/pytest-dev/pytest-asyncio)
- HTTP proxy: no
- Custom certificates: no

### Additional context

I am trying to replace `starlette.TestClient` with `httpx.AsyncClient` because it means my code is end-to-end asynchronous, including tests. See [encode/starlette#975](https://github.com/encode/starlette/issues/975#issuecomment-644647580). However, this means that databases etc. are not connected with the AsyncClient and I have to do it manually in my tests.

**Comment by JayH5** [comment]
@retnikt you can use the [asgi-lifespan](https://pypi.org/project/asgi-lifespan) library for this, e.g. with pytest like:
```python
@pytest.fixture
async def app():
    async def startup():
        print("Starting up!")

    app = Starlette(on_startup=[startup])

    async with LifespanManager(app):
        yield app

def test_thing(app):
    ...
```

**Comment by retnikt** [comment]
@JayH5 thanks for that! You've also helped me realise now why this probably shouldn't be a standard feature of HTTPX.
