### ISSUE TITLE
TimeoutException missing from package

### ISSUE THREAD

**Issue by HenrikOssipoff** [encode/httpx#1029]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

[According to the documentation](https://www.python-httpx.org/advanced/#timeout-configuration), there should be an `httpx.TimeoutException` class that you can catch if you want to catch any timeout related exception. However, such exception doesn't exist.

### To reproduce

```python
import httpx
httpx.TimeoutException
```

### Additional context

I'm assuming it's intended behaviour, and it's a case of the docs not being updated when introducing httpcore over urllib3. However, I'm unsure about what the correct approach now is; should one catch HTTPError instead, or are we forced to catch each individual timeout related exception?

**Comment by HenrikOssipoff** [comment]
I see now that the `TimeoutException` is living in `httpcore` since 0.13.
I feel like this should be documented (did I miss it?).

Would it maybe make more sense to wrap these exceptions in `httpx` instead, so that the user doesn't have to worry about the underlying library?

**Comment by johnanthonyowens** [comment]
This is covered in #949.

**Comment by florimondmanca** [comment]
Hey,

As mentioned above this is part of a known issue tracked via #949, going to close this as a duplicate.

Thanks
