### ISSUE TITLE
I want to initiate a request from a specific IP address, but I don't know how to do it using httpx.

### ISSUE THREAD

**Issue by seo666** [encode/httpx#1040]
python3 httpx and aiohttp

I want to initiate a request from a specific IP address, but I don't know how to do it using httpx.

aiohttp like this.

conn = aiohttp.TCPConnector(local_addr=("127.0.0.1", 0))
async with aiohttp.ClientSession(connector=conn) as session:
async with session.get(url) as response:
r = await response.read()

Please tell me how to do using httpx.Thank you~!

**Comment by florimondmanca** [comment]
Heya,

Closing as this is tracked in HTTPCore, see https://github.com/encode/httpcore/issues/88.

Also, please don’t duplicate questions between Gitter and the issue tracker. (Gitter was the right channel to ask about this!) Thanks!
