### ISSUE TITLE
HTTP NTLM Authentication

### ISSUE THREAD

**Issue by mihaimyh** [encode/httpx#1041]
Hi,

Does httpx supports HTTP NTLM authentication? I didn't find anything on docs.
With requests this can be done like so:

```
from requests_ntlm import HttpNtlmAuth

session = requests.Session()
session.auth = HttpNtlmAuth('AD\\' + username, password)
```

**Comment by florimondmanca** [comment]
Don’t think so, no, and probably something that would be better served by a third party package like for Requests. It can be implemented as a custom Auth flow :) See https://www.python-httpx.org/advanced/#customizing-authentication
