### ISSUE TITLE
Considering non env-var 'no_proxy' support?

### ISSUE THREAD

**Issue by florimondmanca** [encode/httpx#1043]
### Checklist

- [x] There are no similar issues or pull requests for this yet.
- [ ] I discussed this idea on the [community chat](https://gitter.im/encode/community) and feedback is positive.

### Is your feature related to a problem? Please describe.

Hey all,

So while looking into an issues with `no_proxy` in Requests (https://github.com/psf/requests/issues/5000) I tried one of the failing cases with HTTPX, and ended up realizing that we don't take into account `no_proxy` in the `proxies={...}` usage. We only account for the `no_proxy`/`NO_PROXY` environment variable.

Eg this will fail as the request will be routed through the proxy:

```python
import httpx

proxies = {'https': 'http://no.where.com', 'no_proxy': 'google.com'}
client = httpx.Client(proxies=proxies)
client.get('https://google.com')  # ConnectError
```

However, this use case is covered by Requests (although with rough edges - see https://github.com/psf/requests/issues/5000).

```python
import os
import requests

os.environ['HTTPS_PROXY']='https://b.r.o.k.e.n.com'
proxies = {'no_proxy': 'google.com'}
r = requests.get('https://google.com', proxies=proxies)
```

## Describe the solution you would like.

The Requests way of passing a `no_proxy` key in the dict is somewhat clunky tbh, and also not compatible with us allowing users to pass an `httpx.Proxy` config object, or an URL, instead of a dict.

So I'd be thinking about a dedicated `no_proxy` option on clients, which accepts a list of domains or IPs (similar to how the env variable accepts a comma-separated string):

```python
httpx.Client(proxies=..., no_proxy=['<domain>', '<ip>', ...])
```

In terms of implementation, we could easily store this as an extra attribute, and then pass it when checking for "should we use proxies for this URL", without interfering with the proxy map building logic:

https://github.com/encode/httpx/blob/620b0670db07ae844aa6fae40d9209a856440c9d/httpx/_client.py#L555-L556

The priority order compared to env vars would be:

1. `no_proxy=[...]`
2. Environment variables (`no_proxy`/`NO_PROXY`)

Happy to discuss use cases and API details further!

**Comment by tomchristie** [comment]
So a consistent way to approach this would be to allow the values in the `proxies=...` dictionary to be `None`, so eg...

`proxies={'all': 'http://127.0.0.1:1234', 'all://google.com': None}`

**Comment by tomchristie** [comment]
Related to https://github.com/encode/httpx/pull/1059

**Comment by tomchristie** [comment]
Incidentally, I'm not super keen on `all://` since it *actually* means "http" or "https", but I think we need to treat any conversations around that separately.
