### ISSUE TITLE
Save cookies to a file

### ISSUE THREAD

**Issue by Mavic111** [encode/httpx#1056]
### Checklist

- [x] I searched the [HTTPX documentation](https://www.python-httpx.org) but couldn't find what I'm looking for.
- [x] I looked through similar issues on GitHub, but didn't find anything.
- [x] I looked up "How to do ... in HTTPX" on a search engine and didn't find any information.
- [x] I asked the [community chat](https://gitter.im/encode/community) for help.

### Question

I've been using this code in requests to save cookies to a file.
session = requests.Session()
json.dump(session.cookies.get_dict(), open(cookies.txt, 'w'))

and this code to open cookies file and set it to session cookies
cookies = requests.utils.cookiejar_from_dict(json.load(open('Cookies/cookies.txt', 'r')))
session.cookies.update(cookies)

How i do that in httpx? because httpx.Client.cookies doesn't have get_dict attribute. 

Thank you.

**Comment by florimondmanca** [comment]
Hi,

`Cookies` instances are mappings (the [docs](https://www.python-httpx.org/api/#cookies) say "a dict-like cookie store", and "standard mutable mapping interface"), so you can pass them to `dict()` to get a JSON-serializable dict object back. Similarly `Client(cookies=…)` accepts a `dict`, so you can pass the result of `json.load()` to it.

Example:

```python
import json
import httpx

client = httpx.Client()
r = client.get('https://www.google.com')

# Save cookies...

with open('cookies.json', 'w') as f:
    json.dump(dict(client.cookies), f)

# Load cookies...

with open('cookies.json') as f:
    cookies = json.load(f)

client = httpx.Client(cookies=cookies)
```

Hope this helps!

Note that there seems to be some caveats to this "dump-and-load cookies" approach with some websites, see #895.
