### ISSUE TITLE
AttributeError exception if header value is None

### ISSUE THREAD

**Issue by tector** [encode/httpx#1061]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

Header normalization fails if header value is None. 

### To reproduce

Send a request with a header key but give it no value:

```python
async with https.AsyncClient as client:
    r = client.get(URL, headers={'foo': None})
```

### Expected behavior

Ignore the header with None value (like 'requests' lib handle it)

### Actual behavior

Gives AttributeError: 'NoneType' object has no attribute 'encode'

### Debugging material

```bash
  File "/home/ubuntu/.pyenv/versions/<REDACTED>/lib/python3.8/site-packages/httpx/_client.py", line 1305, in get
    return await self.request(
  File "/home/ubuntu/.pyenv/versions/<REDACTED>/lib/python3.8/site-packages/httpx/_client.py", line 1137, in request
    request = self.build_request(
  File "/home/ubuntu/.pyenv/versions/<REDACTED>/lib/python3.8/site-packages/httpx/_client.py", line 195, in build_request
    headers = self.merge_headers(headers)
  File "/home/ubuntu/.pyenv/versions/<REDACTED>/lib/python3.8/site-packages/httpx/_client.py", line 242, in merge_headers
    merged_headers.update(headers)
  File "/home/ubuntu/.pyenv/versions/<REDACTED>/lib/python3.8/site-packages/httpx/_models.py", line 480, in update
    headers = Headers(headers)
  File "/home/ubuntu/.pyenv/versions/<REDACTED>/lib/python3.8/site-packages/httpx/_models.py", line 393, in __init__
    self._list = [
  File "/home/ubuntu/.pyenv/versions/<REDACTED>/lib/python3.8/site-packages/httpx/_models.py", line 394, in <listcomp>
    (normalize_header_key(k, encoding), normalize_header_value(v, encoding))
  File "/home/ubuntu/.pyenv/versions/<REDACTED>/lib/python3.8/site-packages/httpx/_utils.py", line 53, in normalize_header_value
    return value.encode(encoding or "ascii")
AttributeError: 'NoneType' object has no attribute 'encode'
```

### Environment

- OS: Ubuntu 18.04.4 LTS
- Python version: 3.8.2
- HTTPX version: 0.13.3
- Async environment: asyncio
- HTTP proxy: yes
- Custom certificates: no

### Additional context

I solved the problem when I deleted the Header key which had the None value. But for being compatible with the requests library I would expect to not do so.

**Comment by florimondmanca** [comment]
Thanks for submitting this, I think in the name of Requeqts compatibility this would be a sensible tweak.

Would you like to give it a shot with a PR? I think we'd need the following:

- Update the `HeaderTypes` type hint to allow `Optional` values.
- Update `Headers` to drop any `None` values.
- Add a test case.

**Comment by varunu28** [comment]
@florimondmanca I will like to take up this issue. Can you please assign it to me?

**Comment by florimondmanca** [comment]
For extra context, we actually already discussed this in the past via #152. At the time the "Requests compatibility" argument was not mentioned, and the issue was closed with a "filter headers out" workaround.

#1063 looks like a good one, I'm still on the fence about whether we should move forward with this change. Thinking…

**Comment by tomchristie** [comment]
Potential gotcha if we *do* start support `None` is that... 

This... `r = client.get(URL, headers={'foo': None})`
Has different behaviour to this... `r = client.get(URL, headers={'foo': ''})`

Initially I was leaning toward "okay, sure let's allow `None` value here". Having reviewed #152, and noticing the above, I'm not so sure that it doesn't just introduce a bunch of unnecessarily ambiguous behaviour.

**Comment by florimondmanca** [comment]
Yes, that's my feeling on this as well - could just result in ambiguous edge cases...

Is there anything we can do to clearly tell users "no, None headers are not supported, instead please do XYZ" (where X is probably "pop the header on the client, or on your headers dict, or use an omit_none helper, see <link>"). Dunno if this could be in code, or just a docs heads up...

**Comment by tomchristie** [comment]
> Is there anything we can do to clearly tell users [...]

We *could* raise explicit TypeErrors, such as "header values must be strings or bytes", but I don't think we *necessarily* need to.

**Comment by tector** [comment]
maybe also see how requests handle this issue:
https://github.com/psf/requests/blob/1b417634721ec377abb7f17bc1f215e07202c2f7/requests/utils.py#L932 
It seems to me that requests also doesn't allow None values in headers - in contrast to what i experienced, but maybe i use an older version of requests... i have to check...

**Comment by tomchristie** [comment]
I think it may be worth opening up an issue around header validity checking, but I'd treat that differently to this is.
Closing this one off now, since I think we're probably in the "let's not allow None values in headers" camp, right?
