### ISSUE TITLE
Don't call `should_not_be_proxied` on each request

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#1062]
Currently we're calling `should_not_be_proxied` on each request, which is problematic for two reasons...

* It's ignoring the `trust_env`, and relying on an environment variable unilaterally.
* It's preforming an extra chunk of work on each request that we'd rather not do.

**Comment by cdeler** [comment]
@tomchristie 

Do I understand correctly, that you told about working with requests on session level?

Something a-la:
1. introduce url->proxy transport cache on the Session level
1. disable the function call when trust_env is on

**Comment by cdeler** [comment]
@tomchristie , @florimondmanca ^ if so, I can try to work on it. Please just advise me if I was right.

**Comment by tomchristie** [comment]
Not sure if I'd recommend contributors jumping on this one, since it might be a bit fiddly.
