### ISSUE TITLE
Consider renaming `HTTPError` to `RequestError`

### ISSUE THREAD

**Issue by florimondmanca** [encode/httpx#1064]
Spun up from https://github.com/encode/httpx/issues/867

Currently `httpx.HTTPError` serves as a base exception class, no problem. (In 0.13.x it wasn't the case because HTTPCore could raise independant exception due to a lack of mapping, but this was fixed via #1044 and #1045.)

_However_ with #949 and 1.0 in mind, I think there's a case to be made for this exception to be renamed to something else, most likely `httpx.RequestError`.

The motivation discussed in #867 was to make `.raise_from_status()` raise a dedicated `HTTPStatusError` exception, _different from the base class_. (There's an implementation of this in in #869.) I _think_ it's a valid use case.

But either way another reason why I think `HTTPError` might not be ideal is that it's very close but different from `HTTPXError`, which feels a bit misleading (has an "isn't it a typo?" kind of vibe to it).

So, should we switch to `httpx.RequestError`?

**Comment by tomchristie** [comment]
Big plus one from me on `HTTPStatusError` - that makes a lot of sense.

I'm not 100% sure about the renaming.

**Comment by StephenBrown2** [comment]
Why not simply `httpx.Error` as the base exception? Too general?

**Comment by florimondmanca** [comment]
Yep, looking at it again the rename doesn't sound absolutely necessary or relevant - Stephen's note on the ambiguity of `RequestError` w/o `ResponseError` is a good point. :-)

Closing this, the `HTTPStatusError` idea is now tracked in #1067.
