### ISSUE TITLE
Raise dedicated exception in `.raise_from_status()`

### ISSUE THREAD

**Issue by florimondmanca** [encode/httpx#1067]
Refs #949, spun up from #1064.

Currently `Response.raise_from_status()` raises a generic `HTTPError` exception.

The problematic side is that it is not possible to catch it separately without also catching all exceptions originating from HTTPX (since `HTTPError` is the base exception class).

So we should probably introduce a dedicated exception class, namely something like `HTTPStatusError`.

_Note: there's an implementation of this in #869 but the PR also introduced some other changes (including renaming `HTTPError` to `RequestError` which is not really desirable as discussed in #1064)._

**Comment by frankie567** [comment]
Hello there! Sounds like a good issue for starting contributing to httpx, so I'll work on it if you don't mind @florimondmanca 🙂

**Comment by florimondmanca** [comment]
@frankie567 Please feel free to 🎉
