### ISSUE TITLE
SSL wrong version running with proxies

### ISSUE THREAD

**Issue by shineoos** [encode/httpx#1068]
System: Windows 10
Python Version: 3.8.3
Error: httpcore._exceptions.ConnectError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)

I get this error when I run with proxies, my proxies works with requests and aiohttp

**Comment by florimondmanca** [comment]
Hi, closing since we're discussions this on Gitter, and it's not obvious yet that there's something wrong with HTTPX given how generic this SSL error is... Thanks.

**Comment by tomchristie** [comment]
Referencing the resolution to this... https://gitter.im/encode/community?at=5f1559cc5ed1d537747014bc
