### ISSUE TITLE
HTTP/2 fails to negotiate SETTINGS with remote before initial HEADERS

### ISSUE THREAD

**Issue by valiant1x** [encode/httpx#1100]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

Some Akamai servers are rejecting connections made through sync httpx client with `http2=True`. It seems that the chunking of frames 0 and 1 together in the initial outbound TCP packet, and lack of httpx/h2 client to negotiate SETTINGS before sending the initial `HEADERS` in frame 1, is causing some rejection by Akamai anti-bot measures.

### To reproduce

```python
        import httpx
        #use custom ssl context - consider ssl_context.keylog_filename to decrypt HTTP/2 traffic
        ctx = HttpxSslContext.getContext()
        #WORKING with proper HTTP/2 SETTINGS sent and received (and ACK'd) before sending HEADERS: use mitmproxy
        proxies = { 'http': 'http://localhost:8080', 'https': 'http://localhost:8080' }
        client = httpx.Client(http2=True, verify=ctx, proxies=proxies, timeout=10)
        response = client.get('https://http2.pro/')

         #NOT working: do not use mitmproxy and instead rely upon httpx HTTP/2 handling
        client = httpx.Client(http2=True, verify=ctx, timeout=10)
        response = client.get('https://http2.pro/')
```

### Expected behavior

Our HTTP/2 client should initially only send Magic (PRI) and SETTINGS to the server, allow server to acknowledge the SETTINGS, perform negotiation, and a final ACK of server accepted settings before sending initial HEADERS. This is to follow the iPhone user-agent behavior. Example using mitmproxy:

![image](https://user-images.githubusercontent.com/29789261/88865220-ec869d00-d1cc-11ea-9f03-211dbb3aa4a2.png)

### Actual behavior

httpx combines the initial Magic (PRI), SETTINGS and WINDOW_UPDATE into the same initial outgoing packet as the HEADER.

![image](https://user-images.githubusercontent.com/29789261/88865646-0aa0cd00-d1ce-11ea-8b7e-b57d8694ccbf.png)
![image](https://user-images.githubusercontent.com/29789261/88865708-2b692280-d1ce-11ea-889d-00a2dd9ed903.png)

### Environment

- OS: Windows
- Python version: 3.8.2
- HTTPX version: 0.13.3
- Async environment: n/a, using sync
- HTTP proxy: Yes, issue occurs without proxy as well.
- Custom certificates: N/A

### Additional context

The goal is to follow an iOS user-agent correctly, otherwise, Akamai detects some abnormality and returns `400 Bad Request`

The sample site provided above (http2.pro) is not the actual Akamai site triggering the issue.

**Comment by florimondmanca** [comment]
Thanks for the detailed report!

A couple of follow up questions:

- Is this HTTP/2 sequencing behavior *actually* causing the problem you're seeing? You're talking about anti bot measures and the iPhone user agent. Be aware that HTTPX provides its own user-agent header by default. Could it be part of the problem? We had a case previously where CloudFlare would deny access because the user-agent was detected as a bot.
- Out of curiosity, does this reproduce when using async?

**Comment by florimondmanca** [comment]
I'm using this script to try and reproduce, and I'm not seeing the `400` error status code. I assume that's because I'm not hitting the Akamai network you're referring to. Do I need to provide the custom SSL context? What does it contain?

```python
import httpx

client = httpx.Client(http2=True)
r = client.get("https://http2.pro")
r  # <Response [200 OK]>
```

**Comment by valiant1x** [comment]
> 
> 
> Thanks for the detailed report!
> 
> A couple of follow up questions:
> 
>     * Is this HTTP/2 sequencing behavior _actually_ causing the problem you're seeing? You're talking about anti bot measures and the iPhone user agent. Be aware that HTTPX provides its own user-agent header by default. Could it be part of the problem? We had a case previously where CloudFlare would deny access because the user-agent was detected as a bot.
> 
>     * Out of curiosity, does this reproduce when using async?

I do specify custom headers and cookies, and TLS handshake, which match the iPhone according to pcap, but I was trying to provide the simplest example possible.

Async would require a large redesign of our codeflow so I have not tested it, my apologies.

There are a handful of other tweaks and customizations performed that would otherwise restrict your connection to Akamai/Cloudflare endpoints. I do believe the HTTP/2 fingerprint is the culprit here because everything works as expected when using mitmproxy. The only other parameters mitmproxy changes are TLS handshake and a couple header properties, but I can verify my headers/TLS to be correct according to a real iOS device capture. This only leaves the differing HTTP/2 behavior.



I believe the sole suspect is the HTTP/2 handling because everything else is exactly the same in the pcap. 

> 
> 
> I'm using this script to try and reproduce, and I'm not seeing the `400` error status code. I assume that's because I'm not hitting the Akamai network you're referring to. Do I need to provide the custom SSL context? What does it contain?
> 

For any considerable amount of testing you need a proper TLS handshake. Ciphers and other changes requiring openSSL modification are required.

> Edit:
> 
> > The sample site provided above (http2.pro) is not the actual Akamai site triggering the issue.
> 
> Ah, I see. Is such an Akamai site available online anywhere?

I am hesitant to post the actual site here. The remote site would not be so enthused to know we are automating against them. 😄 

Perhaps a simpler question is: how can the initial_connection to remote host be redesigned to allow for acknowledgement of SETTINGS first?

**Comment by florimondmanca** [comment]
The code for our HTTP/2 network implementation lives in the HTTPCore repo, namely here: https://github.com/encode/httpcore/blob/master/httpcore/_async/http2.py

From looking at it quickly, we do *intend* to send the connection init packets first, with request specific data being sent later. You can verify this by rubbing your program with `HTTPX_LOG_LEVEL=trace` and looking for connection_init followed by `send_headers`. I don't know why the actual network packets don't reflect this in your case.

One good first step might be to reproduce that the order is not as expected *in general* (eg including for a regular HTTP/2 request to example.org). Then maybe we'll need to take a closer look at what data the `h2` library returns after the connection init is done and before headers are sent to it.

**Comment by valiant1x** [comment]
I refactored `h2.H2Connection` to prepare separate chunks of data for the preamble and initial SETTINGS, which allowed negotiation to occur in the same manner mitmproxy or a native iOS device handles it. This alone was not enough and still caused chunking of the data into a single packet, but adding a simple `time.sleep(0.2)` between the segments was enough to allow proper sending/processing. It's a strange hack but it worked, and that's all I needed 😄 

Thanks for reviewing. It seems like a non-issue for general HTTP/2 processing, so I will close this.

**Comment by tomchristie** [comment]
File this one under "reasons why we prefer HTTP/1.1 by default, but include HTTP/2 as an optional extra". 😆
