### ISSUE TITLE
bash: /root/go/bin/httpx: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by hackerparakh** [encode/httpx#1131]
### Checklist

- [ ] I searched the [HTTPX documentation](https://www.python-httpx.org) but couldn't find what I'm looking for.
- [ ] I looked through similar issues on GitHub, but didn't find anything.
- [ ] I looked up "How to do ... in HTTPX" on a search engine and didn't find any information.
- [ ] I asked the [community chat](https://gitter.im/encode/community) for help.

**Comment by tomchristie** [comment]
We can't really help you out if you're not providing information about how you've installed httpx, or exactly what you've attempted to do.

**Comment by hackerparakh** [comment]
git clone https://github.com/projectdiscovery/httpx.git httpx-new; cd httpx-new/cmd/httpx; go build .; mv httpx /usr/local/bin/; httpx -h

This worked

**Comment by euri10** [comment]
This is just the wrong repo 😁
