### ISSUE TITLE
Document Base Url joining behavior

### ISSUE THREAD

**Issue by StephenBrown2** [encode/httpx#1139]
Just a tracking issue to add documentation for the Base URL improvements added in #1130 , potentially cribbing from that added in #1117 , and including the relative dot behavior.

**Comment by StephenBrown2** [comment]
Have the docs been added yet?

**Comment by tomchristie** [comment]
Our docs note that "For example, base_url allows you to prepend an URL to all outgoing requests".

https://www.python-httpx.org/advanced/#other-client-only-configuration-options

We've not had any complaints about this, so I'm going to close this issue off.
