### ISSUE TITLE
Move URLLib3Transport out of core and into a stand-alone package.

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#1143]
We should remove `URLLib3Transport` from `httpx`, and make it a stand-alone package, with a simple README documenting how to install and use it, with `transport=...`.

In fact, we *could* even just drop it from core, and *aim* at delivering a third party package but *not* treat having to do so as a 1.0 release blocker. (I mean, is anyone *actually* using it at the moment?)

**Comment by tomchristie** [comment]
I think we could pretty much get away with just a GitHub gist implementation, that we can then point to in the docs as an example of a custom transport, using URLLib3.

Things to do here would be to make sure everything in the implementation is using public API, so...

* Drop `verify`, `cert`, `trust_env`, and instead use `ssl_context: SSLContext`, and direct users towards eg `ssl_context=httpx.create_ssl_context()` when instantiating the transport.
* Import NetworkError from the top level of `httpcore`... `httpcore.NetworkError`, *not* the `httpx` import we're currently using.
* (Re)Implement the `map_exceptions` helper locally. (From https://github.com/encode/httpx/blob/master/httpx/_exceptions.py#L336-L359 but we *won't* need the `**kwargs` cleverness in this case.) *OR* just drop `map_exceptions` and instead explicitly handle the catch and re-raise cases. (Probably simpler here, actually)
* Use `httpcore.PlainByteStream` and `httpcore.IteratorByteStream` rather than the content streams.

And also, a nice to have...

* Ensure retries is configured off, and drop the `MaxRetryError` case, since we won't need it, and anyways we'd rather eventually push towards client-configured retries, rather than transport-configured retries.

**Comment by florimondmanca** [comment]
What do we think of this…? :-)

https://gist.github.com/florimondmanca/d56764d78d748eb9f73165da388e546e

**Comment by tomchristie** [comment]
Love it, yes! *Really* nice.

Couple of possible polishing touches...

* I don't think we need to import/catch MaxRetries, since we're using `retries=0`. In any case it's likely only ended up there as a remanent of having looked at how requests wraps up urllib3 exceptions.
* Perhaps returning a `SyncByteStream` subclass, `URLLib3ByteStream(conn=...)` would be more graceful than what we've been doing until now with the inner `response_bytes` function and the `close_func=conn.release_conn` callback?
* Maybe we should use `urllib3.exceptions.SSLError` rather than the extra import?

Anyways looks *ace* either with or without those. 👍

**Comment by florimondmanca** [comment]
Very nice suggestions — amended! :tada:
