### ISSUE TITLE
Headers order

### ISSUE THREAD

**Issue by qo4on** [encode/httpx#1147]
Is it possible to see/modify the raw headers order of the request?

**Comment by tomchristie** [comment]
I've not double checked the underlying `h11` library, but I'd except headers to be sent in the order you provide them.

We include some automatic headers on outgoing requests, which will always get sent first, but you can modify these either by using `client.build_request`/`client.send` or if you really need to by instating a Request directly.

More importantly- can you describe your use case, what you were expecting, and what actually happened?

**Comment by yifeikong** [comment]
This is really important for crawlers. AFAIK, browsers send headers in a consistent way, so some CDN or firewalls block requests that use a header order different from popular browsers.

See: https://stackoverflow.com/questions/17828740/which-request-headers-can-be-used-for-a-browser-client-fingerprint
