### ISSUE TITLE
Add API docs for streaming

### ISSUE THREAD

**Issue by felix-hilden** [encode/httpx#1154]
- [x] There are no similar issues or pull requests for this yet.
- [x] I discussed this idea in #1152 and feedback is positive.

There is no documentation in either the top level `stream` or `Client.stream`, and they are not mentioned in generated documentation. At least a short description of functionality and parameters (pointing to `httpx.request` if applicable) should be added.

**Comment by tomchristie** [comment]
So the streaming docs are here... https://www.python-httpx.org/quickstart/#streaming-responses

But yes, they're missing from the API documentation at the moment.

**Comment by felix-hilden** [comment]
Yes, that's what I meant by generated documentation! And thanks for the reference link 👍
