### ISSUE TITLE
CONNECT request didn't include a port

### ISSUE THREAD

**Issue by charkal233** [encode/httpx#1169]
CONNECT request didn't include a port

proxies = {'all://': httpx.Proxy('http://127.0.0.1:24000', mode='TUNNEL_ONLY')}
client = httpx.Client(proxies=proxies, http2=True)
r = client.get("https://www.google.com") #this will cause an error
r = client.get("https://www.google.com:443") # this one work

- OS: Windows
- Python version: Python 3.7.6
- HTTPX version: 0.14.1
- HTTP proxy: yes
- Custom certificates: no

**Comment by tomchristie** [comment]
I'm not able to replicate this (tested using `proxy.py`)...

```python
>>> proxies = {'all://': httpx.Proxy('http://localhost:8899', mode='TUNNEL_ONLY')}
>>> client = httpx.Client(proxies=proxies, http2=True)
>>> client.get("https://www.google.com")
<Response [200 OK]>
>>> client.get("https://www.google.com:443")
<Response [200 OK]>
>>> client.get("https://www.google.com").http_version
'HTTP/2'
```

Or, slightly more simply...

```python
>>> proxies = httpx.Proxy('http://localhost:8899', mode='TUNNEL_ONLY')
>>> client = httpx.Client(proxies=proxies, http2=True)
>>> client.get("https://www.google.com")
<Response [200 OK]>
>>> client.get("https://www.google.com:443")
<Response [200 OK]>
>>> client.get("https://www.google.com").http_version
'HTTP/2'
```

* What proxy are you using?
* Could you try the same, using `proxy.py` and see what results you get?
* What about if you don't use `http2=True`?
* When you say "will cause an error" what do you mean exactly? A traceback? Could we see it?
* When you say "didn't include a port" what do you mean exactly?

**Comment by charkal233** [comment]
I saw the this failure"CONNECT request didn't include a port: www.google.com" in charles.
It cause different error while I using different, but with proxy.py it did work.
Could you please try this proxy http://lum-customer-youwenhao-zone-testz-country-us-dns-remote-session-c88db5123e:hjedtwb3kf55@servercountry-US.zproxy.lum-superproxy.io:22225
I set an limit on it, so don't warry about it.

**Comment by charkal233** [comment]
I check my log in my proxy debugger. Normally in the CONNECT request, there will be ":443" in the host header like "Host: www.google.com:443", but when i use httpx, the host header only contain the hostname but no port like "Host: www.google.com"

**Comment by tomchristie** [comment]
Okay, so based on these docs https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/CONNECT which *always* include the port component, I guess we need to be doing so, too.

Can anyone confirm where that might be ref'ed in the HTTP specs?

Looks like we want to tweak this block in `httpcore`... https://github.com/encode/httpcore/blob/d82896bf09db516b1daa27f525c1c9690e9fc961/httpcore/_async/http_proxy.py#L197-L200

From this:

```python
if port is None:
    target = host
else:
    target = b"%b:%d" % (host, port)
```

To this:

```python
if port is None:
    default_port = {b'http': 80, b'https': 443}[scheme]
    target = b"%b:%d" % (host, default_port)
else:
    target = b"%b:%d" % (host, port)
```

**Comment by tomchristie** [comment]
Okay, I've confirmed this using Charles proxy too.

Looks like it *ought* to be a good first issue for contributors to `httpcore`, although I'd *really* like to see any fixes confirmed before and after.

**Comment by tomchristie** [comment]
https://tools.ietf.org/html/rfc7231#section-4.3.6

> The request-target consists of only the host name and port number of the tunnel destination, separated by a colon.  For example:
>
> ```
> CONNECT server.example.com:80 HTTP/1.1
> Host: server.example.com:80
> ```

So, yup. Needs a tweak in httpcore.
Thanks so much for the report!

**Comment by charkal233** [comment]
And thank you for coding httpx!!

**Comment by florimondmanca** [comment]
@charkal233 https://github.com/encode/httpcore/pull/154 is open to attempt fixing this. Could you try installing httpcore from that branch and then see if the issue was resolved? Thanks!

```bash
pip install git+https://github.com/j178/httpcore.git@c30edf3#egg=httpcore
```

(Pip git install command from the top of my head, might need tweaking.)

**Comment by charkal233** [comment]
I use
> pip install git+https://github.com/j178/httpcore.git@0c06138f51f0e092352fb582fd6bb187a47a2cf1#egg=httpcore --upgrade
proxies = {'all://': httpx.Proxy('http://127.0.0.1:24000', mode='TUNNEL_ONLY')}
sess = httpx.Client(proxies=proxies) 
r = client.get("https://www.google.com") # <Response [200 OK]>
sess = httpx.Client(proxies=proxies, http2=True)
r = client.get("https://www.google.com") # <Response [200 OK]>
problem solved
