### ISSUE TITLE
Add support for Google's Brotli Python implementation

### ISSUE THREAD

**Issue by sethmlarson** [encode/httpx#117]
This is handled by urllib3 and it'd be pretty trivial to lift from there.

**Comment by tomchristie** [comment]
Is that different to the implementation that we currently support? https://github.com/encode/http3/blob/master/http3/decoders.py#L83

**Comment by sethmlarson** [comment]
Unfortunately it is: https://github.com/urllib3/urllib3/blob/master/src/urllib3/response.py#L103

**Comment by tomchristie** [comment]
Gotcha. What’s the difference?

**Comment by sethmlarson** [comment]
Brotlipy provides `decompress()`/`flush()`, Google's Brotli on provides `process()`

**Comment by halbow** [comment]
I can take a look at this !

**Comment by StephenBrown2** [comment]
This has been added in https://github.com/encode/httpx/pull/156

**Comment by sethmlarson** [comment]
Yep! Closing this issue. Thanks @StephenBrown2
