### ISSUE TITLE
Provide defaults for connection pool

### ISSUE THREAD

**Issue by bwelling** [encode/httpx#1173]
https://github.com/encode/httpx/blob/master/docs/advanced.md#custom-transports provides an example for configuring an httpx client with a custom connection pool, which is needed to specify a local address.  This example is overly complicated and fragile, though, as it requires far too much knowledge about the underlying httpcore interface.  

Specifically, if a user wants standard client behavior except for one small thing, that user is required to set a bunch of unrelated client parameters which have no visible defaults, as those defaults would typically be set by the httpx library code.  The values of some of these parameters will likely change over time, as will the set of parameters passed by the standard httpx code.  So, anything using the custom transport paradigm would either diverge, or the user would need to periodically poll httpx to update to the current set.

In a comment on encode/httpcore#100, I suggested that providing wrappers in httpx around `httpcore.SyncConnectionPool` and `httpcore.AsyncConnectionPool` that merge a set of user-provided configuration options with the defaults, and @tomchristie responded with `We could certainly think about switching our policy on httpcore defaults, yup.`.

It would certainly be a lot easier (as well as safer, and more future-proof) if code could do something like:
```
transport = httpcore.SyncConnectionPool(local_address="0.0.0.0")
client = httpx.Client(transport=transport)
```
if they wanted everything to operate as an httpx client normally would, except with a custom local address (that may not be the right interface, but the point is that it doesn't require specifying all of the other things that should be unchanged).

**Comment by tomchristie** [comment]
Resolved now that `httpx.HTTPTransport()` exists.
