### ISSUE TITLE
Do we have any plan to add proxy IP for a single request ?

### ISSUE THREAD

**Issue by Iflier** [encode/httpx#1194]
Hi developers,

This is a great work!

### Checklist

- [ ] There are no similar issues or pull requests for this yet.
- [ ] I discussed this idea on the [community chat](https://gitter.im/encode/community) and feedback is positive.

### Is your feature related to a problem? Please describe.

For the network data collection related jobs, sometimes, a single proxy IP may be invalid after making several requests. In this case, use a single proxy IP for each request, rather than use a Client instance maybe more appropriate. I know, we can set a proxy IP when create a Client(or AsyncClient) instance, while if the proxy ip used in Client instance become unavailable after several requests, we may need to create another Client instance, I'm not sure if say it like this is correct :-( .

## Describe the solution you would like.

Do we have any plan to enable `httpx.request(...)` has a `proxies` arg, just like `requests` do ?

**Comment by florimondmanca** [comment]
Hi,

Well true, Requests supports passing `proxies` on the high level API, so we might want to consider this as well. Not costly in terms of implementation, since it's mostly an extra argument to forward to the underlying client constructor.

https://requests.readthedocs.io/en/master/user/advanced/#proxies

**Comment by tomchristie** [comment]
Yup, we'd need to be clear that we're *not* supporting `client.request(..., proxies=...)`, but I don't see any reason why we shouldn't support it in the top-level helper functions, `httpx.request` & pals.

**Comment by Iflier** [comment]
Okey, I got it. Thanks for your clarification 👍 . @florimondmanca @tomchristie
