### ISSUE TITLE
Allow `proxies` in `httpx.request()` high-level API

### ISSUE THREAD

**Issue by florimondmanca** [encode/httpx#1195]
Spun up from #1194 

The high-level API functions such as `httpx.get()` and `httpx.post()` don't allow passing `proxies=...` yet (only possible on `Client`), but Requests does support this: https://requests.readthedocs.io/en/master/user/advanced/#proxies

We should add support for this argument:

```pycon
>>> import httpx
>>> proxies = "http://localhost:8899"
>>> r = httpx.get("https://example.com", proxies=proxies)
```

We may need to update some documentation (for example, the [HTTP Proxying](https://www.python-httpx.org/advanced/#http-proxying) docs *may* need to clarify that `proxies` does not _require_ using clients), but we can treat that as a follow-up if it's unclear what should be updated exactly.

**Comment by tomchristie** [comment]
Right, we may also want a note in the requests compat. section, because `Session.request(...)` allows a `proxies=...` argument, whereas `Client.request(...)` does not.

(Which is because of the knock on implications of our tighter Transport API vs. `requests` adapters.)
