### ISSUE TITLE
Separate `httpx.post(content=...)` from `httpx(data=...)`?

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#1210]
Currently we're following the `requests` API, with `data=...` representing one of:

* `str`/`bytes`/`byte iterator`/`byte aiterator` - Content to send in the body of the request.
* `dict` - Data to send in either a URLEncoded or Multipart request.

These are really two very different types of cases. One is for submitting HTML form data, the other is for uploading raw byte content. It's possible that we should consider if we want to diverge from `requests` here, in order to provide a more clear, consistent interface?

For example...

```python
# Send a POST request, with "abc" as the request body.
httpx.post(content=b'abc')

# Send a POST request, with URLEncoded data.
httpx.post(data={"field": "value"})

# Send a POST request, with MultiPart encoded data.
httpx.post(data={"field": "value"}, files=...)
```

Would be interested to see what others think of this?...

(Obviously we'd want a gradual deprecation if we *did* decide to take this on.)

**Comment by tomchristie** [comment]
So I'm starting to think that we might want to reopen this, and move towards `content=...` for byte content vs `data=...` for form encoded data only. Here's why I'm thinking that'll end up being able to give us a more consistent API throughout...

* We want to support `Response(content=...)`, it'd be nice if `Request(content=...)` mirrored that.
* A neat thing to do would be to drop `Response(stream=...)` and have the `content=...` allowed types be `bytes|byte iterator|byte aiterator|ByteStream`
* A neat thing to do would be to drop `Request(stream=...)` and have the `content=...` allowed types be `bytes|byte iterator|byte aiterator|ByteStream`

We could still support `data=<bytes|byte iterator>` but only for backwards compat purposes with requests, giving us a nice clear split between form data vs. json data vs. raw byte content.

Anyways, just getting my thoughts down here for now.

**Comment by florimondmanca** [comment]
Yes — I'm not against us adding support for `content=...` at all - that sounds like a very sensible naming, and nothing similar in Requests territory there, so all good.

What I was warning against was removing the `data=<bytes>` usage, which I believe we should keep for Requests compatibility purposes.

If we'd be to support `content=<bytes>` and `data=<bytes (for compat)|byte iterator>`, then that'd sound about right to me. :-)
