### ISSUE TITLE
Use `request.url == <str>` in test cases.

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#1228]
Several of our test cases make URL comparisons, using `request.url == httpx.URL(...)`, eg... https://github.com/encode/httpx/blob/master/tests/client/test_client.py#L186-L201

We should replace those with the more concise `request.url == "<str>"` throughout, since it reads more nicely, and works just as well.

**Comment by florimondmanca** [comment]
We'll probably need a `# type: ignore` comment alongside these usages since I believe mypy expects setting to `URL` instances (mypy limitation I believe?).

**Comment by tomchristie** [comment]
I *think* you might be misreading? This is for equality, `==`, rather than a property setter.

**Comment by tomchristie** [comment]
Oh right, because I got the issue title wrong. 🤣

**Comment by aitorres** [comment]
Hello! Would you like me to help with this issue?

**Comment by florimondmanca** [comment]
Anyone is free to jump in and discuss or submit a pull request for any issue, yup. :)

**Comment by eduzen** [comment]
Hi @florimondmanca, I created a pull request for this good first issue. I hope it is fine.
