### ISSUE TITLE
Python 3.7.7 _ssl fails to import with multiple conda environments with httpx

### ISSUE THREAD

**Issue by achapkowski** [encode/httpx#1233]
If you have a Python 3.6.x and Python 3.7.x conda environments on the same machine, the ```import _ssl``` will cause the ASyncClient to fail to load with an invalid DLL error.

1. Create a Python 3.6 environment and install httpx
2. Create a Python 3.7 environment and install httpx
3. From the 3.7 environment, run the following

```python
from httpx import Client
from httpx import AsyncClient
from httpx import Response, Request
```

4. Watch the `_ssl` module fail

**Comment by florimondmanca** [comment]
Hello,

Thanks for reporting, but — is there anything we should do on our side? Is https://github.com/conda-forge/httpx-feedstock of any help? If you're installing HTTPX via `conda install httpx`, perhaps that's an issue worth discussing there.

**Comment by achapkowski** [comment]
I am installing via ```conda install httpx```.  I am wondering if the SSL packaging isn't being installed properly, or a specific version needs to be set for 3.7.

**Comment by tomchristie** [comment]
Could you include the full error traceback? Doesn't sound like anything on our side, but perhaps we'll be able to help get it resolved all the same.
