### ISSUE TITLE
Add proxy support for AsyncClient

### ISSUE THREAD

**Issue by Kikey-y** [encode/httpx#1236]
Can you please add support for the async client? I was shocked that I can't use proxies with async and I had to use aiohttp, please add support for it. Thanks.

**Comment by tomchristie** [comment]
Hiya. We have identical proxy support in both sync & async. You'd need to explain a bit more what issue you were having?

**Comment by Kikey-y** [comment]
Whenever I try to post using async or sync client, using the proxies parameter, it says `TypeError: post() got an unexpected keyword argument 'proxies'`
Here's some code:

`import httpx, asyncio

cl = httpx.AsyncClient()

async def test():

    r = await cl.post('https://httpbin.org/post', proxies={"http": "http://user:pass@ip:port"})
    print(r.json())

asyncio.run(test())`

It says the error above, which made me think there's no support for proxies on async, sorry. How do I fix that?

**Comment by tomchristie** [comment]
We probably need to make it more clear in the docs that `proxies=...` should be passed to the client instance, eg. `AsyncClient(proxies=...)`

**Comment by Kikey-y** [comment]
> We probably need to make it more clear in the docs that `proxies=...` should be passed to the client instance, eg. `AsyncClient(proxies=...)`

Oh I'm sorry, since I switched from requests to this one cause I've heard this is the async version of requests, i thought they'd work the same. My bad.
And in my opinion I think it's better to have to proxies parameter since it'll add more flexibility, at least in my case, since I need only one asyncClient to run multiple requests through it, some of which aren't proxied.
But for now, I'll just use the context manager, thanks!
