### ISSUE TITLE
How to work with session adapters as in requests?

### ISSUE THREAD

**Issue by upworkjob** [encode/httpx#1263]
```
import requests
import collections

class SortedHTTPAdapter(requests.adapters.HTTPAdapter):
    def add_headers(self, request, **kwargs):
        request.headers = collections.OrderedDict(
            ((key, value) for key, value in sorted(request.headers.items()))
        )

session = requests.Session()
session.mount("http://", SortedHTTPAdapter())
session.mount("https://", SortedHTTPAdapter())

```

```
client = httpx.AsyncClient(http2=True)
client.mount("http://", SortedHTTPAdapter())
AttributeError: 'AsyncClient' object has no attribute 'mount'
```

**Comment by florimondmanca** [comment]
Hi,

This API is not supported by HTTPX, and I can't say for now if we're going to add something similar (since we don't have a notion of "adapter").

You might want to look through issues, we do have some ongoing discussions about a "Mount API", as well as "Event hooks", both of which could address the kind of use case you're exposing here.

Thanks!

**Comment by upworkjob** [comment]
> Hi,
> 
> This API is not supported by HTTPX, and I can't say for now if we're going to add something similar (since we don't have a notion of "adapter").
> 
> You might want to look through issues, we do have some ongoing discussions about a "Mount API", as well as "Event hooks", both of which could address the kind of use case you're exposing here.
> 
> Thanks!

Is there any way to have more precise control over headers sent? Like using OrderedDict and do not changing case of letters?

**Comment by florimondmanca** [comment]
@upworkjob No, that's not possible and most likely won't be.

Dictionaries are officially ordered as of Python 3.7, though, and the case problem you're mentioning is probably related to #538 (preserving outgoing headers case), which is a long-running issue that hopefully gets resolved some time in the future. :-)

**Comment by tomchristie** [comment]
Actually, we need to do a better job of documenting this. The Transport API is our equivalent to requests "adapters", although we haven't yet documented that at https://www.python-httpx.org/compatibility/

The "Custom Transports" docs give a bit of info about using customized transport classes, which could include subclassing `httpcore.SyncConnectionPool` and overriding the `request` method to modify its behaviour. - https://www.python-httpx.org/advanced/#custom-transports

We're working on preserving header casing at https://github.com/python-hyper/h11/pull/103

We also need to do a bit of work on making it easier to instantiate a connection pool, without having to specify all the configuration arguments explicitly.

**Comment by septatrix** [comment]
Definitely +1 for adding this to the docs. I has a case where a website directed me to a custom protocol (which the browser would normally handle) and had to mount a adapter for this in requests. This also seems to work fine with custom transports and I only stumbled upon this after finding this issue.
