### ISSUE TITLE
Disable TLSv1 and TLSv1.1 by default

### ISSUE THREAD

**Issue by sethmlarson** [encode/httpx#127]
TLSv1.2 was released over 10 years ago and is widely deployed.

> The Alexa Top 1 Million Analysis from February 2018 shows that for the sites surveyed, the vast majority support TLSv1.2 (98.9 percent), with a mere 0.8 percent using TLSv1.0 and an even smaller percentage using TLSv1.1.

Quote from [IETF Draft on Deprecating TLSv1 and TLSv1.1 from 2018](https://tools.ietf.org/id/draft-moriarty-tls-oldversions-diediedie-00.html)

We may be able to tighten up the ciphers we're enabling by default as well as a result of this change.

**Comment by halbow** [comment]
I can take a look at this !

**Comment by sethmlarson** [comment]
Great! Reach out if you need any help or have questions. :)
