### ISSUE TITLE
Allow use the async api without instantiate a client

### ISSUE THREAD

**Issue by dsvictor94** [encode/httpx#131]
Hi!

Would be more intuitive and more symmetric if the asynchronous api were accessible without instantiating the client. 

e.g

```Python
import aiohttpx from httpx
r = await aiohttpx.get('https://www.example.com/')
```

Thank you for this wonderful project.

**Comment by tomchristie** [comment]
Thanks! I don’t think that’s something we’re likely to do. async is useful specifically for making highly concurrent number of requests, in which case you always want to be using a Clients connection pool. (If anything I’d prefer dropping the top level API entirely and always requiring a client instance)
