### ISSUE TITLE
Wrong elapsed timedelta

### ISSUE THREAD

**Issue by enguerranchevalier** [encode/httpx#1310]
### Checklist

- [ X] The bug is reproducible against the latest release and/or `master`.
- [ X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

The `elapsed` argument obtained following a stream request seems completely incoherent.

### To reproduce

Code example with httpx 0.15.1:

```
import httpx

client = httpx.Client()

with client.stream("GET", "https://httpbin.org/basic-auth/user/pass", auth=("user", "pass")) as r:
   print(r)

print(r.elapsed)
```

### Expected behavior

Result got with httpx 0.14.3: `0:00:02.275297`

### Actual behavior

Result got with httpx 0.15.1: `1 day, 17:07:15.687523`

### Debugging material

![image](https://user-images.githubusercontent.com/12841394/93995268-15707c00-fd91-11ea-913e-a6741a251d1d.png)

### Environment

- OS: Linux
- Python version: 3.7.5
- HTTPX version: 0.15.1
- Async environment: None
- HTTP proxy: No
- Custom certificates: No

Thanks,

**Comment by tomchristie** [comment]
👀 Yikes.
