### ISSUE TITLE
Set a list of DNS addresses for transport

### ISSUE THREAD

**Issue by Dexus77** [encode/httpx#1319]
I did not find this feature in the documentation, if this feature already exists, please tell me how to do it.

I am using aiohttp in the current project, but it has a big flaw, it does not support HTTP/2.

When trying to replace it with httpx, I got an error - Name or service not known.  I must say right away that this is not a problem with httpx, but with my DNS server on which there is a limit on the number of requests.

Therefore, I have to change to Google servers, for example like this

resolver = AsyncResolver(nameservers=["8.8.8.8", "8.8.4.4"])
async with ClientSession(connector=TCPConnector(limit=0, resolver=resolver)) as session:

Is it possible to implement something like this in httpx?

**Comment by tomchristie** [comment]
We don't currently support customising DNS resolution, no.

I guess we'll want something like this on our backlog, but it's not likely to happen super quickly.

**Comment by Dexus77** [comment]
Thanks for your reply, have a nice day.

**Comment by florimondmanca** [comment]
Dexus77 Hmm, isn't this something you can tweak at your system / OS level? On Mac I know there are settings for choosing which DNS to use in general, prove same for Linux and Windows. Same than Tom though, I don't see us supporting this very quickly, sounds like it would require very careful design and implementation.

**Comment by Dexus77** [comment]
I did not consider this option.  registering several thousand domain
servers in the OS is most likely not a good idea.

чт, 24 вер. 2020 о 11:46 Florimond Manca <notifications@github.com> пише:
