### ISSUE TITLE
Remove asyncio usage within SSLConfig

### ISSUE THREAD

**Issue by sethmlarson** [encode/httpx#132]
Should have to pass in the backend to call `run_in_threadpool()` to make it agnostic to backend being used.

**Comment by tomchristie** [comment]
Alternate. We don't use `run_in_threadpool` in the Config at all, and instead do that within the `Connection`... https://github.com/encode/httpx/blob/edd702955ef670a365122ac96a8cd0064895de7e/httpx/dispatch/connection.py#L69

(We'd want to inspect if the `ssl` property was already set, and only call use a threadpooled call to  `load_ssl_context` if needed.)
