### ISSUE TITLE
Implement http+unix dispatcher

### ISSUE THREAD

**Issue by sethmlarson** [encode/httpx#133]
Lots of users for Docker, Sentry, etc use the `http+unix://...` URLs. Might necessitate additional backend interface if we intend this to be first-class support.

**Comment by tomchristie** [comment]
Any good reference describing this scheme?

I'd expect that this is more of a good case for us ensuring that the dispatcher interface is sufficiently capable, and sufficiently well documented. If we can allow third party packages to support themore complex use cases, without building them into the core package itself, then I think that'd be a great thing.

**Comment by tomchristie** [comment]
Let's treat this as out-of-scope at this point in time.
