### ISSUE TITLE
socket.gaierror under trio not casted into httpx.ConnectError

### ISSUE THREAD

**Issue by kontsaki** [encode/httpx#1369]
Hello

### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### To reproduce
```
import httpx
import trio


async def test():
    async with httpx.AsyncClient() as client:
        try:
            await client.get("http://thisdoesnotexistasdf.com")
        except httpx.ConnectError:
            print("oops")

trio.run(test)
```

### Expected behavior

should raise `httpx.ConnectError`

### Actual behavior

raises `socket.gaierror`

### Environment

- OS:  linux
- Python version:  3.8.5
- HTTPX version:  0.16.1 and master 1bc3b01
- Async environment:  trio, not happening on asyncio
- trio version: 0.17.0

**Comment by jcugat** [comment]
Thanks for reporting this! It's an httpcore issue that was just fixed yesterday in https://github.com/encode/httpcore/pull/225

**Comment by kontsaki** [comment]
oh i should have searched through httpcore issues as well, thank you!

**Comment by florimondmanca** [comment]
Still meaning to issue a bug fix release on the HTTPCore side, hopefully tomorrow, but feel free to ping. :)

**Comment by jcugat** [comment]
No worries @kontsaki 😄
