### ISSUE TITLE
EOF occurred in violation of protocol

### ISSUE THREAD

**Issue by CLannadZSY** [encode/httpx#1371]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [ ] There are no similar issues or pull requests to fix it yet.

### Describe the bug
this is my code
```python
import httpx

headers = {
    'accept': 'text/html,*/*',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'zh-CN,zh;q=0.9,en;q=0.8',
    'origin': 'https://www.amazon.com',
    'user-agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36',
}

url = 'https://www.amazon.com/'
response = httpx.get(url, headers=headers)
print(response.status_code)
```
error img
![image](https://user-images.githubusercontent.com/38000492/97390327-7bfc3300-1917-11eb-8b60-54f7cfe39ad8.png)

### Environment

- OS: Windows
- Python version: 3.8.6
- HTTPX version: 0.16.1
- Custom certificates: no

**Comment by cdeler** [comment]
@CLannadZSY please could you provide me with the full stacktrace, as I cannot reproduce the issue locally

**Comment by CLannadZSY** [comment]
@cdeler I reinstalled my python environment and httpx, this problem was solved

**Comment by cdeler** [comment]
If you hit it again, just store all the stack trace, and reopen the issue
