### ISSUE TITLE
Nicer repr for `httpx.Cookie`, displaying stored cookies.

### ISSUE THREAD

**Issue by Mavic111** [encode/httpx#1377]
When i'm trying to save cookies with these code:
with open('Cookies/cookies.txt', 'w') as f:
        json.dump(dict(client.cookies), f)

i got error:
raise CookieConflict(message)
httpx.CookieConflict: Multiple cookies exist with name=client_type

i'm also curios, how to print all session cookies like in requests module (using print(session.cookies)
when im using print(client.cookies) with httpx module, the result was <httpx.Cookies object at 0x03B50E20>

can you help me?

**Comment by VeNoMouS** [comment]
@Mavic111 use `client.cookies.jar` to print, there will be more than 1 cookie with the same key name in there, so when your converting to a dict, that is your issue.

**Comment by tomchristie** [comment]
Requests will give you the same behaviour wrt. multiple cookies with the same name...

```python
>>> dict(s.cookies)
...
requests.cookies.CookieConflictError: There are multiple cookies with name, 'name'
```

Tho I. would agree that our `Cookies` repr would be nicer if it displayed the stored cookies. In the same way that `RequestsCookieJar` does...

```python
>>> print(s.cookies)
<RequestsCookieJar[<Cookie name=value for httpbin.org/>, <Cookie name=value2 for www.httpbin.org/>]>
```

**Comment by tomchristie** [comment]
I've retitled the issue to reflect the one aspect of this that I think we could improve on.
