### ISSUE TITLE
HeaderTypes should include None?

### ISSUE THREAD

**Issue by astrojuanlu** [encode/httpx#1380]
While trying to call `AsyncClient` like this:

```python
async with httpx.AsyncClient(headers=None) as client:
    r = await client.get(pass_url)
```

got this MyPy error:

```
incompatible type "None"; expected
"Union[Headers, Dict[str, str], Dict[bytes, bytes], Sequence[Tuple[str, str]], Sequence[Tuple[bytes, bytes]]]"
 [arg-type]
            async with httpx.AsyncClient(headers=None) as client:
                                                 ^
Found 1 error in 1 file (checked 7 source files)
```

which makes total sense, because:

https://github.com/encode/httpx/blob/1bc3b0188a65cfa3f3dc8b85a0ed0e78d437ba5e/httpx/_types.py#L43-L49

However, the very signature of the class initializer specifies `None` as the default value:

https://github.com/encode/httpx/blob/1bc3b0188a65cfa3f3dc8b85a0ed0e78d437ba5e/httpx/_client.py#L1195

Therefore, either your MyPy checks on CI are not strict enough :) or there's something I'm not seeing.

I think this would make the trick:

```diff
diff --git a/httpx/_types.py b/httpx/_types.py
index 776df1d8..3ddcc1be 100644
--- a/httpx/_types.py
+++ b/httpx/_types.py
@@ -41,6 +41,7 @@
 ]
 
 HeaderTypes = Union[
+    None,
     "Headers",
     Dict[str, str],
     Dict[bytes, bytes],
```

but I don't know if that breaks consistency with other parameters (just started using the library 10 minutes ago, awesome project by the way! :heart:)

**Comment by StephenBrown2** [comment]
I believe that having `None` as the default value simply means that it is an optional parameter, as seen in `BaseClient`: https://github.com/encode/httpx/blob/1bc3b0188a65cfa3f3dc8b85a0ed0e78d437ba5e/httpx/_client.py#L100
and allowing that to get passed all the way back to the model: https://github.com/encode/httpx/blob/1bc3b0188a65cfa3f3dc8b85a0ed0e78d437ba5e/httpx/_models.py#L546-L547
which then initializes it as an empty list.

What is your purpose in passing `None` explicitly to the `headers` param? That is intended to be used to set custom headers for the requests made with the Client: https://www.python-httpx.org/advanced/#sharing-configuration-across-requests

**Comment by astrojuanlu** [comment]
> What is your purpose in passing `None` explicitly to the `headers` param?

For example:

```
$ cat test.py 
from typing import Dict, Optional
import httpx

async def my_wrapper_function(headers: Optional[Dict[str, str]] = None) -> None:
    async with httpx.AsyncClient(headers=headers) as client:
        ...
$ mypy test.py --pretty --strict
test.py:5: error: Argument "headers" to "AsyncClient" has incompatible type
"Optional[Dict[str, str]]"; expected
"Union[Headers, Dict[str, str], Dict[bytes, bytes], Sequence[Tuple[str, str]], Sequence[Tuple[bytes, bytes]]]"
 [arg-type]
        async with httpx.AsyncClient(headers=headers) as client:
                                             ^
Found 1 error in 1 file (checked 1 source file)
```

My point is that, using MyPy strict mode, defining a function the way it's defined in httpx gives an error:

```
$ cat test2.py 
from typing import Dict

def foo(headers: Dict[str, str] = None) -> None:
    print(headers)
$ mypy test2.py --strict --pretty
test2.py:4: error: Incompatible default for argument "headers" (default has type "None",
argument has type "Dict[str, str]")  [assignment]
    def foo(headers: Dict[str, str] = None) -> None:
                                      ^
Found 1 error in 1 file (checked 1 source file)
```

**Comment by florimondmanca** [comment]
Hey!

Nah, I don't think we want to put `None` in the type definition. I guess it _could_ be better solved by adhering to `strict_optional` ourselves, but this isn't something we do anywhere yet and so I'd tend to push back on it for now.

Could you just go with...?

```python
Client(..., headers=headers or {})
```

Or something along these lines. In other words: address the strictness into your code before calling into HTTPX. :-)

That ought to make stricter mypy happy, correct?

**Comment by astrojuanlu** [comment]
Understood - it's a mild annoyance, but absolutely bearable of course :) I was actually doing that already. At least this issue stands here in case someone else stumbles upon this problem.

Thanks!

**Comment by florimondmanca** [comment]
Right! Well I'll close this off but sure, it will be visible in the history. :)
