### ISSUE TITLE
Update compatibility documentation 

### ISSUE THREAD

**Issue by VeNoMouS** [encode/httpx#1383]
Could the link in https://github.com/encode/httpx/blob/master/docs/compatibility.md for `Request instances` be updated from `https://github.com/encode/httpx/blob/master/advanced#request-instances` to `https://github.com/encode/httpx/blob/master/docs/advanced.md#request-instances`

**Comment by florimondmanca** [comment]
@VeNoMouS Hi, sure, happy to review any quick pull request for fixing that link URL. :-)

**Comment by VeNoMouS** [comment]
lol, sure np, ill do a pr in a bit
