### ISSUE TITLE
How should i upload files with 'multipart/form-data' encoding?

### ISSUE THREAD

**Issue by LR1093141031** [encode/httpx#1402]
![image](https://user-images.githubusercontent.com/50727631/100530922-08f61d00-3233-11eb-9a60-a88ce2b8bdc7.png)

**Comment by LR1093141031** [comment]
have been tried 
```
from requests_toolbelt import MultipartEncoder
form_data = MultipartEncoder(fields={"file": (f"{file_name}", open(img_file_full_path, 'rb'), r"image/jpeg")})
sauce.post(url=self.search_url, headers=self.search_headers, data=form_data.__dict__['fields']))
```

by using MultipartEncoder, tried to fill data parameter with a dict.
seems in vain

**Comment by florimondmanca** [comment]
@LR1093141031 Hi,

We have a section about this in the docs that can probably help you: https://www.python-httpx.org/advanced/#multipart-file-encoding

If you'd like further help please try and reach out to the community chat instead, as we keep this tracker focused on development: https://gitter.im/encode/community

Thanks!
