### ISSUE TITLE
HTTP2 Sync Client blocked after attempting to establish a downchannel to Alexa Voice Service

### ISSUE THREAD

**Issue by vong0** [encode/httpx#1410]
Hi,

### Describe the bug

So I'm trying to establish a downchannel with Alexa Voice Service (AVS) following the docs at:
- https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/manage-http2-connection.html

According to AVS I need to setup a downchannel in a half-closed state that lasts the duration of the HTTP2 connection. This downchannel is used to deliver messages from AVS to my client.
```
Downchannel: 
- A stream you create in your HTTP/2 connection, which is used to deliver directives from the cloud to your client. 
- The downchannel remains open in a half-closed state from the device and open from AVS for the life of the connection. 
- The downchannel is primarily used to send cloud-initiated directives and audio attachments to your client.
```

To do this, I create a separate thread that issues a GET request to the endpoint specified by Alexa:
- I am using your HTTP2 Sync Client
- I have tried both a normal GET request and a streaming GET request
- Once the thread have started, I try to continue issue any subsequent requests to do something operation...

Problem:
- Once the thread has started i.e. the one that sends a GET request to the Alexa Downchannel Endpoint
- All subsequent client requests are blocked.

### To reproduce

My code and setup instructions can be found at:
- https://github.com/vong0/alexa-client-python/
- the script to run is the `main_downchannel.py` [Link](https://github.com/vong0/alexa-client-python/blob/master/main_downchannel.py)

### Expected behavior
The behaviour I'm expecting is that 

### Environment
OS: Windows 10 running Ubuntu WSL1
Python version: 3.6.9
HTTPX version: 0.16.1

**Comment by florimondmanca** [comment]
@vong0 Hello! Could you clarify how this relates to the other Alexa / HTTP/2 ticket?

**Comment by florimondmanca** [comment]
@vong0 Theres a warning on that docs page about a possible necessity to `/ping` the connection so it doesn't become considered stale by the service:

>  Warning: If using libcurl, your client must make a GET request to /ping every 5 minutes to maintain the connection. For details, see Ping and Timeout below.

From my POV not doing this could explain why you're seeing errors that tend to indicate Alexa closed the connection.

**Comment by florimondmanca** [comment]
(Honestly, this use of HTTP/2 as a 2-way communication channel is uhh... Weird. Why not WebSocket? It's got PING built-in. It's got clear channel-like semantics. No weird ad-hoc protocol thingies required. Huh.)

**Comment by vong0** [comment]
> @vong0 Hello! Could you clarify how this relates to the other Alexa / HTTP/2 ticket?

This is a separate thing so that I can receive messages from Alexa.
- For example, if you tell Alexa to set an alarm in 5 minutes, this response isn't directly related to your original message
- That's why they have a long-running downchannel and 2-way communication channel.

**Comment by vong0** [comment]
> @vong0 Theres a warning on that docs page about a possible necessity to `/ping` the connection so it doesn't become considered stale by the service:
> 
> > Warning: If using libcurl, your client must make a GET request to /ping every 5 minutes to maintain the connection. For details, see Ping and Timeout below.
> 
> From my POV not doing this could explain why you're seeing errors that tend to indicate Alexa closed the connection.
> 
> Actually that's exactly what their "Ping and Timeouts" section says:
> 
> > Your client must perform one of the following actions, failure to do so will result in a closed connection:
> > 
> > * Send a PING frame to AVS every 5 minutes when the connection is idle.
> > * Make a GET request to /ping every 5 minutes when the connection is idle.
> 
> https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/manage-http2-connection.html#ping-timeout
> 
> There's also a section about "server initiated disconnects" indicating that the client should handle it and be ready to issue a new connection. I believe this _should_ already be handled automatically by HTTPCore's connection pooling, though, but their dance seems to be quite specific and not exactly what we do as a vanilla strategy:
> 
> > When the server initiates a disconnect, your client should:
> > 
> > 1. Open a new connection and route any new requests through it.
> > 2. Close the old connection **after all open requests have been processed** and their corresponding streams have been gracefully closed.
> > 3. Maintain a connection to any stream URL established before the disconnect was initiated (e.g. Amazon Music, Audible, etc.). A stream playing before a server-initiated disconnect occurs should continue to play as long as bytes are available.
> > 
> > If the attempt to create a new connection fails, the client is expected to retry with an exponential back-off.

For the /ping:
- The ping timeout runs for 5 minutes. In my code I ping before I try to establish the downchannel. So the connection should not have been closed.
- I've tested this in an interactive python shell
    - I've sent a ping request and I got an OK response
    - I then try to issue a GET request to "/v20160207/directives" (to establish the downchannel) and then the program stalls
    - I ctrl+c to stop the previous command
    - I then try to resend the ping request and I still get an OK response
    - The only time I cannot send/receive any HTTP2 requests is when the HTTP2 client is still waiting for the GET request to establish the downchannel
- But it seems that once I try issue a GET request or a streaming GET request to "/v20160207/directives", no subsequent requests can be made.

It seems that waiting on the GET request blocks all subsequent HTTP2 requests from working. Not sure why this is the case.
- It might be an issue with Alexa but other people have seem to have gotten it working in different languages using different HTTP2 libraries
- e.g. OKHTTP: https://stackoverflow.com/questions/42214222/okhttp-half-closed-stream-for-avss-downchannel-on-android

**Comment by tomchristie** [comment]
Given that there's be a substantial amount of change in `httpcore` since this issue, so I'm going to close this off as stale.
I did have a bit of a look over Amazon's AVS docs, but there's no obviously easy way for me to test this out.

On the off-chance that you're still interested in this @vong0, after all this time, then I'll happily re-open this and spend some time working through it with you. I'd also be very interested in hearing from any other folks working with HTTP/2 and AVS.

**Comment by los-floppos** [comment]
Hey there, 

Approx. one year later I'm running into the same issue. A call against the AVS API with curl works out of the box, though: 
```bash
curl -v --connect-timeout 0 --oauth2-bearer "assToken" --http2 $BASE_URL/v20160207/directives
```

Can you help me out how to achieve a "downchannel with a half-open state" with httpx?
