### ISSUE TITLE
URL.join behaviour is incorrect.

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#142]
Our `URL.join` behavior currently isn't as expected. It should be in line with rfc3986#section-5.2, and Python's existing `urljoin`.

It ain't...

```python
>>> httpx.URL('http://www.example.com/some/directory/abc.html').join('../../foo.html')
URL('http://www.example.com/some/directory/foo.html')
```

**Comment by sethmlarson** [comment]
Thoughts on using the built-in `urljoin` function (this is what urllib3 does)? Otherwise we could use [`rfc3986.URIReference.resolve_with()`](https://github.com/python-hyper/rfc3986/blob/master/src/rfc3986/_mixin.py#L231) as well.

**Comment by tomchristie** [comment]
Strongly prefer using `resolve_with()` which is what the intent already is: https://github.com/encode/httpx/blob/master/httpx/models.py#L201

Evidently not quite right tho.
