### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by juniorhero** [encode/httpx#1425]
pip install httpx

Collecting httpx
  Could not find a version that satisfies the requirement httpx (from versions: )
No matching distribution found for httpx

**Comment by florimondmanca** [comment]
@juniorhero Hello — could you share your system specifications…? There are some hints in the default issue template, feel free to have a look at it.

**Comment by juniorhero** [comment]
i tried on kali linux 2020.4 got this error
i got same error on ubuntu and linux mint as well
I dont know what is going wrong

**Comment by juniorhero** [comment]
it turns out pip is not installed by default on any of this distros
and had to manually install

**Comment by juniorhero** [comment]
then i tried with pip3 install httpx 

though installation completes successfully


when httpx command is run
httpx: command not found

**Comment by johtso** [comment]
@juniorhero httpx is a python library, not a command line tool.

**Comment by florimondmanca** [comment]
@juniorhero Looks like you were able to install HTTPX now. Going to close this for now. For general usage of Python and pip I'd recommend doing some research on getting started with Python. If you need specific help for using HTTPX, let's head over to the chat instead: https://gitter.im/encode/community Thanks!
