### ISSUE TITLE
Not using selected ciphers

### ISSUE THREAD

**Issue by drain** [encode/httpx#1427]
### Description
When sending an http2 request, four extra ciphers get added. The goal here is to mimic the okhttp ciphers and get identical ja3 hashes. Since these ciphers are imported elsewhere it returns a different hash. 

Here are the 4 ciphers that are causing the problem:
[1302]	TLS_AES_256_GCM_SHA384
[1303]	TLS_CHACHA20_POLY1305_SHA256
[1301]	TLS_AES_128_GCM_SHA256
[00FF]	TLS_EMPTY_RENEGOTIATION_INFO_SCSV

### Code
```
import httpx, ssl

ctx = ssl.SSLContext()
CIPHERS = 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384'

ctx.set_ciphers(CIPHERS)
ctx.set_alpn_protocols(["h2", "http/1.1"])
client = httpx.Client(verify=ctx, proxies={"https" : "http://127.0.0.1:8888"})

r = client.get("https://ja3er.com/json")
```

### Expected
[C02B]	TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
[C02C]	TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
[CCA9]	TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
[C02F]	TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
[C030]	TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
[CCA8]	TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
[C013]	TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
[C014]	TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
[009E]	TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
[009F]	TLS_DHE_RSA_WITH_AES_256_GCM_SHA384

### Actual
[1302]	TLS_AES_256_GCM_SHA384
[1303]	TLS_CHACHA20_POLY1305_SHA256
[1301]	TLS_AES_128_GCM_SHA256
[C02B]	TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
[C02C]	TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
[CCA9]	TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
[C02F]	TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
[C030]	TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
[CCA8]	TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
[C013]	TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
[C014]	TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
[009E]	TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
[009F]	TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
[00FF]	TLS_EMPTY_RENEGOTIATION_INFO_SCSV

**Comment by JayH5** [comment]
This seems more like a Python/OpenSSL question than an httpx or http/2-specific question.

> Here are the 4 ciphers that are causing the problem:
[1302] TLS_AES_256_GCM_SHA384
[1303] TLS_CHACHA20_POLY1305_SHA256
[1301] TLS_AES_128_GCM_SHA256
[00FF] TLS_EMPTY_RENEGOTIATION_INFO_SCSV

The first 3 of these are TLS v1.3 ciphers, so my guess would be that the Java/OpenSSL version used with okhttp doesn't support TLS v1.3 while the Python/OpenSSL version used with httpx does. You could, in theory, disable TLS v1.3 in your SSLContext.

The last one seems to be a workaround for an SSL issue and it doesn't seem possible (or a good idea) to remove (see various [SO questions](https://stackoverflow.com/questions/35254883/avoid-sending-tls-empty-renegotiation-info-scsv-cipher-in-tls-client-hello)).

You can see what ciphers are used by OpenSSL for a given cipher string like so:
```
❯ openssl version
OpenSSL 1.1.1i  8 Dec 2020

❯ openssl ciphers -s -V 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384'
          0x13,0x02 - TLS_AES_256_GCM_SHA384  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(256) Mac=AEAD
          0x13,0x03 - TLS_CHACHA20_POLY1305_SHA256 TLSv1.3 Kx=any      Au=any  Enc=CHACHA20/POLY1305(256) Mac=AEAD
          0x13,0x01 - TLS_AES_128_GCM_SHA256  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(128) Mac=AEAD
          0xC0,0x2B - ECDHE-ECDSA-AES128-GCM-SHA256 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AESGCM(128) Mac=AEAD
          0xC0,0x2C - ECDHE-ECDSA-AES256-GCM-SHA384 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AESGCM(256) Mac=AEAD
          0xCC,0xA9 - ECDHE-ECDSA-CHACHA20-POLY1305 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=CHACHA20/POLY1305(256) Mac=AEAD
          0xC0,0x2F - ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AESGCM(128) Mac=AEAD
          0xC0,0x30 - ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AESGCM(256) Mac=AEAD
          0xCC,0xA8 - ECDHE-RSA-CHACHA20-POLY1305 TLSv1.2 Kx=ECDH     Au=RSA  Enc=CHACHA20/POLY1305(256) Mac=AEAD
          0xC0,0x13 - ECDHE-RSA-AES128-SHA    TLSv1 Kx=ECDH     Au=RSA  Enc=AES(128)  Mac=SHA1
          0xC0,0x14 - ECDHE-RSA-AES256-SHA    TLSv1 Kx=ECDH     Au=RSA  Enc=AES(256)  Mac=SHA1
          0x00,0x9E - DHE-RSA-AES128-GCM-SHA256 TLSv1.2 Kx=DH       Au=RSA  Enc=AESGCM(128) Mac=AEAD
          0x00,0x9F - DHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=DH       Au=RSA  Enc=AESGCM(256) Mac=AEAD
```

**Comment by drain** [comment]
Thank you! Disabling TLS v1.3 did the trick.

**Comment by JuMPBELL** [comment]
> Thank you! Disabling TLS v1.3 did the trick.

its a nice idea, but how to disable TLS1.3?
