### ISSUE TITLE
typing.Optional for AsyncClient parameters

### ISSUE THREAD

**Issue by altendky** [encode/httpx#1439]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

Many of the `AsyncClient` parameters allow `None` (including having that as the default) but are not type hinted as optional resulting in Mypy messages like below.  For example, the optional `app` parameter.

https://github.com/encode/httpx/blob/f4165e9e091f7ca622a996ce531a2e8638e941a0/httpx/_client.py#L1214

### Expected behavior

`None` and `typing.Optional` hinted values being passed to these parameters do not cause an error or warning.

### Actual behavior

```
qtrio/examples/download.py:155: error: Argument "app" to "AsyncClient" has incompatible type "Optional[QuartTrio]"; expected "Callable[..., Any]"
```

### Debugging material

n/a

### Environment

- OS: Ubuntu Linux 20.04
- Python version: 3.9.0
- HTTPX version: 0.16.1
- Async environment: Trio
- HTTP proxy: no
- Custom certificates: no

### Additional context

I can submit a PR with the added `typing.Optional` but figured I would start with a ticket to make sure there wasn't a reason they should not be added.  I looked around and noted that other places are using `typing.Optional` so it doesn't seem like there is a global exclusion of their use.

I tried adding the following to attempt to allow implicit optionals for quart-trio, but it isn't working.  Maybe I need to file a Mypy bug on that topic...

```ini
[mypy-quart_trio.*]
no_implicit_optional = False
```

Thanks for your time and consideration.

Cheers,
-kyle

**Comment by florimondmanca** [comment]
@altendky Hello!

Could you share sample code snippets that allow reproducing the mypy error?

For example, does this show as an error?

```python
from typing import Optional, Callable
import httpx

app: Optional[Callable]
client = httpx.AsyncClient(app=app)
```

Also, you've tried "no implicit optional", but could it be related to mypy's "strict optional" mode? One of them requires the type hints to have Optional so that a None value can effectively be passed, even if the default is None.

**Comment by altendky** [comment]
Hi @florimondmanca.

It was late and my error in regards to configuring mypy is now obvious...  I was modifying the configuration for `quart_trio` not `httpx`.  So that's silly me.  My apologies that noise.  But, that was just my 'workaround' for the actual ticket topic.

Here's an example, as requested.

```
cat > x.py << EOF
import typing

import httpx


optional_app: typing.Optional[typing.Callable]
httpx.AsyncClient(app=optional_app)

none_app: None
httpx.AsyncClient(app=none_app)
EOF
cat > mypy.ini << EOF
[mypy]
no_implicit_optional = True
EOF
python3.9 -m venv venv
venv/bin/pip install --upgrade pip setuptools wheel
venv/bin/pip install httpx==0.16.1 mypy==0.790
venv/bin/pip freeze
venv/bin/mypy x.py
```

Resulting in:
```
x.py:7: error: Argument "app" to "AsyncClient" has incompatible type "Optional[Callable[..., Any]]"; expected "Callable[..., Any]"
x.py:10: error: Argument "app" to "AsyncClient" has incompatible type "None"; expected "Callable[..., Any]"
Found 2 errors in 1 file (checked 1 source file)
```

<details> <summary>Full shell transcript</summary>

```bash
$ cat > x.py << EOF
> import typing
> 
> import httpx
> 
> 
> optional_app: typing.Optional[typing.Callable]
> httpx.AsyncClient(app=optional_app)
> 
> none_app: None
> httpx.AsyncClient(app=none_app)
> EOF
```

```bash
$ cat > mypy.ini << EOF
> [mypy]
> no_implicit_optional = True
> EOF
```

```bash
$ python3.9 -m venv venv
```

```bash
$ venv/bin/pip install --upgrade pip setuptools wheel
Collecting pip
  Using cached pip-20.3.3-py2.py3-none-any.whl (1.5 MB)
Collecting setuptools
  Using cached setuptools-51.1.1-py3-none-any.whl (2.0 MB)
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: pip, setuptools, wheel
  Attempting uninstall: pip
    Found existing installation: pip 20.2.3
    Uninstalling pip-20.2.3:
      Successfully uninstalled pip-20.2.3
  Attempting uninstall: setuptools
    Found existing installation: setuptools 49.2.1
    Uninstalling setuptools-49.2.1:
      Successfully uninstalled setuptools-49.2.1
Successfully installed pip-20.3.3 setuptools-51.1.1 wheel-0.36.2
```

```bash
$ venv/bin/pip install httpx==0.16.1 mypy==0.790
Collecting httpx==0.16.1
  Using cached httpx-0.16.1-py3-none-any.whl (65 kB)
Collecting mypy==0.790
  Using cached mypy-0.790-py3-none-any.whl (2.4 MB)
Collecting httpcore==0.12.*
  Using cached httpcore-0.12.2-py3-none-any.whl (54 kB)
Collecting h11==0.*
  Using cached h11-0.11.0-py2.py3-none-any.whl (54 kB)
Collecting sniffio
  Using cached sniffio-1.2.0-py3-none-any.whl (10 kB)
Collecting mypy-extensions<0.5.0,>=0.4.3
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting rfc3986[idna2008]<2,>=1.3
  Using cached rfc3986-1.4.0-py2.py3-none-any.whl (31 kB)
Collecting typed-ast<1.5.0,>=1.4.0
  Using cached typed_ast-1.4.1-cp39-cp39-manylinux1_x86_64.whl (769 kB)
Collecting typing-extensions>=3.7.4
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting certifi
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting idna
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Installing collected packages: sniffio, rfc3986, idna, h11, typing-extensions, typed-ast, mypy-extensions, httpcore, certifi, mypy, httpx
Successfully installed certifi-2020.12.5 h11-0.11.0 httpcore-0.12.2 httpx-0.16.1 idna-2.10 mypy-0.790 mypy-extensions-0.4.3 rfc3986-1.4.0 sniffio-1.2.0 typed-ast-1.4.1 typing-extensions-3.7.4.3
```

```bash
$ venv/bin/pip freeze
certifi==2020.12.5
h11==0.11.0
httpcore==0.12.2
httpx==0.16.1
idna==2.10
mypy==0.790
mypy-extensions==0.4.3
rfc3986==1.4.0
sniffio==1.2.0
typed-ast==1.4.1
typing-extensions==3.7.4.3
```

```bash
$ venv/bin/mypy x.py
x.py:7: error: Argument "app" to "AsyncClient" has incompatible type "Optional[Callable[..., Any]]"; expected "Callable[..., Any]"
x.py:10: error: Argument "app" to "AsyncClient" has incompatible type "None"; expected "Callable[..., Any]"
Found 2 errors in 1 file (checked 1 source file)
```

</details>

I think the basic question is does httpx want to 'support' `no_implicit_optional = True` or to leverage the implicit optional feature and expect users to configure their mypy runs accordingly?  I can understand either choice though I personally would tend towards libraries following more strict typing restrictions so as to directly enable more use cases.

Aside, this makes me wonder if Mypy should (or does) allow libraries to set their own settings for user runs.  I'll go check on that as well now.  Also, perhaps I should specify my extra-strict settings in a `[mypy-qtrio.*]` section instead of doing so globally.  Various options, but that just reinforces that I could be ok with httpx taking either stance listed above.

Thanks for your consideration.

**Comment by tomchristie** [comment]
Our linting settings are currently to allow implicit optionals, yup.
I *think* that's mypy's default. (?)

**Comment by altendky** [comment]
That's correct afaik.  Ok, I'll take this as a 'yes, we want to leave the code as is with implicit optionality'.  Thanks for your time.  Maybe I'll try to poke at Mypy about the idea of being able to use a library's own configuration when checking an application that uses it.  This seems like a bit of a hole in the system.

**Comment by dctr** [comment]
Hello everyone, 

Sorry for being late to the discussion ;-) I just opened [this discussion](https://github.com/encode/httpx/discussions/1747) and was pointed to this issue.

In the linked discussion I made a case for, as mentioned above, an issue when using mypy's `no_implicit_optional = True`. I would highly appreciate if you could reconsider addressing this, as it would greatly help teams like mine that want to implement stricter type checking.

Cheers
