### ISSUE TITLE
Document solution for startup/shutdown of ASGI apps

### ISSUE THREAD

**Issue by florimondmanca** [encode/httpx#1441]
Prompted by https://github.com/encode/httpx/issues/350#issuecomment-752639213

As discussed in #350, HTTPX doesn't provide a solution for managing the startup/shutdown lifecycle of an ASGI app. That is left to user code and not planned to change soon.

However we could/should consider pointing users at [`asgi-lifespan`](https://pypi.org/project/asgi-lifespan/) in our docs so that we're pointing at a full solution.

https://www.python-httpx.org/async/#calling-into-python-web-apps

**Comment by tomchristie** [comment]
Seems reasonable yup. I don't think we'll ever want HTTPX to deal with ASGI startup/shutdown, seems out of scope.
Also, at some point it'd make sense to update Starlette so that it's test client (which *does* handle startup/shutdown) uses HTTPX.
