### ISSUE TITLE
Using specific DNS servers

### ISSUE THREAD

**Issue by florimondmanca** [encode/httpx#1444]
Dumping this discussion from Gitter as it might be useful as a future reference.

AmericanY 17:57
Hello, is it possible to use specific DNS with HTTPX ?

Florimond Manca 19:32
@AmericanY Not sure what you mean there... How would you solve that use case with another HTTP client? Isn’t DNS configured at the system level?

AmericanY 19:38
@florimondmanca instead of changing the system DNS itself. is it possible to define the DNS for the script to use it during running. which means I just need it only during running of the script and to not keep changing the default dns of system

Florimond Manca 19:40
Currently I don’t think we support that, nope. I’m not even sure how you would do that with plain Python sockets, which is why I was asking if other clients support that functionality

parity3 19:47
re: using specific DNS, curl / pycurl seems to support it: https://curl.se/libcurl/c/curl_easy_setopt.html via CURLOPT_DNS_SERVERS

Florimond Manca 23:47
@AmericanY Right now I think your best chance might be to build a custom transport that uses dnspython.
I found this SO thread that mentions dnspython: https://stackoverflow.com/questions/34793061/socket-resolve-dns-with-specific-dns-server/34793361
The custom transport would use the host part of the URL to perform the DNS query and get and IP back, then use it to call the usual transport

Florimond Manca 23:53
Something like this... :)

```python
import dns
import httpx
import httpcore

class DNSTransport(httpcore.SyncHTTPTransport):
    def __init__(self, transport, res):
        self.transport = transport
        self.res = res

    def request(self, method, url, headers, stream, ext):
        scheme, host, port, path = url
        ip = self.res.query(host.decode()).encode()
        url = (scheme, host, port, path)
        return self.transport.request(method, url, headers, stream, ext)

transport = httpcore.SyncConnectionPool(...)  # Follow example in custom transports docs

res = dns.resolver.Resolver()
res.nameservers = ...
transport = DNSTransport(transport, res)

with httpx.Client(transport=transport) as client:
    ...
```

**Comment by kkm** [comment]
@florimondmanca 
I'm looking for the examples of current version 0.23.3. it has changed a lot with dnstransport.
Thanks.

**Comment by seidnerj** [comment]
@kkm, below I included my take on this, but note that SSL verification becomes a problem since the underlaying libraries try and verify the certificate for an IP address (and hence fail). Also, you have to initialize many parameters through the Transport class instead of the Client class otherwise they might not have any effect.

```
import dns.asyncresolver
import httpx
import trio


class SpecificDNSAsyncHTTPTransport(httpx.AsyncHTTPTransport):

    def __init__(self, dns_server_ip=None, **kwargs) -> None:
        super().__init__(**kwargs)
        self._dns_server_ip = dns_server_ip

    async def _patch_request(self, request):
        answer = await dns.asyncresolver.resolve_at(self._dns_server_ip, request.url.raw_host.decode(), 'A')
        ip_address = next(answer.__iter__()).address
        new_uri = request.url._uri_reference.copy_with(host=ip_address)
        request.url._uri_reference = new_uri

    async def handle_async_request(self,
                                   request: httpx.Request) -> httpx.Response:
        if self._dns_server_ip is not None:
            await self._patch_request(request)

        return await super().handle_async_request(request)


async def main():

    transport = SpecificDNSAsyncHTTPTransport(dns_server_ip='1.1.1.1', verify=False, proxy=httpx.Proxy(url='http://localhost:8888'))
    session = httpx.AsyncClient(transport=transport)
    res = await session.get('https://www.google.com/')
    print(res.content.decode())


if __name__ == "__main__":
    trio.run(main)
```

**Comment by T-256** [comment]
FYI https://github.com/encode/httpx/discussions/2698
