### ISSUE TITLE
[Proposal] Single line call with async client

### ISSUE THREAD

**Issue by lephuongbg** [encode/httpx#1446]
### Checklist

- [x] There are no similar issues or pull requests for this yet.
- [ ] I discussed this idea on the [community chat](https://gitter.im/encode/community) and feedback is positive.

### Is your feature related to a problem? Please describe.

I would like to reduce the amount of (boilerplate) code to send simple requests with asynchronous client.

## Describe the solution you would like.

A single line call should be enough to open connection, send the request, then close the connection.

```python
async def any_function():
    response = await httpx.aget('https://example.com')
    # or
    response = await httpx.a.get('https://example.com')
    # NOTE: welcome suggestion on specific API design
```

instead of 2 lines:

```python
async def any_function():
    async with httpx.AsyncClient() as client:
        response = await client.get('https://example.com')
```

**Comment by tomchristie** [comment]
I get why it might look like a neat idea on the surface, but I'm not convinced in practise.

Given that async is about achieving high concurrency, it's a bit hard to think up good real-world examples where using single-shot calls like this are a good design decision vs. having a properly setup client.

**Comment by jedihugo** [comment]
I believe this line here has configuration parameters such as timeout, keep_connection, etc., in which, in our project we specify a lot, so this line has its usefulness for sure.
`async with httpx.AsyncClient() as client:`

**Comment by lephuongbg** [comment]
> using single-shot calls like this are a good design decision vs. having a properly setup client.

@tomchristie It is not, and it is not meant to be. It is the same with comparing calling `httpx.get()` vs calling `with httpx.Client() as client: client.get()`: one is for convenient where you don't need anything fancy, just call an URL then get the result; and the other is for connection pooling, streaming, client reuse, etc.

The implementation should also be simple like this, you can see that the proposed interface is just a syntactic sugar on top of the two-line version:

```python
class AsyncClient:
    @classmethod
    async def aget(cls, url: str, ...):
        async with cls() as client:
            return await client.get(url, ...)
```

> I believe this line here has configuration parameters such as timeout, keep_connection, etc., in which, in our project we specify a lot, so this line has its usefulness for sure

@jedihugo In that case you should need multi-line version, for obvious reason that keep_connection means you would want to reuse the client. But if you only need to set timeout, headers then single-line should be enough.

**Comment by tomchristie** [comment]
> one is for convenient where you don't need anything fancy, just call an URL then get the result; and the other is for connection pooling, streaming, client reuse, etc.

Sure. My point is that async *in any case* is more of a precision tool.

If you don't "need anything fancy" then great we've got single call (thread blocking) helper functions right there for you. If you're getting fancy and writing highly concurrent code, then we'll also require you to be ever-so-slightly more precise about the scope of your resources.

Pitch this a different way around - if we did provide single-call async functions then we'd be given our users a really easy way to write what might look on the surface as perfectly reasonable, highly concurrent codebases, while *actually not using connection pooling, or resource limits* that using a client would provide.

**Comment by lephuongbg** [comment]
I understand your point that users might abuse this syntax that could causes lot of unnecessary connections. From where I see, that is a more of a matter of education and best practices. There are already many guides and blog posts that encourage users to make one client session when they're are doing many requests to a single server in short amount of times. 

In our project, we have a lot of separate functions scattered throughout many modules, each only does one call to an URL. Writing two-lines or the proposed one-line version in this situation makes no difference performance-wise since we can't share the client. Our calls are also occasional so keeping connection wouldn't provide much benefits for us.

With one-line, we can still take advantage of the non-blocking connection, while being able to write less, or need to remember the syntax less.

**Comment by florimondmanca** [comment]
@lephuongbg Thanks for raising this up for discussion.

I'd stand with Tom's analysis on this one. I'd also add that as we're trying to narrow down on a 1.0 release _someday_, it's in the project's best interest to keep any new syntax or full additions of code / API to an absolute minimum.

We could reassess this post-1.0, but for now if your use case is specific enough that it requires async but doesn't warrant reusing connections, I'd suggest just going along with some custom helper functions (a single `arequest(<method>, <url>, ...)` should do the trick) on your end.

Thank you!
