### ISSUE TITLE
delete method doesn't support the json keyword argument

### ISSUE THREAD

**Issue by Waffles32** [encode/httpx#1448]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

`json` keyword is not supported with the DELETE HTTP method

### To reproduce

python3 -c 'import httpx; httpx.delete("", json=1)'

### Expected behavior

HTTP DELETE request be made with a JSON body and appropriate headers (like a POST request via the `post` method)

### Actual behavior

A TypeError exception is thrown

### Debugging material

`Python 3.8.6 (default, Dec  1 2020, 10:02:28) 
[Clang 12.0.0 (clang-1200.0.32.27)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import httpx
>>> httpx.delete("", json=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: delete() got an unexpected keyword argument 'json'`

### Environment

- OS: macOS
- Python version: 3.8.6
- HTTPX version: 0.16.1
- Async environment: asyncio
- HTTP proxy: no
- Custom certificates: no

### Additional context

...

**Comment by florimondmanca** [comment]
Hey,

Nope, that's expected, and documented in our Requests compatibility docs as well, see: https://www.python-httpx.org/compatibility/#request-body-on-http-methods

Thanks
