### ISSUE TITLE
Handle 408-response connection closes.

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#146]
PR #145 ensures that we're checking for disconnections when we reacquire connections, by using the `StreamReader.at_eof` interface.

However @njsmith points out, that's not always quite sufficient. https://github.com/encode/httpx/pull/143#issuecomment-515202982

> There's StreamReader.at_eof, but that will fail if the HTTP server is polite and sends a 408 Request Timeout before it closes the connection. I think the best you can do is:
>
> ```python
> def asyncio_stream_is_readable(stream):
>      return stream._buffer or stream._eof
> ```
>
> or else giving up on the Stream API and using protocols/transports directly.

Either of those would be do-able.

How common is 408 usage in the wild - are there example URLs we can confirm against?

Also worth noting that there's also always going to be a race network condition where we start getting a 408 response that was about to be sent, just as we're in the process of sending out a new request.

**Comment by Sheshtawy** [comment]
I'd love to help with this if no one is

**Comment by tomchristie** [comment]
Closing this in favour of #34.

For robustness we ought to be closing keep-alive connections after a timeout period.

That doesn't prevent 408 cases from occuring entirely, but it would substantially mitigate against it, and is the sensible case for us to prioritize here.
