### ISSUE TITLE
Drop `Origin` class.

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#147]
We currently have an `Origin` class that we use for eg. being able to lookup connections-by-origin from the connection pool. (With hostname and scheme normalization.)

We don't *really* need to do this. There's no reason we can't just use the existing `URL` model for this purpose, and only use URLs that just include the host/scheme portions.

* Change the `URL.origin` property to instead return a `URL` instance, which only includes the origin portions of info.
* Remove the `Origin` class.
* Change `origin: Origin` type annotations anywhere to `origin: URL` annotations.

Having less API surface area is *a good thing*™️.

**Comment by sethmlarson** [comment]
Aren't URLs and URL origins logically different things though? I'm having trouble seeing the positive vs. negative of this change.

**Comment by sethmlarson** [comment]
Going to close this in favor of #165
