### ISSUE TITLE
httpx depends on h2 (hyper), which is unmaintained

### ISSUE THREAD

**Issue by Apteryks** [encode/httpx#1476]
## Describe the bug

Hello; that's perhaps a misunderstanding on my part, but FWIU this project absorbed hyper (h2) and had it deprecated.  Yet httpx's setup.py still references to h2 (version 3!) as an extra dependency (https://github.com/encode/httpx/blob/0f280af8b170ed5cc48c12a894f71a8b5762f748/setup.py#L65), which in the best case is a one year old release of an now unmaintained library.

What is is useful for? Can it simply be removed? What about hyper compatibility feature with requests (HTTP20Adapter) ? Is there something like this in HTTPX?  Thank you, and sorry for all the questions :-).

**Comment by Apteryks** [comment]
Ah, I think I now see the subtlety: hyper (the client) is abandoned, but hyper-h2 (https://github.com/python-hyper/hyper-h2), which is a "pure-Python HTTP/2 protocol stack", is not.

Perhaps it'd be clearer if h2 was brought under this project umbrella.  As it stands, it inherits the hyper branding, which can mislead us to the dead repo (client).

**Comment by florimondmanca** [comment]
@Apteryks I'll conver this to a discussion, if that's OK. :-)
