### ISSUE TITLE
Update 1.0 release

### ISSUE THREAD

**Issue by AstraLuma** [encode/httpx#1479]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug
On the front page, it still says "A 1.0 release is expected to be issued sometime in late 2020."

### To reproduce

Navigate to https://www.python-httpx.org/

### Expected behavior

A 1.0 ETA in the future.

### Actual behavior

A 1.0 ETA in the past.

### Debugging material

(none)

### Environment

- OS: All
- Python version: All
- HTTPX version: All
- Async environment: Any
- HTTP proxy: None
- Custom certificates: None

### Additional context

I don't mean to be a dick about this. I just mean to gently remind you that this is still on the front page.

**Comment by johtso** [comment]
This was already updated, just hasn't been included in a release yet. https://github.com/encode/httpx/pull/1445

**Comment by tomchristie** [comment]
Sure, the docs will update on our next release.

**Comment by florimondmanca** [comment]
> already updated

Ah, I knew I had already seen this brought up! 😄
