### ISSUE TITLE
head request behaviour

### ISSUE THREAD

**Issue by bugficks** [encode/httpx#1483]
httpx                    0.16.1

_httpx_ head() request behaves differently compared to _requests_ head() implementation.
for _httpx_ **allow_redirects** defaults to **true**, for _requests_ it defaults to [**false**](https://github.com/psf/requests/blob/master/requests/sessions.py#L576)

**Comment by florimondmanca** [comment]
@bugficks Hi,

I believe this is a deliberate choice? I think there is a comment about this in the code, although I'm not sure it's for HEAD or OPTIONS.

If this is something we're missing in the Requests Compatibility guide, then sure, happy that we add it. :-)

**Comment by bugficks** [comment]
@florimondmanca

so it seems. I have just tried urllib3 and they're following redirects as well. so really _requests_ behaves bad :)

Requests Compatibility seems like a good place to add in case someone else stumbles on this.
Thanks

**Comment by florimondmanca** [comment]
@bugficks Okay. :-) If you'd like to send a patch with some additional words in the compatibility guide, please feel free to.

**Comment by tomchristie** [comment]
Closed via #1520
