### ISSUE TITLE
Set Headers like Cookies in Client session for all requests

### ISSUE THREAD

**Issue by StephenBrown2** [encode/httpx#149]
Assuming one can use `Client`/`AsyncClient` as a drop-in replacement for `requests.Session`, I would like to be able to set headers (and cookies) to be sent for each request, for example for token-based authentication.

With `requests`, I can do:
```python
header_dict = {"X-Auth-Token": "FooBarBazToken"}
session = requests.Session()
session.headers.update(header_dict)
```

`cookies` can already be set on the `httpx.Client`. I would like to be able to also do that with `headers`:
```python
>>> headers = Headers({"X-Auth-Token": "FooBarBazToken", "User-Agent": "python-myclient/0.2.1"})
>>> session = Client(base_url="https://httpbin.org", headers=headers)

>>> get_headers = session.get("/headers")

>>> get_headers.json()
{'headers': {'Accept': '*/*',
  'Accept-Encoding': 'gzip, deflate',
  'Cookie': 'MyCookie=MyValue',
  'Host': 'httpbin.org',
  'User-Agent': 'python-myclient/0.2.1',
  'X-Auth-Token': 'FooBarBazToken'}}
```

**Comment by tomchristie** [comment]
Indeed, yup! 👍
We've got a `.cookies` interface on there already, but we don't yet have a `.headers` interface.

**Comment by StephenBrown2** [comment]
So there is a `cookies=` option! I missed it because I was searching so hard for `headers`. I'll update the OP.
