### ISSUE TITLE
Incompatible with httpcore 0.12.0

### ISSUE THREAD

**Issue by UrbiJr** [encode/httpx#1499]
### Describe the bug

I get `TypeError: __init__() got an unexpected keyword argument 'retries'` after latest update when trying to create an instance through `httpx.Client()`. 

Traceback:
```
>>> client = httpx.Client()
Exception ignored in: <function Client.__del__ at 0x0000029540F5C948>
Traceback (most recent call last):
  File "C:\Users\UrbiJ\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\_client.py", line 1130, in __del__
    self.close()
  File "C:\Users\UrbiJ\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\_client.py", line 1102, in close
    self._transport.close()
AttributeError: 'Client' object has no attribute '_transport'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\UrbiJ\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\_client.py", line 608, in __init__
    trust_env=trust_env,
  File "C:\Users\UrbiJ\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\_client.py", line 649, in _init_transport
    verify=verify, cert=cert, http2=http2, limits=limits, trust_env=trust_env
  File "C:\Users\UrbiJ\AppData\Local\Programs\Python\Python37\lib\site-packages\httpx\_transports\default.py", line 67, in __init__
    backend=backend,
TypeError: __init__() got an unexpected keyword argument 'retries'
```
### To reproduce
```
>>> import httpx
>>> s = httpx.Client()
```

### Environment

- OS: Windows
- Python version: 3.7.9
- HTTPX version: 0.17.0

**Comment by johtso** [comment]
What's your httpcore version?

I'm guessing that somehow you updated httpx without the httpcore dependency being updated.

**Comment by UrbiJr** [comment]
yeah indeed that was the problem ! thank you

**Comment by johtso** [comment]
One of the downsides of the separate libraries approach. Out of curiosity, how did you manage to update `httpx` without the dependency updating?

**Comment by UrbiJr** [comment]
Tbh, I'm Not sure if I updated `httpx` without the dependency being updated, *or* if I accidentally installed a previous version of `httpcore` later... It could also be second option, in that case I must have forgotten to activate the `venv` of some projects

**Comment by johtso** [comment]
Ah, that would make sense!

**Comment by Colin-b** [comment]
No that's not on your side, this is a bug in `httpx==17.0.0`, resolved by #1495 , not yet released on pypi.

**Comment by johtso** [comment]
Whoops! Didn't realise that wasn't in `17.0.0`..

**Comment by florimondmanca** [comment]
Yup, in 0.17.0 you should have bumped the minimum HTTPCore version to make sure 0.17.0 shipped with versions that has the `retries` option. :)

**Comment by tomchristie** [comment]
My post-match review on this is that we ought to have had an httpcore 0.13.0 release, prior to httpx 0.17.0.

If we're pinning to `>=` httpcore minor version numbers, then we've got something (slightly) wrong.

Not a big deal, just worth mentioning.

*(At this point tho' I think we just want to have a minor httpx release that pins to httpcore >= 0.12.1)*

**Comment by tomchristie** [comment]
Slightly related discussion... https://github.com/encode/httpx/discussions/1504
