### ISSUE TITLE
CertTypes `keyfile` and `password` should be Optional types.

### ISSUE THREAD

**Issue by decaz** [encode/httpx#1502]
`SSLContext.load_cert_chain` can take `None` as arguments values ([docs](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.load_cert_chain)) so I guess this:
https://github.com/encode/httpx/blob/c09e61d50c8f169187cada6dbf14b89c7763c63f/httpx/_types.py#L54
should be rewritten as follows:
```python
CertTypes = Union[str, Tuple[str, Optional[str]], Tuple[str, Optional[str], Optional[str]]] 
```

**Comment by florimondmanca** [comment]
Hi,

Sounds legit, happy to review PRs towards that. :)

**Comment by johtso** [comment]
Feel like a type definition like that would be more readable broken over multiple lines, so many square brackets!
