### ISSUE TITLE
Ignore `None` Headers

### ISSUE THREAD

**Issue by StephenBrown2** [encode/httpx#152]
I wanted to set an optional Header, so sometimes the value is `None`. What I expected was for the header to be omitted from the list when the value is `None`. Instead, I got:
```
AttributeError: 'NoneType' object has no attribute 'encode'
```
`if v is not None` could be added [here](https://github.com/encode/httpx/blob/master/httpx/models.py#L325) and [here](https://github.com/encode/httpx/blob/master/httpx/models.py#L330) to filter the headers on instantiation. [`__setitem__`](https://github.com/encode/httpx/blob/master/httpx/models.py#L428) should probably also be updated to `del` the item if the passed `value` is `None`.

**Comment by sethmlarson** [comment]
What is the use-case for this that can't be accomplished via `headers.pop("name", None)` to remove headers if they exist?

Do any other HTTP libraries have this behavior? urllib3 I know doesn't.

**Comment by StephenBrown2** [comment]
I suppose I could filter the dict before passing it to Headers, but my use was like:
```py
def function(param_one: str, optional_header: Optional[str] = None)
    headers = Headers(
        {
            "X-Auth": param_one,
            "X-Auth-Token": optional_header
        }
    )
    httpx.get(url, headers=headers)
```
Instead I _could_ do:
```py
def function(param_one: str, optional_header: Optional[str] = None)
    header_dict = {
        "X-Auth": param_one,
        "X-Auth-Token": optional_header
    }
    headers = Headers(
        {k: v for k, v in header_dict if v is not None}
    )
    httpx.get(url, headers=headers)
```

but that doesn't seem as clean to me. I hadn't seen it elsewhere, it was just surprising behavior when I tried it.

**Comment by sethmlarson** [comment]
What about?

```python
def function(..., optional_header: Optional[str] = None):
    headers = {
        ...
    }
    if optional_header is not None:
        headers["X-Auth-Token"] = optional_header
    httpx.get(url, headers=headers)
```

?

**Comment by StephenBrown2** [comment]
Yeah, there are several ways to do it. I'd probably make a utils function for myself [like](https://stackoverflow.com/a/54817412):

```py
from collections.abc import Mapping

def filter_none(d):
	""" Generic filter function to recursively remove keys with values of `None`.
	Ref: https://stackoverflow.com/a/54817412
	"""
    if isinstance(d, Mapping):
        return {k: filter_none(v) for k, v in d.items() if v is not None}
    else:
        return d
```

and then:

```py
from utils import filter_none

def function(..., optional_header: Optional[str] = None):
    headers = {
        ...
    }
    httpx.get(url, headers=filter_none(headers))
```

**Comment by sethmlarson** [comment]
So I'll close this issue, I think we'll require values within the `headers` parameter.

**Comment by StephenBrown2** [comment]
Fair enough

**Comment by scottzach1** [comment]
> Do any other HTTP libraries have this behavior? urllib3 I know doesn't.

This is the behavior for requests library, and I think is a very convenient default behavior.

For a real-world scenario, I have a `httpx.AsyncClient` within a SDK I am developing. Within the default headers I specify `headers={"Content-Type": "aplication/json"}` as this is required for ~95% of the requests. Unfortunately, there is one particular endpoint that uses `multipart/form-data`. This has caused issues for me as the generated boundaries are only included in the headers if the "Content-Type" unset.

```python
import httpx

client = httpx.Client(
    headers={
        "Accept": "application/json",
        "Content-Type": "application/json",
    }
)

client.post(
    "/some/endpoint/",
    files=dict(operation=("copy", None)),
    headers={"Content-Type": ???},  # cannot unset header / does not work with None or multipart/form-data
)
```

This appears to be the case due to the implementation of how headers are generated in `MultipartStream` and then merged into the outgoing request headers. As I am unable to unset the `Content-Type` for the individual request the generated header containing the boundary is not included in the outgoing request.

https://github.com/encode/httpx/blob/66225539796d819b5114ead2fd5e4d61865ab708/httpx/_multipart.py#L208

I hope this makes sense? I am happy to go into more detail or create a new issue if desired. :)

**Comment by tomchristie** [comment]
Heya @scottzach1, do you need to be setting `"Content-Type"` on the client?...

```python
import httpx

client = httpx.Client(
    headers={
        "Accept": "application/json",
    }
)

# Uses multipart/form-data
client.post(
    "/some/endpoint/",
    files=dict(operation=("copy", None)),
)

# Uses application/json
client.post(
    "/some/endpoint/",
    json=...
)
```

**Comment by scottzach1** [comment]
My apologies @tomchristie! I didn't realize the `json=` keyword argument automatically sets the `Content-Type` header. In retrospect, it  makes perfect sense. Thanks for the clarification!

**Comment by tomchristie** [comment]
Good to know that's resolved the issue. You have tapped into an awkward spot tho...
Some headers don't make sense to specify on the client, and we're not documenting that anywhere.

**Comment by technillogue** [comment]
Hi, I'm also interested in this. I described my use-case here: https://github.com/encode/httpx/discussions/3037#discussioncomment-14469701
