### ISSUE TITLE
httpx.RemoteProtocolError: illegal header line: bytearray(b'get-ban-to-cache-result/forum.php: userdata not support')

### ISSUE THREAD

**Issue by zhs509** [encode/httpx#1561]
> import httpx
from fake_useragent import UserAgent
headers = {'user-agent':UserAgent().random}
url = 'https://club.huawei.com/thread-26829078-1-1.html'
resp = httpx.get(url=url,headers=headers)
print(resp.text)

environment：win10 x64，Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 22:39:24) [MSC v.1916 32 bit (Intel)] on win32

using httpx return httpx.RemoteProtocolError，while using requests return ok.

![20210408150309](https://user-images.githubusercontent.com/10372168/113983338-61da5f80-987c-11eb-8d74-6abaaa593471.png)

**Comment by tomchristie** [comment]
Duplicate of #1363
