### ISSUE TITLE
auth issue!

### ISSUE THREAD

**Issue by AmericanY** [encode/httpx#1567]
```python
import httpx
auth = ("Authorization", "11")
r = httpx.get('http://httpbin.org', auth=auth)
print(r.request.headers)
```

Output:

```
Headers({'host': 'httpbin.org', 'accept': '*/*', 'accept-encoding': 'gzip, deflate', 'connection': 'keep-alive', 'user-agent': 'python-httpx/0.17.1', 'authorization': '[secure]'})
```

**Comment by florimondmanca** [comment]
@AmericanY Hello, please be mindful that we'd like usage questions like these to be started as Discussions. You'd also need to be more specific if you'd like someone to put in some time to help you out.

Thanks.

**Comment by rjy7wb** [comment]
how do you prevent this from happening? enable the auth headers to be shown

**Comment by johtso** [comment]
> how do you prevent this from happening? enable the auth headers to be shown

I don't think the obfuscation behaviour of the `__repr__` is configurable. I guess you could just convert it to a dictionary before printing? Or pluck out and print the relevant value..

**Comment by tomchristie** [comment]
Worth reflecting on this perhaps. Do we want this behaviour?

**Comment by johtso** [comment]
@tomchristie I'm struggling to see a use case. I guess the ability to expand the list of sensitive fields might make sense. But I don't see a situation where you need a neat API to bypass redaction. If the main purpose is to allow adding more sensitive fields, then I guess it would come free? Do we have any other places where we allow some kind of global configuration? I'm guessing it would make sense as a global configuration..

**Comment by tomchristie** [comment]
Oh I didn't point out clearly my intent there.

My meaning was...

> Worth reflecting on this **\<obfuscation\>** perhaps. Do we want this behaviour **\<of hiding the auth header\>**?

Eg. Does `requests` do anything similar here? How about curl's terminal output when using a basic auth username and password? Are we confident we've made the right call wrt. usability in our `repr` implementation here?

**Comment by johtso** [comment]
After a bit of poking around, `requests` doesn't seem to do anything related to redaction of sensitive data. Also tried verbose output of basic auth with `curl`, and again, nothing redacted.

So it sounds like we're doing something different here.

**Comment by tomchristie** [comment]
Personally I think I'd be pretty okay with us not redacting this field in the `__repr__`. Feels like more of a hindrance than a benefit, no?

**Comment by johtso** [comment]
Could probably justify removing it in the name of keeping things as simple as possible. Although having a default behaviour that might help avoid someone shooting themselves in the foot is a nice idea.

It does kind of make sense to treat `__repr__` as something that is potentially publishing data to untrusted environments. An obvious case is logging exceptions and their context variables. Services like sentry.io have server side scrubbing rules. Ideally you don't want to be sending the sensitive data in the first place and you do some sanitisation before sending. I actually assumed that this would be more well provided for out of the box, but taking a look at the python sentry SDK, it doesn't provide any data scrubbing functionality.

I guess the problem with trying to solve the issue of leaking sensitive data when logging exception context _within_ `httpx`, is that it doesn't protect the other places in the code where that sensitive information is referenced.

What it does help with is the `print(my_headers)` case.

I'm on the fence.

A. Something is better than nothing. Avoid exposing things that we know are probably sensitive.
B. Nobody else helps the user with this, so there is no expectation of this functionality. Also if someone wants to avoid exposing/logging sensitive data, this isn't really going to cut it.

**Comment by StephenBrown2** [comment]
Not to put forth the "That's how it's always been" argument, but... That's how it's been for two years at least:
Initial PR: https://github.com/encode/httpx/pull/222
Initial Issue: https://github.com/encode/httpx/issues/220

If nobody else does it, then maybe we're being too helpful with it? But it hasn't come up as an issue before this, and there are ways around it, which I would expect to use if wanting to debug auth anyways:
```pycon
In [1]: import httpx
   ...: auth = ("Authorization", "11")
   ...: r = httpx.get('http://httpbin.org', auth=auth)
   ...: print(r.request.headers)
Headers({'host': 'httpbin.org', 'accept': '*/*', 'accept-encoding': 'gzip, deflate', 'connection': 'keep-alive', 'user-agent': 'python-httpx/0.16.1', 'authorization': '[secure]'})

In [2]: print(r.request.headers['Authorization'])
Basic QXV0aG9yaXphdGlvbjoxMQ==
```
