### ISSUE TITLE
Issue a warning or exception when a client is closed while requests remain in-flight.

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#1614]
Raised via: https://github.com/encode/httpx/issues/1478#issuecomment-828955977

If developer erroneously closes a client while a request/response is still in-flight, then there's no warning that this has occurred, and the seen exception is as-if the server had disconnected early.

At a minimum we'd really want to *at least* issue a warning when this occurs. Ideally we also want the response to raise a clear exception that properly indicates the underlying cause of the error.

**Comment by tomchristie** [comment]
The user-code error that caused this would also be resolved if we added some `RuntimeError` cases around weird client state transitions on `__enter__`/`__exit__`/`__aenter__`/`__aexit__`.

So:

* On `__enter__`/`__aenter__` raise a `RuntimeError` if the client was not in an `UNOPENED` state.
* On `__exit__`/`__aexit__` raise a `RuntimeError` if the client was not in a `CLOSED` state.

```python
    def __enter__(self: T) -> T:
        if self._state == ClientState.OPENED:
            # Most likely this indicates that a client is being incorrectly used in multiple with blocks.
            raise RuntimeError("Client instances should not be repeatedly opened.")
        if self._state == ClientState.CLOSED:
            # Strictly speaking we *could* allow client instances to be closed and re-opened
            # within different `with` blocks, but it's not a great idea as it can easily lead to
            # invalid/unexpected states.
            raise RuntimeError("Client instances should not be re-opened once closed.")

        self._state = ClientState.OPENED
        ...
```

```python
    def __exit__(self: T) -> T:
        if self._state == ClientState.CLOSED:
            # This should have already raised a `RuntimeError` in `__enter__`, because it
            # indicates that the clients had `__enter__`/`__exit__` called multiple times.
            raise RuntimeError("Client instances cannot be repeatedly closed.")
        if self._state == ClientState.UNOPENED:
            # This shouldn't ever occur.
            # Would indicate `__exit__` being called without a prior call to `__enter__` having occurred.
            raise RuntimeError("Client instances cannot be closed if they have not been opened.")

        self._state = ClientState.OPENED
        ...
```

**Comment by tomchristie** [comment]
Somewhat related to #1615

**Comment by tomchristie** [comment]
Interesting spin off thought here. We *could* indicate some basic information on the client `__repr__` here.

```pycon
>>> client
<httpx.Client (4 requests sent, 1 request in-flight)>
```

**Comment by ahopkins** [comment]
That's a really helpful idea. Irrespective of the exception, that is really nice information.

**Comment by default-303** [comment]
@ahopkins can i have this issue ?

**Comment by tomchristie** [comment]
I'm kinda minded for us to punt on this. We can re-review if there's feedback indicating that it'd be helpful, but let's try to base this more on user experience than "we think this might be a good idea".
