### ISSUE TITLE
Stricter enforcement around client scoping.

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#1615]
Raised via: https://github.com/encode/httpx/issues/1478#issuecomment-828955977

There are really two sensible ways to use a client instance wrt. scoping the lifetime...

Implicitly opened clients...

```python
client = httpx.Client()
...
client.close()  # Optional in the sync case. Issues a warning if omitted in the async case.
```

Explicitly opened clients...

```python
with httpx.Client() as client:
    ...
```

However we currently don't guard against unexpected usages, which would likely indicate a user error, and could lead to unexpected behaviours.

* Using a client within a `with` scope multiple times in parallel.
* Using a client making plain implicitly opening requests, and *then* opening it within a `with` scope.
* Using a client within a `with` scope, but calling an explicit `close()`.
* Using a client within a `with` scope multiple times sequentially. We could *potentially* allow this? Possibly a footgun? Not sure?

We could guard against these cases and more strictly enforce correct client scoping.

For instance, the user-code error that caused https://github.com/encode/httpx/issues/1478#issuecomment-828955977 would be resolved if we added some `RuntimeError` cases around weird client state transitions on `__enter__`/`__exit__`/`__aenter__`/`__aexit__`.

So:

* On `__enter__`/`__aenter__` raise a `RuntimeError` if the client was not in an `UNOPENED` state.
* On `__exit__`/`__aexit__` raise a `RuntimeError` if the client was not in a `CLOSED` state.

**Comment by tomchristie** [comment]
Somewhat related to #1614

**Comment by jkklapp** [comment]
@tomchristie I'd like to help out with this one. Can you assign the issue to me?

**Comment by tomchristie** [comment]
Not really using assignments as workflow at the moment. (We could possibly reconsider that with discussion.) You're very welcome to pitch out a pull request for it tho.

**Comment by default-303** [comment]
can i have this issue if no one is working on it ?
