### ISSUE TITLE
How to configure TLS beyond client certificate and CA root certs?

### ISSUE THREAD

**Issue by VeNoMouS** [encode/httpx#166]
Typically in requests you can use a __HTTPAdapter__ to hijack and set the SSL context and define what ciphers to use, how does one go about doing the same in __httpx__?

**Comment by sethmlarson** [comment]
I was thinking about this, maybe we need to either provide a better interface or a recipe for how to do this. There are plenty of valid use-cases for configuring beyond our defaults and we should expose that in the way that forces us to do the least work possible.

**Comment by sethmlarson** [comment]
My proposed solution was the allow passing an `ssl.SSLContext` into `verify=...`. It would get transformed into an `SSLConfig` object and then still call `load_client_cert()` if `cert=...` is called with it?

**Comment by VeNoMouS** [comment]
I think your biggest hurdle doing that is around here https://github.com/encode/httpx/blob/master/httpx/dispatch/connection.py#L64-L78 due to your logic and how the logic in config is constructed

**Comment by VeNoMouS** [comment]
Is there anyway to access HTTPConnection i mean you could populate __HTTPConnection.ssl.ssl_context__ with a context

**Comment by VeNoMouS** [comment]
But that creates issues in https://github.com/encode/httpx/blob/master/httpx/config.py#L68-L105 where it just blindly creates a new context

**Comment by tomchristie** [comment]
> My proposed solution was the allow passing an ssl.SSLContext into verify=.... It would get transformed into an SSLConfig object and then still call load_client_cert() if cert=... is called with it?

Yeah either overloading `verify=...`, or else adding a new `ssl=...` argument.

I think I probably quite like your suggestion here @sethmlarson.

**Comment by VeNoMouS** [comment]
I like the `ssl` argument suggestion personally, I am really excited for this project :) and thanks for taking the time to look into this
