### ISSUE TITLE
Add Python 3.10 to the build matrix

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#1678]
Prompted by #1670

At the time of writing this, Python 3.9 is the current most up to date release... https://www.python.org/downloads/
But the 3.10 beta is available, and we should probably start testing against that.

The 3.10 release schedule: https://www.python.org/dev/peps/pep-0619/

**Comment by Kludex** [comment]
Python 3.10.0-beta.2 is the latest one by this date.

You can check the last releases here: https://github.com/actions/python-versions
