### ISSUE TITLE
Create a Client.build_request() method

### ISSUE THREAD

**Issue by sethmlarson** [encode/httpx#174]
See: https://github.com/encode/httpx/issues#issuecomment-515950955

**Comment by VeNoMouS** [comment]
@sethmlarson bad reference link

**Comment by florimondmanca** [comment]
@sethmlarson I second @VeNoMouS — the link leads to the issues board. Any rememberance of where it should have gone to?

**Comment by sethmlarson** [comment]
I don't recall actually. :( That's a shame!

**Comment by VeNoMouS** [comment]
Waaaah Waaaah waaaaaaaaaah

**Comment by florimondmanca** [comment]
@sethmlarson Okay! Do you recall any more context on what `Client.build_request()` should do?

**Comment by sethmlarson** [comment]
I think it was meant to combine all the `merge_*()` functions? Do you remember @tomchristie?

**Comment by tomchristie** [comment]
> I think it was meant to combine all the merge_*() functions?

Yup - we'd like to be able to do something like...

```python
request = client.build_request()
response = await client.send(request)
```
