### ISSUE TITLE
Add HTTPX to the Python documentation.

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#1772]
There are a couple of places in the Python documentation where `requests` is recommended for HTTP requests.

I think that we've done enough work on HTTPX now that we ought to look at getting `httpx` included here, or at *least* open the dialog up. Getting up into the Python docs for 3.10 onwards would seem to be a pretty reasonable aim.

* https://docs.python.org/3/library/http.client.html
* https://docs.python.org/3/library/urllib.request.html

If having a 1.0 release is a blocker to us getting into the docs, then lets make sure we've got a pull request ready to go into the docs, have discussed any wording options through with the Python maintainers, and are aware of any deadlines we'd need to meet in order to get the docs change live. (Eg. is there a deadline if we wanted to be in the docs by the time 3.10 is released fully?)

I'm not super familiar with the process for submitting changes to Python or the Python docs.

**Comment by tomchristie** [comment]
Is anyone able to help out with the following?...

* Figuring out what the process is for making a pull request to the Python docs here?
* Figuring out what deadlines we'd need to meet if we wanted to get this change into the Python 3.10 docs?

**Comment by graingert** [comment]
@tomchristie here's a bpo https://bugs.python.org/issue44908

**Comment by rattrayalex** [comment]
Hi there, I'm a newcomer to Python (well, a returner to Python) and it took me a while to find out that httpx is really the way to make requests in Python in 2022 if I want sync & async support. I think this might be worth another shot (or alternatively, asking the PSF to document on the Requests homepage that it doesn't support async, and that httpx/aiohttp are alternatives which do).
