### ISSUE TITLE
Update h2 pin?

### ISSUE THREAD

**Issue by nicknotfun** [encode/httpx#1798]
### Discussed in https://github.com/encode/httpx/discussions/1485

<div type='discussions-op-text'>

<sup>Originally posted by **HarrySky** February 24, 2021</sup>
Hi, some time ago `h2` pin was updated in `httpcore`: https://github.com/encode/httpcore/pull/208

But it is still pinned to `3.*` in this package's `http2` extra:
https://github.com/encode/httpx/blob/0f280af8b170ed5cc48c12a894f71a8b5762f748/setup.py#L65

This is not an issue, as I can just add `h2>=3,<5` to my setup.py instead of using `httpx[http2]`, but maybe you want dependencies to be in sync with `httpcore`.

EDIT: Using git blame we can see that before `http2` extra - `httpcore[http2]` was used instead of `h2` dependency directly.</div>

**Comment by smoogle** [comment]
Running into this conflict now with aioapns which wants 4.*

**Comment by tomchristie** [comment]
Good call, thanks!
