### ISSUE TITLE
Add a contributing page for httpx

### ISSUE THREAD

**Issue by RatanShreshtha** [encode/httpx#181]

**Comment by sethmlarson** [comment]
Would be great to have a page about how to setup a development environment, using nox (once it's merged), etc.

**Comment by humrochagf** [comment]
Hi,

I started the creation of the contributing page with the #190 PR

I'll need some help with the commands that you are currently using for code coverage and linting so I can add them into the dox automation.

I also need some help with another contributing info like if this project follows any Code of Conduct.

**Comment by humrochagf** [comment]
Oh right, I parsed the commands into the scripts folder to nox command.

Notice that I didn't parse the commands that make changes at the files like `autoflake` and `black`. I don't think it can be a default behavior during the testing round. Maybe we can add them as a format step that can be called by `nox format` or something like that.

Also, notice that the current code only gets 100% coverage on `python 3.7`. On 3.6 and 3.8-dev it gets 99%. And there are some flake8 warnings at the current codebase that the lint command flagged here when I tested.

**Comment by humrochagf** [comment]
Looking through the open PRs I noticed that @sethmlarson implemented the nox pipeline at the PR #128, so since I was kind of reimplementing part of it at #190 I'll wait #128 get merged to organize the contributing page based on #128 implementation.

**Comment by sethmlarson** [comment]
Yup, you can revert your changes for adding nox / flake8 / etc for this PR and suggest changes on the other PR if you think that PR needs updating. Thanks for this! :)

**Comment by humrochagf** [comment]
Great! I reverted the changes and made the suggestions on the PR :smiley:

**Comment by sethmlarson** [comment]
Thanks @humrochagf! I've merged your PR, if anyone wants to add additional helpful information they can open a separate PR. Closing this one!
