### ISSUE TITLE
作者你好，0.19.0版本AsyncClient.__aenter__() 方法增加了调用控制。如果是Singleton instance 则无法重新发送请求

### ISSUE THREAD

**Issue by Anqi0324** [encode/httpx#1874]
The starting point for issues should usually be a discussion...

https://github.com/encode/httpx/discussions

Possible bugs may be raised as a "Potential Issue" discussion, feature requests may be raised as an "Ideas" discussion. We can then determine if the discussion needs to be escalated into an "Issue" or not.

This will help us ensure that the "Issues" list properly reflects ongoing or needed work on the project.

---
```python
async def __aenter__(self: U) -> U:
        if self._state != ClientState.UNOPENED:
            msg = {
                ClientState.OPENED: "Cannot open a client instance more than once.",
                ClientState.CLOSED: "Cannot reopen a client instance, once it has been closed.",
            }[self._state]
            raise RuntimeError(msg)

        self._state = ClientState.OPENED

        await self._transport.__aenter__()
        for proxy in self._mounts.values():
            if proxy is not None:
                await proxy.__aenter__()
        return self
```

**Comment by tomchristie** [comment]
It's not clear what the issue is here.

You'd need to add a code example that explains why this is a problem.

目前还不清楚这里的问题出在什么方面。 您需要添加一个代码示例，解释为什么这是一个问题。
