### ISSUE TITLE
[SSL: NO_PROTOCOLS_AVAILABLE] no protocols available with python 3.10

### ISSUE THREAD

**Issue by ca3tie1** [encode/httpx#1925]
```
from httpx._config import SSLConfig
import httpx
import ssl

ssl_config = SSLConfig(verify=False)
ssl_context = ssl_config.load_ssl_context()
sl_context.options ^= ssl.OP_NO_TLSv1
ssl_context.options ^= ssl.OP_NO_TLSv1_1
ssl_context.options ^= ssl.OP_NO_TLSv1_2
ssl_context.options ^= ssl.OP_NO_TLSv1_3
```
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\httpx\_api.py", line 304, in post
    return request(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\httpx\_api.py", line 100, in request
    return client.request(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\httpx\_client.py", line 785, in request
    return self.send(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\httpx\_client.py", line 871, in send
    response = self._send_handling_auth(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\httpx\_client.py", line 907, in _send_handling_auth
    response = self._send_handling_redirects(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\httpx\_client.py", line 943, in _send_handling_redirects
    response = self._send_single_request(request, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\httpx\_client.py", line 977, in _send_single_request
    (status_code, headers, stream, extensions) = transport.handle_request(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\httpx\_transports\default.py", line 180, in handle_request
    with map_httpcore_exceptions():
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\conte
xtlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-
packages\httpx\_transports\default.py", line 78, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [SSL: NO_PROTOCOLS_AVAILABLE] no protocols available (_ssl.c
:997)

I am trying to be compatible with the request of a old TLS . It is work on Python 3.6 3.7 but didn't work with Python 3.10 and Python 3.8 on Ubuntu.
Is there any solution to this ?

**Comment by ca3tie1** [comment]
This error occurs because the higher version of python no longer supports the use of this method to turn on the support of the old TLS protocol. 
Use the following method to work:
```
    from httpx._config import SSLConfig, DEFAULT_CIPHERS

    ssl_config = SSLConfig(verify=False)
    ssl_context = ssl_config.load_ssl_context()
    try:
        ssl_context.minimum_version = ssl.TLSVersion.TLSv1
    except AttributeError:
        ssl_context.options ^= ssl.OP_NO_TLSv1 
        ssl_context.options ^= ssl.OP_NO_TLSv1_1 
        ssl_context.options ^= ssl.OP_NO_TLSv1_2
        ssl_context.options ^= ssl.OP_NO_TLSv1_3
    ssl_context.set_ciphers(DEFAULT_CIPHERS + 'HIGH:!DH')
```

**Comment by tomchristie** [comment]
Ah great - thanks for following up with that @ca3tie1, really useful to have history for these sorts of things.

Seems a bit odd that it's not supported, but doesn't raise an error.

```python
sl_context.options ^= ssl.OP_NO_TLSv1  # If this *doesn't* work, then it'd be nice if Python was raising an exception here?
ssl_context.options ^= ssl.OP_NO_TLSv1_1
ssl_context.options ^= ssl.OP_NO_TLSv1_2
ssl_context.options ^= ssl.OP_NO_TLSv1_3
```

There's *probably* something worth looking into here - seems like we *might* be able to try to improve the developer user experience, and help guide them towards resolving the issue.

Do you have an example of a public URL that requires the older TLS versions?

*Useful resource for this conversation - [Python 3.10 release notes](https://docs.python.org/3/whatsnew/3.10.html)*

**Comment by ca3tie1** [comment]
> Ah great - thanks for following up with that @ca3tie1, really useful to have history for these sorts of things.
> 
> Seems a bit odd that it's not supported, but doesn't raise an error.
> 
> ```python
> sl_context.options ^= ssl.OP_NO_TLSv1  # If this *doesn't* work, then it'd be nice if Python was raising an exception here?
> ssl_context.options ^= ssl.OP_NO_TLSv1_1
> ssl_context.options ^= ssl.OP_NO_TLSv1_2
> ssl_context.options ^= ssl.OP_NO_TLSv1_3
> ```
> 
> There's _probably_ something worth looking into here - seems like we _might_ be able to try to improve the developer user experience, and help guide them towards resolving the issue.
> 
> Do you have an example of a public URL that requires the older TLS versions?
> 
> _Useful resource for this conversation - [Python 3.10 release notes](https://docs.python.org/3/whatsnew/3.10.html)_

You can test on this URL: https://221.1v82.147.43:4430/
