### ISSUE TITLE
When using http2, the proxy will not automatically reconnect after disconnecting

### ISSUE THREAD

**Issue by GeekDuanLian** [encode/httpx#1937]
Steps to reproduce:

- Open the proxy, request a URL that will stay connected, such as `https://www.google.com/`
- Close and reopen the proxy, request the URL again.
- Raised an error: `httpcore.WriteError: [Errno 104] Connection reset by peer`

At present, you can only manually execute `self._transport.aclose()` to reset the connection status, and then requesting the URL again will not cause an error.

```python3
with httpx.Client(proxies='http://user:password@127.0.0.1:7770', http2=True) as client:
    res = client.get('https://check-host.net/ip')
    print(res.status_code)
    print(res.http_version)

    # timeout should be less than SyncHTTPProxy._keepalive_expiry
    time.sleep(4)  # restart proxy server here

    res = client.get('https://check-host.net/ip')
    print(res.status_code)
    print(res.http_version)
```

**Comment by tomchristie** [comment]
So... this isn't an HTTP/2 thing. (We don't use HTTP/2 with proxy connections anyways. I get a bit mind boggled even trying to figure out if that makes much sense.)

I'd *assume* that you'd likely see the same behaviour with `requests` here, too. And that there's probably not much we can do about it, and that raising a `WriteError` here is probably pretty reasonable behaviour. *However* If someone checks this out and it looks like my assessment here is wrong. That `requests` handles the case without error, and `httpx` doesn't, then I'll happily reconsider this.
