### ISSUE TITLE
Unable to call MSG91 APIs

### ISSUE THREAD

**Issue by upeshphable** [encode/httpx#1942]
I'm trying to use httpx for making REST calls to MSG91 services. The call always fails with error code 302 from MSG91 whereas the same call works using requests library.

```
import httpx

url=f"https://api.msg91.com/api/v5/otp?invisible=1&otp={otp}&mobile={mobile}&authkey={key}"

async with httpx.AsyncClient() as client:
    response = await client.post(url)

    print(response.status_code) # 302
```

The following works:
```
import requests

url=f"https://api.msg91.com/api/v5/otp?invisible=1&otp={otp}&mobile={mobile}&authkey={key}"

response = requests.post(url)

print(response.status_code) # 200
```

**Comment by florimondmanca** [comment]
@upeshphable I believe you'd need to use `AsyncClient(follow_redirects=True)`. Contrary to Requests, HTTPX doesn't follow redirects by default (at least not anymore, since version 0.20.0 I believe), to help developers be more explicit about their intended redirects behavior.

**Comment by upeshphable** [comment]
> @upeshphable I believe you'd need to use `AsyncClient(follow_redirects=True)`. Contrary to Requests, HTTPX doesn't follow redirects by default (at least not anymore, since version 0.20.0 I believe), to help developers be more explicit about their intended redirects behavior.

@florimondmanca I tried it with follow_redirects as well. It's the same result.

**Comment by florimondmanca** [comment]
@upeshphable Having that flag on _and_ receiving 302's would be surprising. It is behaving as designed on my end, with HTTPX 0.21.1:

```pycon
>>> import httpx
>>> httpx.get("https://google.com")
<Response [301 Moved Permanently]>
>>> httpx.get("https://google.com", follow_redirects=True)
<Response [200 OK]>
```

Could you look into where that 302 FOUND brings you by looking at the `Location` header?

**Comment by florimondmanca** [comment]
Hmm, hold on, there you go. You're making a POST request. As per the HTTP spec (RFC 2616), redirects aren't followed for this HTTP method. So `follow_redirects` making no difference is expected — you should be using the definitive URL in this case, which you'll find in `response.headers["Location"]`. :-)

**Comment by tomchristie** [comment]
@florimondmanca - Your initial assessment was correct. We *do* follow 302's despite the RFC (because that's what `requests` and browsers do)

See eg...

* https://github.com/encode/httpx/blob/716749e3fd3c99cb47cc20b96def280dcb3c8d16/httpx/_models.py#L1451
* https://github.com/encode/httpx/blob/master/httpx/_client.py#L487

@upeshphable It really *should* work with `follow_redirects=True`. I'd suggest you try an example that's as similar to the requests example you're using and show us the results...

```python
import httpx

url=f"https://api.msg91.com/api/v5/otp?invisible=1&otp={otp}&mobile={mobile}&authkey={key}"

response = httpx.post(url, follow_redirects=True)

print(response.status_code) # 200
```

Or to simplify things further, just try it with the command line client, and show us the results you see (stripping out any private info if needed)

```shell
$ httpx -m POST https://api.msg91.com/api/v5/otp?invisible=1&otp={otp}&mobile={mobile}&authkey={key}
```

**Comment by upeshphable** [comment]
@florimondmanca @tomchristie I tried the follow_redirects this morning and it worked. It's following redirects. I guess I was having a bad day :-( I can see the requests for redirects and eventually ending up with a good response. See the response below. Earlier it didn't have this :P

Thank you for your guidance!

```
DEBUG     2021-11-20 12:36:12,038 httpx._client:_send_single_request():L1684 HTTP Request: POST https://api.msg91.com/api/v5/otp?invisible=1&authkey=xxxxxxxxx&mobile=xxxxxxxxx&otp=12345&template_id= "HTTP/1.1 302 Found"
DEBUG     2021-11-20 12:36:12,186 httpx._client:_send_single_request():L1684 HTTP Request: GET https://mc.zumigo.com/zumigows/identifyDevice?sessionId=25CBE-8B3B-C6D9A2B42DB2&correlationId=316b746c4a6c383103438&redirectUrl=https%3A%2F%2Fcontrol.msg91.com%2Fapi%2Finvisible_response.php&mdnHint=xxxxxxxxx&customData=316b%3Csep%3E2021-11-20%2012:36:12 "HTTP/1.1 303 See Other"
DEBUG     2021-11-20 12:36:12,443 httpx._client:_send_single_request():L1684 HTTP Request: GET https://control.msg91.com/api/invisible_response.php?sessionId=25CBE-8B3B-C6D9A2B42DB2&correlationId=316b746c4a83134303438&customData=3166c4a6c383138%3Csep%3E2021-11-20+12%3A36%3A12&mdnHint=xxxxxxxxx&status=ERROR&code=900002&message=SERVER_ERROR&detailMessage=BACKEND_SERVER_FAILED&info=backend%20server%20failed "HTTP/1.1 302 Found"
DEBUG     2021-11-20 12:36:12,532 httpx._client:_send_single_request():L1684 HTTP Request: GET https://control.msg91.com/api/sendotp.php?authkey=xxxxxxxxx&mobile=xxxxxxxxx&otp=12345&template_id=&is_v5=1&for_panel_id=1&route=106&response=json&mobiles=xxxxxxxxx&invisible_request_id=316b746c4a6c383134303438 "HTTP/1.1 200 OK"
```
