### ISSUE TITLE
Fallback when faulty Content-Encoding header is set?

### ISSUE THREAD

**Issue by rinti** [encode/httpx#195]
Hi!

I am trying to use httpx to talk with an API that sends this header:
`Content-Encoding: UTF-8`
which obviously is an invalid header, this however prevents me from getting a response as I get this error:
```
  File "/Users/andreas/repositories/bussen/venv/lib/python3.7/site-packages/httpx/models.py", line 781, in decoder
    decoder_cls = SUPPORTED_DECODERS[value]
KeyError: 'utf-8'
```

If i try using requests instead it works. I'd be happy to try to help if I get a little guidance on what would be a sensible fallback here.

**Comment by sethmlarson** [comment]
Closed via #196
