### ISSUE TITLE
Making the exceptions pickleable

### ISSUE THREAD

**Issue by randrej** [encode/httpx#1990]
### Discussed in https://github.com/encode/httpx/discussions/1987

<div type='discussions-op-text'>

<sup>Originally posted by **randrej** December 27, 2021</sup>
I'm often using `httpx` with multiprocessing queues and such, and whenever `httpx` throws I get an exception similar to [this one](https://bugs.python.org/issue37208). Adding proper `__reduce__` methods to the exceptions, like explained [here](https://stackoverflow.com/a/36342588) would mitigate this issue completely.

Here's a concrete example of the error occurring:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/process.py", line 384, in wait_result_broken_or_wakeup
    result_item = result_reader.recv()
  File "/usr/local/lib/python3.9/multiprocessing/connection.py", line 256, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() missing 1 required keyword-only argument: 'request'
```

I'm offering to contribute this functionality if the maintainers are willing to merge it.</div>

**Comment by tomchristie** [comment]
Hiya Andrej, thanks! I'm a bit lukewarm towards pickle, but we *could?* consider this.
What I'd always recommend as a first step is making a comparison against other HTTP clients.

Taking a look at `requests` - [I don't see this for their exceptions](https://github.com/psf/requests/blob/main/requests/exceptions.py). Given that their project has a much longer history than ours, I think that's not a bad point of reference. Are you able to find any discussions on their issue history requesting this? What resolution did they reach?

**Comment by zpz** [comment]
I had the same issue caused by httpx.HTTPStatusError not pickle-able in multiprocessing code. Spent some time to track down and hacked it to make it pickle-able.

On a quick look, I don't see the `requests` page contains custom Exception classes that are not pickle-able. Of course, the lack of pickle methods on that page does not make things un-pickleable. It's the extra args to `httpx.HTTPStatusError`  that are not passed to super that makes it un-pickle-able.

**Comment by zpz** [comment]
Concurrent.futures has some code to make exceptions pickleable, so that Future can raise exceptions that happened in a worker process. If that worker uses httpx and raises HTTPStatusError, then it will be broken. My use case is somewhat similar. The design passes results between processes, including exception objects.

**Comment by gkoller** [comment]
We had to work around this issue as well (we use Celery). It is easily resolved by calling `super().__init__` with all the arguments that were supplied to the custom exception's `__init__`.

This is detailed in:
1. Celery's documentation: https://docs.celeryq.dev/en/stable/userguide/tasks.html#creating-pickleable-exceptions
2. Python Cookbook, 3rd edition - David Beazley & Brian K. Tones, Chapter 14, section .8. Creating Custom Exceptions: _If you are going to define a new exception that overrides the __init__() method of Exception, make sure you always call super().__init__() with all of the passed arguments._ [...] _This might look a little weird, but the default behavior of Exception is to accept all arguments passed and to store them in the .args attribute as a tuple. Various other libraries and parts of Python expect all exceptions to have the .args attribute, so if you skip this step, you might find that your new exception doesn’t behave quite right in certain contexts._

Unfortunately this is not detailed in any official documentation. But the Python cookbook is right on when is says: _so if you skip this step, you might find that your new exception doesn’t behave quite right in certain contexts_.

**Comment by lovetox** [comment]
@lovelydinosaur  could you please reopen this ticket?

It was closed with the reason "completed" but no reason for closing was given and no new code was introduced.

As the others found out, the custom Exception of httpx does not correctly subclass the base Exception type in python.

The current approach is catching this exception and converting it into a different application exception which subclasses correctly. This is a bit ugly.

**Comment by oelhammouchi** [comment]
+1
