### ISSUE TITLE
When using proxy the request downgrades to HTTP/1

### ISSUE THREAD

**Issue by biplovdahal** [encode/httpx#1992]
Using the following code

```
client = httpx.Client(http2=True, proxies=proxies)
 response = client.get('https://www.truepeoplesearch.com/results?name=John', headers=headers)
response.http_version
```

It appears that it returns HTTP/1

but if I were to make the same request without proxy, it shows HTTP/2

Version of HTTPX being used.
```
Name: httpx
Version: 0.21.1
Summary: The next generation HTTP client.
Home-page: https://github.com/encode/httpx
Author: Tom Christie
Author-email: tom@tomchristie.com
```

**Comment by chinaliukun** [comment]
Same problem in httpx 0.21.1. I try the socks5 and http proxy, and they all failed. But I can get normal http2 response via Chrome using proxy. So weird.

**Comment by biplovdahal** [comment]
@yofeng2021 Yes, same with me. I was able to load proxy via chrome and the request went through HTTP/2. I think the issue stands with the library httpx itself. I recall this was working couple months ago, all of a sudden it stopped.
