### ISSUE TITLE
Implement HTTP Forwarding Proxy

### ISSUE THREAD

**Issue by sethmlarson** [encode/httpx#202]
Related: #36

**Comment by tomchristie** [comment]
What's the difference between this and #201?

**Comment by sethmlarson** [comment]
Forwarding is sending a request to a proxy and that proxy makes the request on your behalf and then gives you back the response.

Tunnel/CONNECT is asking the proxy for a TCP tunnel via CONNECT and then proceeding with HTTP(S) as normal through that tunnel.

**Comment by tomchristie** [comment]
So in the requests API, where we have `proxy={http=..., https=...}` then the `http` value should point at a simple forwarding proxy address, and the `https` value should point at a Tunnel/Connect proxy address? (Or have I got that wrong?)

**Comment by GnubiBORED** [comment]
@sethmlarson in my case i need to be able to add extra headers to those CONNECT/tunnel when proxy is used will be possible?

**Comment by sethmlarson** [comment]
@GnubiBORED Yes that will be possible via configuring your proxy like so (or something similar, API isn't nailed down yet):

```python
import httpx

proxy = httpx.HTTPProxy("http://127.0.0.1:8080", proxy_headers={"Proxy-Authorization": "..."})
client = httpx.Client(
    proxies={"http": proxy, "https": proxy}
)
```

For HTTP (forwarding) the headers are sent with the request.
For HTTPS (tunnel) the headers are sent with the CONNECT request but not the requests made after tunneling. Those are controlled by `headers=...`.

Does that handle your use-case? :)

**Comment by GnubiBORED** [comment]
yep it handle my case totally, only question more is thath if i can order headers passing and collections.OrderectDict like i do in requests. but i think its possible and works, correct me if im incorrect

**Comment by sethmlarson** [comment]
@GnubiBORED: To answer your questions:

For HTTP Forwarding proxies (http://...) the proxy headers are joined to the request headers that are sent to the proxy. It's up to the proxy to strip them (`Proxy-Authorization`, etc)

For HTTP CONNECT proxies (https://...) the proxy headers are only sent for the CONNECT request. The actual request won't include any of the proxy headers.

And yes if you pass an iterable of tuples order is preserved.

**Comment by GnubiBORED** [comment]
any update in proxy implementation in httpx?

**Comment by sethmlarson** [comment]
I'm working on combining the proxy implementations. I have them working I believe the issue now is writing tests for them. Will push what I have today and continue writing tests.

**Comment by GnubiBORED** [comment]
you will comment it on HTTP(S) Proxy Support (TODO) in readme once its done?

**Comment by sethmlarson** [comment]
Yeah I'll be removing that and in the docs. :)

**Comment by adrianmeraz** [comment]
Awesome work @sethmlarson , this has been a long-standing reason why I couldn't use HttpX just yet.

**Comment by sethmlarson** [comment]
@adrianmeraz I'm so glad! :) Have you tested the PR to see if it works properly for your user-case? Would love more eyes on it.

**Comment by adrianmeraz** [comment]
@sethmlarson I'll be sure to test it out ASAP!

**Comment by GnubiBORED** [comment]
im new to python but its already testeable? if yes i would like to test these

**Comment by sethmlarson** [comment]
Yeah @GnubiBORED you would have to pull this exact branch though. Once it lands in master I'll be tagging a new release so everyone waiting for proxies can try the new feature. :)

**Comment by GnubiBORED** [comment]
@sethmlarson i downloaded these
e

**Comment by GnubiBORED** [comment]
also with
`client = httpx.Client(
    proxies={"http": proxy, "https": proxy}
)`
i get 
`    proxies={"http": proxy, "https": proxy}
TypeError: __init__() got an unexpected keyword argument 'proxies'

Process finished with exit code 1
`

**Comment by sethmlarson** [comment]
@GnubiBORED @adrianmeraz Proxies are in the latest release! :tada: Could you give them a try?
