### ISSUE TITLE
Support digest authentication for HTTP proxies.

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#2033]
Escalating discussion https://github.com/encode/httpx/discussions/2028 into an issue.

HTTP proxies are sometimes configured to use digest authentication.
Right now we only support basic authentication with HTTP proxies.
It'd be worthwhile to also support digest - which requires following up the initial `CONNECT` request to the proxy with a subsequent authentication request before the proxy tunnel is established.

Here's [the original discussion](https://github.com/encode/httpx/discussions/2028)...

<div type='discussions-op-text'>

<sup>Originally posted by **raffaem** January 13, 2022</sup>
Does httpx support DigestAuthentication for proxies, and if so, can you connect to HTTPS websites through a proxy that requires DigestAuthentication?

[requests-toolbet](https://github.com/requests/toolbelt) has a `HTTPProxyDigestAuth` class, but it does **not** allow you to connect to HTTPS through the proxy.

Apparently that feature [won't be implemented](https://github.com/psf/requests/issues/6025) in the foreseeable future in requests.

The only working implementation that I have found, and which allows you to connect to HTTPS websites through the proxy, is [this one](https://gist.github.com/Tey/ded2486da8a69bb84d2dce94e2e09ff7#file-requests_digest_proxy-py), which was provided in [this StackOverflow post](https://stackoverflow.com/a/60031108/1719931).

Does httpx support this feature, or will it support it?</div>

**Comment by tomchristie** [comment]
Still valid thx, @stale bot.

**Comment by gjmhmm8** [comment]
1

**Comment by tomchristie** [comment]
I think we should consider closing this since we've only had one person ever request this.

There's enough documentation and pointers around `httpcore` for someone who's interested to be able to start tackling it. If someone ends up interested and invested in resolving that, then I think that'd be a good indicator that it'd be worth re-opening.

Seem valid @encode/maintainers?

**Comment by tomchristie** [comment]
I'm going to close this ticket off for now - if someone bumps into this as a requirement please let us know.
Otherwise / until then, we'll be treating this as out of scope.
