### ISSUE TITLE
Specified timeout not enforced (using a proxy)

### ISSUE THREAD

**Issue by esbenkolsbjerg** [encode/httpx#2073]
In the process of upgrading some very old packages I noticed a huge performance drop of a specific proxy pool. I tracked the issue to the timeouts set not being enforced. 
 
For this specific pool we usually run with `timeout = httpx.Timeout(5, connect=3.15)`. But the requests are not timed out at all and they fail when the proxy service behind returns a `httpx.ProxyError: 503 Service Unavailable` after 60 s. 

I tried some different combinations of httpcore and httpx with the following results below:

httpcore==0.13.7 + httpx[http2]==0.20.0: httpx.ProxyError: timed out (This happens after 5 s with a "timeout = httpx.Timeout(5, connect=3.15)" aka works as expected)
httpcore==0.14.0 + httpx[http2]==0.21.0: httpx.ProxyError: 407 Proxy Authentication Required (All the time. This happens for other proxy services as well)
httpcore==0.14.1 + httpx[http2]==0.21.0: httpx.ProxyError: 503 Service Unavailable (This happens after 60 s with a "timeout = httpx.Timeout(5, connect=3.15)")
httpcore==0.14.7 + httpx[http2]==0.22.0: httpx.ProxyError: 503 Service Unavailable (This happens after 60 s with a "timeout = httpx.Timeout(5, connect=3.15)")
httpcore==0.14.7 + httpx[http2]==0.22.0: httpx.ProxyError: 503 Service Unavailable (This happens after 60 s with a "timeout = DEFAULT_TIMEOUT_CONFIG = Timeout(timeout=5.0)")

As far as I can see everything (related to this) works as expected with a combination of httpcore==0.13.7 and httpx[http2]==0.20.0. But after the write of httpcore for 0.14.0 it hasn't worked. My guess this behavior is NOT intended?

**Comment by tomchristie** [comment]
Thanks for raising this @esbenkolsbjerg.

Yes, that'll have crept in with 0.14.

Taking a look, I can see where this is happening...

We [construct the connect request here](https://github.com/encode/httpcore/blob/cad62bf9a5c1b83e9a32bdabf84b134a4683cee2/httpcore/_async/http_proxy.py#L252-L257)...

```python
                connect_request = Request(
                    method=b"CONNECT", url=connect_url, headers=connect_headers
                )
                connect_response = await self._connection.handle_async_request(
                    connect_request
                )
```

However, we're not including the `extensions=...`, which is where the "connect" timeout is included.

We need to tweak that to include `extensions=extensions` (for both the async and sync cases).

Would you like to take a go at a pull request resolving that? (No worries if not, myself or someone else on the team will also happily step in)

**Comment by esbenkolsbjerg** [comment]
Hi @tomchristie 

Thanks for the VERY quick reply. I'm not to familiar with the code so it would be awesome if one of you guys could resolve it.

**Comment by tomchristie** [comment]
Alrighty then - resolved in https://github.com/encode/httpcore/pull/506

You're welcome to test against that branch if you want to verify it for yourself.
I think you can use the following to install it with `pip`?...

```shell
$ pip install git+https://github.com/encode/httpcore.git@fix-proxy-connect-timeout
```

> Thanks for the VERY quick reply.

Ah yeah, the benefits of funded open source development. (At least when it's working well, that is.)

**Comment by tomchristie** [comment]
Great! I expect we'll push a new `httpcore` version out soon enough.
