### ISSUE TITLE
Switch to explicit typing.Optional throughout

### ISSUE THREAD

**Issue by michaeloliverx** [encode/httpx#2092]
See the following snippet:

```python
from contextlib import AsyncExitStack

import httpx


async def main() -> None:
    async with AsyncExitStack() as stack:
        http_client = await stack.enter_async_context(httpx.AsyncClient())
        reveal_type(http_client)
```

Output with `strict = false`:

```
repro.py:9: note: Revealed type is "httpx._client.AsyncClient*"
```

Output with `strict = true`:

```
repro.py:8: error: Need type annotation for "http_client"  [var-annotated]
repro.py:8: error: Argument 1 to "enter_async_context" of "AsyncExitStack" has incompatible type "AsyncClient"; expected "AsyncContextManager[<nothing>]"  [arg-type]
repro.py:9: note: Revealed type is "Any"
Found 2 errors in 1 file (checked 1 source file)
```

---

I initially raised an issue at https://github.com/python/mypy/issues/12226 but it looks to be an issue with `httpx`. They said 

> The annotations at https://github.com/encode/httpx/blob/7883c98556eaa7630454d5b62426a5c497542408/httpx/_client.py#L1970 need to be changed to Optional.

**Comment by tomchristie** [comment]
Perhaps we should re-title this as the more general case.

Something like "Switch to explicit typing.Optional throughout" (?)

**Comment by tomchristie** [comment]
See also https://github.com/encode/httpx/pull/1760, https://github.com/encode/httpx/discussions/1747

**Comment by nhoad** [comment]
If no one has picked this up yet, I'm happy to take a crack at it.

I've been working on it a little bit and I've got the total number of errors from `mypy --strict httpx` down from 437 to 207, just by adding `typing.Optional` or adding `None` to some already existing `typing.Union` definitions (e.g. `httpx._types.HeaderTypes`).

Happy to continue the work and open a PR if people are interested.

**Comment by florimondmanca** [comment]
@nhoad Hi, it looks like there's initial work on this here: #2092
