### ISSUE TITLE
Large ".pack" file in repo causes very long clone time

### ISSUE THREAD

**Issue by florimondmanca** [encode/httpx#212]
Hey,

While cloning the repo locally (over SSH) I noticed an unusually long clone time (~5min, 25MB). I tracked this down to this file stored in the git history:

```
.git/objects/pack/pack-0458eb2f12bd2dd2025bf18c69e7c95a24e8c1c3.pack
```

I suppose this may be from a previously large object stored in the repo, but not sure. Any idea?

This is not critical at all — just reporting because it could be a bit cumbersome for newcomers. :-)

**Comment by sethmlarson** [comment]
Hm, that's interesting. Is there anything we can do about that or is it kinda just there forever unless we change our git history?

**Comment by florimondmanca** [comment]
My guess is that it’s somewhere in the git history, but finding which commit(s) made it appear doesn’t seem trivial to me. I may try and bisect my way through the repo and report back here. 👍

**Comment by behrtam** [comment]
Seems to be about images in `/docs`...

```
pack-size   hash           path
13784 KiB   8d53a5a3bdd4   docs/img/compatibility.jpg
 5333 KiB   49b510fa81fb   docs/img/leaf.jpg
 1452 KiB   7c574313b78b   docs/img/async.jpg
 1008 KiB   6c6552645cc0   docs/img/quickstart.jpg
  545 KiB   029d9b390aaa   docs/img/advanced.jpg
  351 KiB   4f890d9a0e04   docs/img/parallel.jpg
  295 KiB   d2b8a6975c90   docs/img/requests-sidebar.png
```

https://stackoverflow.com/questions/2100907/how-to-remove-delete-a-large-file-from-commit-history-in-git-repository

**Comment by sethmlarson** [comment]
Great detective work! Is there anything we can do to fix the history?

**Comment by tomchristie** [comment]
Deleted the `requests3` branch, which is the only place the large images were included.

Appears resolved to me now (based on cloning times before and after the delete).
