### ISSUE TITLE
`raise_for_status` now raises an exception for 1xx and 3xx responses

### ISSUE THREAD

**Issue by remi-dupre** [encode/httpx#2126]
Hi!

I've just noticed that `response.raise_for_status()` now raises an exception for 1xx and 3xx requests. I don't think it was the case before (namely with version 0.18) and the documentation doesn't seem to have been updated here: https://www.python-httpx.org/exceptions/

> The HTTPStatusError class is raised by response.raise_for_status() on 4xx and 5xx responses.

### Steps to reproduce (even though I think this is an intentional behavior, the doc is just not up to date?)

```python
import httpx
url_301 = "https://stat.pagesjaunes.fr/redirect?target=ETvxvbcLWawl69YzLe_Ph4vo03E_Yj6_Jt1_EvjjbHFaCE3c9RGLEg==&v=2.0&p1=1&p2=1&p3=&p4=RESEAUSOC-SITE-LVS-GRATUIT&p5=LR&p6=1361647273529289141447273529289&p7=06486910&p8="
httpx.get(url_301, follow_redirects=False).raise_for_status()

**Comment by florimondmanca** [comment]
@remi-dupre Hey, indeed this seems to come from https://github.com/encode/httpx/pull/1854, the documentation had not been updated at the time, PR description reads:

> The .raise_for_status() method now raises on any response except 2xx.

I assume we could change the docs to read... ?

> The HTTPStatusError class is raised by response.raise_for_status() on any response except 2xx.

**Comment by tomchristie** [comment]
Yup, seconding @florimondmanca here.
Nice simple docs fix if anyone would like to take it on.
