### ISSUE TITLE
Custom Transport docs out of date as of 0.20.*

### ISSUE THREAD

**Issue by johtso** [encode/httpx#2129]
The docs still use the old primitive data structures in `handle_request` rather than the new `Request` object.

https://www.python-httpx.org/advanced/#writing-custom-transports

**Comment by stranger-danger-zamu** [comment]
It appears to be right in the BaseTransport docstring:

https://github.com/encode/httpx/blob/c82885ac04f7c3439dfdd4d26614913bf09389c9/httpx/_transports/base.py#L22-L52

So it might just be bubbling up those changes up.

**Comment by johtso** [comment]
Looks like this was sorted here: https://github.com/encode/httpx/pull/2070
