### ISSUE TITLE
Don't render Authorization, Proxy-Authorization headers, password in URLs

### ISSUE THREAD

**Issue by sethmlarson** [encode/httpx#220]
We could render them as `[secure]` when calling `__repr__` so that they're not exposed by logging services. Was wondering what others thought of this idea?

**Comment by cansarigol** [comment]
Hi, I tried to add this feature. 
In debug logging level case, this doesn't work and we will need a logging formatter. I'm not sure we should think about it.  
If this approach makes sense, we can use it.

**Comment by tomchristie** [comment]
Yeah we do the same with Starlette’s URL class. Def in favour (tho probably just repr, not str)
