### ISSUE TITLE
Curio still mentioned in docs although unsupported since 0.21.0

### ISSUE THREAD

**Issue by florimondmanca** [encode/httpx#2233]
See discussion https://github.com/encode/httpx/discussions/2232?converting=1, see also comment https://github.com/encode/httpx/discussions/1953#discussioncomment-1715439

Curio is still mentioned in documentation here as being supported: https://www.python-httpx.org/async/#curio

But it was dropped in version 0.21.0, when HTTPCore dropped curio support as part of the 0.14.0 redesign.

There is discussion on getting curio support back: https://github.com/encode/httpx/discussions/1953

But right now the documentation is incorrect and curio should be dropped from it.

**Comment by florimondmanca** [comment]
Hi @kcoderhtml, sure, feel free to read through the Contributing Guide if you need info on settings things up! https://www.python-httpx.org/contributing/

**Comment by kcoderhtml** [comment]
Thanks!

**Comment by kcoderhtml** [comment]
Can you assign me to this?

**Comment by kcoderhtml** [comment]
Completed! Awaiting approval for merge.
