### ISSUE TITLE
ASGI/WSGI transport does not honor timeouts, but should

### ISSUE THREAD

**Issue by AllSeeingEyeTolledEweSew** [encode/httpx#2239]
For ASGI:

```python
import asyncio
import httpx

async def forever_app(*args):
    forever = asyncio.get_event_loop().create_future()
    await forever

async def main():
    client = httpx.AsyncClient(app=forever_app, timeout=1e-6)
    await asyncio.wait_for(client.get("/"), 1)

asyncio.run(main())
```

Expected: `httpx.TimeoutException`
Got: `asyncio.TimeoutError`

---

For WSGI:

```python
import httpx
import time

def forever_app(*args):
    time.sleep(1e8)

def main():
    client = httpx.Client(app=forever_app, timeout=1e-6)
    client.get("http://test")

main()
```

Expected: `httpx.TimeoutException`
Got: hangs

**Comment by AllSeeingEyeTolledEweSew** [comment]
Apologies; I fat-fingered the "new issue" button without a description. I've edited it, but I believe email notifications don't show the edits, so this may look weird to email readers.

Apologies also if I jumped the gun by not opening a discussion / feature request, but IMO if the team doesn't want to honor timeouts for ASGI/WSGI, this should at least be documented!

**Comment by florimondmanca** [comment]
That sounds like a fair issue report to me. Don’t see a reason app transports shouldn’t apply the `timeout` extension.

**Comment by jhominal** [comment]
Thing is, applying the `timeout` extension does not sound straightforward to me...

That is, for a WSGI application, applying the timeout seems to require running the WSGI callable object in another thread, and for an ASGI application, in another task.

Is that an acceptable cost for us?

**Comment by tomchristie** [comment]
So, I'm not really in favour of timeouts for WSGI/ASGI transports, because the timeouts are intended as *network* timeouts.

The Flask and Django test clients do not include timeouts, and I don't think they'd make any more sense here either.

Tho yes, would be in favour of any well formed pull request documenting this.

**Comment by AllSeeingEyeTolledEweSew** [comment]
> So, I'm not really in favour of timeouts for WSGI/ASGI transports, because the timeouts are intended as _network_ timeouts.
> 
> The Flask and Django test clients do not include timeouts, and I don't think they'd make any more sense here either.
> 
> Tho yes, would be in favour of any well formed pull request documenting this.

If that's the intended use, I'd also expect an error if I pass `timeout=` to a client with a non-network transport.

Otherwise, it's a footgun for people to write a bunch of tests which use `timeout=` and pass, and then later hang when the app hangs, rather than failing. This is the footgun that led me here
