### ISSUE TITLE
Dependency [h11<0.13.0] conflict while using alone with Hypercorn[h11==0.13.0]

### ISSUE THREAD

**Issue by noctoid** [encode/httpx#2244]
Hi, I just found out a issue while building an RPC framework which is run by Hypercorn which requires 0.13.0 that conflicts with the httpx's requirement which is h11<0.13.0.

Is there anyway to lift the constraint of h11 version number lower than 0.13.0? or there is a must situation that we indeed require such version?

On the other hand, humbly asking, is there a more simple way to fix this conflict issue?

**Comment by yan12125** [comment]
Apparently newer h11 is blocked by httpcore: https://github.com/encode/httpcore/pull/526

**Comment by madkinsz** [comment]
You can track removal of the upper pin from httpcore in https://github.com/encode/httpcore/issues/509 and support for h11 0.13+ in https://github.com/encode/httpcore/pull/579
