### ISSUE TITLE
Text streaming

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#24]
Currently all of the streaming APIs we're providing are byte-wise. We ought to also support text-decoding interfaces.

This would likely mean that we'd want `stream(text=True)`. Difficulties here are that we don't have `.apparent_encoding` available to us prior to the content being available. We'd need to use [chardet's incremental decoding](https://chardet.readthedocs.io/en/latest/usage.html#example-detecting-encoding-incrementally) as well as an [incremental decoder](https://docs.python.org/3/library/codecs.html#codecs.getincrementaldecoder)

I'd suggest we'd want to implement this by adding a `TextDecoder(encoding=None)` class to `decoders.py` that takes the `charset_encoding` as it's initial argument. It would implement the same interface as the existing decoders, except returning `str`.

Aside: It's possible that in the future we might start to move more into line with requests' `iter_content()` and `iter_lines()`.

**Comment by graingert** [comment]
having an incrementally decoding File and StreamReader like objects would be amazing contributions to the chardet project https://github.com/chardet/chardet/issues/154
