### ISSUE TITLE
Version 0.23.1 broke dependent packages

### ISSUE THREAD

**Issue by vertexclique** [encode/httpx#2457]
Hi,

Removing RawURL support in 0.23.1 broke:
* Datadog's official package: https://github.com/DataDog/dd-trace-py
* Python schema registry client: https://github.com/marcosschroh/python-schema-registry-client

Personal suggestion, having this communicated before rollout (like changing surface API) would be really nice.

**Comment by tomchristie** [comment]
Indeed - an error in judgement on my part.

`httpx.RawURL()` was an old undocumented piece of API which we no longer need. I rushed it into a minor point release, when I should have been pushing for a 0.24.0 release instead. Lesson learned.

**Comment by vertexclique** [comment]
All good, thanks for your fantastic responsiveness. I will also cross-notify downstream of datadog dep since they are monkey patching that API on load. That's not going to work anymore.

**Comment by tomchristie** [comment]
Okay, we've called these changes out more explicitly in the release notes now.
I guess that's good enough for now.
Shall we close this issue off?

**Comment by vertexclique** [comment]
Thanks already. Yes, please! 🚀
