### ISSUE TITLE
Breaking drop of URL.raw in patch release 0.23.1

### ISSUE THREAD

**Issue by developerDemetri** [encode/httpx#2462]
The patch release `0.23.1` included a breaking change in #2241 

The justification seems to be that "we don't use it", but `url.raw` is a public property used by other libraries including `ddtrace` 0.x versions: https://github.com/DataDog/dd-trace-py/blob/v0.61.3/ddtrace/contrib/httpx/patch.py#L41 

Can this breaking change be reverted and maybe soft-deprecated? @tomchristie @michaeloliverx

**Comment by developerDemetri** [comment]
Looks like this has been raised in https://github.com/encode/httpx/issues/2457 but it seems like reverting here would be more ideal (and safer) than hoping other dependencies all patch their usage?

**Comment by tomchristie** [comment]
@developerDemetri - Would it help you folks if we released a patch version which included `url.raw` returning a `NamedTuple`? That wouldn't be a full rollback or adding `httpx.RawURL` back to the API, but we could do that quickly and easily, and it would resolve the specific case you're pointing to.

**Comment by developerDemetri** [comment]
> @developerDemetri - Would it help you folks if we released a patch version which included `url.raw` returning a `NamedTuple`? That wouldn't be a full rollback or adding `httpx.RawURL` back to the API, but we could do that quickly and easily, and it would resolve the specific case you're pointing to.

Yup, that should help for our use case and anyone else relying on `url.raw`

**Comment by developerDemetri** [comment]
> > @developerDemetri - Would it help you folks if we released a patch version which included `url.raw` returning a `NamedTuple`? That wouldn't be a full rollback or adding `httpx.RawURL` back to the API, but we could do that quickly and easily, and it would resolve the specific case you're pointing to.
> 
> Yup, that should help for our use case and anyone else relying on `url.raw`

@tomchristie I took a stab at this in https://github.com/encode/httpx/pull/2481
