### ISSUE TITLE
SSL IP address mismatch error via ssh tunnel (But curl works)

### ISSUE THREAD

**Issue by funkindy** [encode/httpx#2513]
Hi. I have a client-side *.pem to access remote server. Because of the server IP whitelist i use ssh port proxy via trusted host. So the target url on my local machine is `https://127.0.0.1:someport/endpoint`

I init AsyncClient with `verify=httpx.create_ssl_context(cert="certfile.pem", verify=False)` to disable all cert verifications, but i still get this error: `httpx.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '127.0.0.1'. (_ssl.c:1131)`

the strange part is that curl works just fine in exactly the same environment. Curl command:

```
curl https://127.0.0.1:someport/endpoint --cert "certfile.pem" --insecure
```

Is there any different between httx's `verify=False` and curl's `--insecure` maybe? Or am i missing something obvious?

Thank you.

**Comment by tomchristie** [comment]
Were you missing something obvious?

**Comment by funkindy** [comment]
> Were you missing something obvious?

Yes, i've passed a custom transport to AsyncClient, which overrides client level verify arg (should provide ssl context directly to the transport instance). Maybe a kind of a warning could help but its ok.
