### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by nmoreaud** [encode/httpx#2560]
From https://pypi.org/project/http3/ we reach this repository and www.encode.io/http3 which returns 404

**Comment by Kludex** [comment]
It's httpx, not http3 🤔

**Comment by kirisakow** [comment]
> It's httpx, not http3 :thinking: 

Sure. Still, the https://pypi.org/project/requests-async/ project's home page still advertises a dead link, with @tomchristie as maintainer. Someone's gotta fix that.
