### ISSUE TITLE
Client superfluously adding a trailing forward slash when provided with an empty path

### ISSUE THREAD

**Issue by Mardoxx** [encode/httpx#2673]
https://www.rfc-editor.org/rfc/rfc3986#section-3
and
https://www.rfc-editor.org/rfc/rfc3986#section-3.3

Are http://base and http://base/ two distinct URLs? If so, so why does this is behaviour exist?

```
>>> from httpx import Client
>>> Client().build_request("GET",  "")
<Request('GET', '/')>
>>> Client().build_request("GET",  "/")
<Request('GET', '/')>
>>> 
```

**Comment by tomchristie** [comment]
See the HTTP/1.1 spec, [RFC 2616](https://www.rfc-editor.org/rfc/rfc2616#section-5.1.2)...

> Note that the absolute path cannot be empty; if none is present in the original URI, it MUST be given as "/"
