### ISSUE TITLE
Square brackets no longer work

### ISSUE THREAD

**Issue by sathio** [encode/httpx#2694]
A GET request such as `/?arr[]=1&arr[]=2` is perfectly legal and it means that you are trying to send an array of values to the endpoint.

Unluckily after 0.23.3 it stopped working because requests are sent as `/?arr%5B%5D=1&arr%5B%5D=2`

**Comment by tomchristie** [comment]
hrm... my reading of RFC 3986 is that square brackets *do* need escaping in the path component.

See https://www.rfc-editor.org/rfc/rfc3986#section-3.3

```
pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
```

And...

https://www.rfc-editor.org/rfc/rfc3986#section-2.2

```
      reserved    = gen-delims / sub-delims

      gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"

      sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
                  / "*" / "+" / "," / ";" / "="
```

The condensed https://www.rfc-editor.org/rfc/rfc3986#appendix-A is helpful there.

Am I reading this wrong?

However, I can see that chrome does *not* percent-escape square brackets in the path. Perhaps the browser behaviour differs from the RFC spec?

**Comment by sathio** [comment]
You are actually right, this is poorly documented and looks like sending non escaped square brackets is a standard de facto. 

The ugly solution would be to add a `strict` parameter, it's definitely breaking something that used to work in the past :)
