### ISSUE TITLE
Does HTTPX support single-connection HTTP/2 with unbounded concurrent requests?

### ISSUE THREAD

**Issue by PrimozGodec** [encode/httpx#281]
First sorry for opening an issue but I didn't find a better way to reach you. Thank you for developing a good looking library which supports HTTP/2. 

We are tinking for switching to HTTPX. Before I start with the implementation, I have two questions about parallel requests. Those things were not clear from the documentation.

1. We have a server that supports HTTP/2 protocol and wants to send multiple parallel requests through one connection to the server. Does `httpx.Client()` use of one connection for multiple parallel requests or it connects multiple times? What about `httpx.parallel()`?

2. If it is possible to send multiple parallel requests through one connection, do we need to handle the number of requests manually when we send a huge number of requests (e.g. 1000) - that we do not reach the limit of requests per connection. What I mean is do we need to send let say 100 requests and then wait for responses or do httpx library do that for us?

**Comment by tomchristie** [comment]
> Does httpx.Client() use of one connection for multiple parallel requests or it connects multiple times?

Yes. HTTPX deals with connection pooling for you.

> If it is possible to send multiple parallel requests through one connection, do we need to handle the number of requests manually when we send a huge number of requests (e.g. 1000) - that we do not reach the limit of requests per connection. What I mean is do we need to send let say 100 requests and then wait for responses or do httpx library do that for us?

Right now it won't limit the number of requests available per HTTP/2 connection, no. I'm not clear what the preferred behavior would be here. (Eg. we could *either* open up multiple HTTP/2 connections per origin in that case if we wanted, *or* we could block until the requests-per-connection limit is hit.) Does HTTP/2 have any specific rules around limits here, or rules around servers informing clients about appropriate limits?

**Comment by tomchristie** [comment]
> I don't think HTTPX handles that case?

Correct - It doesn't yet handle that, no.

**Comment by tomchristie** [comment]
Closing the question now that we have relevant issues to track it.

**Comment by PrimozGodec** [comment]
@tomchristie and @sethmlarson thank you for great and fast response.
