### ISSUE TITLE
RDNS parameter support for SOCKS proxies (socks4h/socks5h) 

### ISSUE THREAD

**Issue by nsde** [encode/httpx#2814]
### Discussed in https://github.com/encode/httpx/discussions/2812

<div type='discussions-op-text'>

<sup>Originally posted by **nsde** August  2, 2023</sup>
E.g. in python-requests, I'd use `socks5h://`...
Is there any way I can do that using `httpx`?

I tried resolving just the IP itself and adding the Host header, but this gave me issues for Cloudflare servers and is a really insecure workaround.

Can anyone help me, please?</div>

**Comment by tomchristie** [comment]
*Manager hat on*... let's not open issues until we've had a resolution on the discussion. 😇
