### ISSUE TITLE
Pin CalVer releases to a minimum date per HTTPX release

### ISSUE THREAD

**Issue by sethmlarson** [encode/httpx#285]
Currently if you upgrade HTTPX via `python -m pip install -U httpx` you won't get an upgrade of `hstspreload` if it's already been installed. This isn't great for users as they're likely to not want to upgrade each dependency individually.

We want users to get the latest versions of these types of dependencies (certifi is another). What are our thoughts on adding a `>=2019.8.20` (or whatever the latest version is on the day of release for that requirement). This could be done via an automated process and would be a good step towards automating our deployments to PyPI with Travis and tags.

**Comment by tomchristie** [comment]
Current releases have this covered now:

https://github.com/encode/httpx/blob/67d96b6522db689a51066897832e6c580b5c580d/setup.py#L57

Assuming it's okay to close this off. Good call on the issue, @sethmlarson!
