### ISSUE TITLE
Don't always encode forward slashes as `%2F` in query parameters

### ISSUE THREAD

**Issue by scnerd** [encode/httpx#2864]
#2723 Transitions to encoding "/" as "%2F" in the query; the argument is that this is "more correct" and more inline with browsers' default behavior.

The problem is that some API's simply reject this; for them, the two encodings are not identical. [A comment](https://github.com/encode/httpx/issues/2721#issuecomment-1732273653) on #2721 remarks that the OpenAI API expects actual slashes. I'm dealing with a private backend (that I don't control) that likewise expects actual slashes.

This new behavior should be possible to opt out of.

**Comment by thetanz-geoff** [comment]
@scnerd: This is raised in discussions (per the rules: "Please only raise an issue if you've been advised to do so after discussion.") here:
https://github.com/encode/httpx/discussions/2856
https://github.com/encode/httpx/discussions/2863

Suggest you keep an eye on all 3 threads for a response, and downgrade to 0.24.1 in the interim.
