### ISSUE TITLE
Support httpcore >= 1.0.0

### ISSUE THREAD

**Issue by paulschreiber** [encode/httpx#2884]
Please add support for httpcore >= 1.0.0, which was released last week.

Currently, installs fail like so:
```
The conflict is caused by:
    The user requested httpcore==1.0.0
    httpx 0.25.0 depends on httpcore<0.19.0 and >=0.18.0
```

**Comment by kloczek** [comment]
+1

**Comment by kloczek** [comment]
It causes issues on build some other modules. Below is from `openapi-core` build log:
```console
Error:
 Problem: conflicting requests
  - nothing provides (python3.8dist(httpcore) < 0.19 with python3.8dist(httpcore) >= 0.18) needed by python-httpx-0.25.0-2.noarch from g2v
```

**Comment by paulschreiber** [comment]
@tomchristie it's not causing any problems right now. dependabot tried to upgrade httpcore, but failed because of the httpx version restriction.

**Comment by StevenMapes** [comment]
Whilst it's not causing a problem it would be nice to test the package with httpcore 1.0.0 and to increase the version restriction as 1.0.0 made async support optional as well as adding in support for Python 3.12
