### ISSUE TITLE
Support brotlicffi in tests

### ISSUE THREAD

**Issue by mgorny** [encode/httpx#2906]
While the package itself can work with either `brotli` or `brotlicffi`, `tests/test_decoders.py` explicitly requires `brotli`. We're currently working on having all packages support `brotlicffi` in Gentoo, since `brotli` doesn't work reliably on PyPy3. Could you please consider making the test accept `brotlicffi` as well?

I suppose the simplest way would be to reuse the existing logic, i.e.:

    from httpx._compat import brotli

I can submit a PR for that.

---

- [x] Initially raised as discussion #2903

**Comment by karpetrosyan** [comment]
> I can submit a PR for that.

Yes, that would be great!

**Comment by tomchristie** [comment]
Alternate options:

* We could just always `brotlicffi` in the tests instead of `brotli`. (Because we value platform independence over c-performance here.)
* We don't actually need the `brotli` dependency in the tests at all, so we could drop it outright. We only use it on 3 lines, each of which we can replace using the byte encoding directly...

```python
-    compressed_body = brotli.compress(body)
+    compressed_body = b"\x8b\x03\x80test 123\x03"
```

```python
-    body = b"test 123"
-    compressed_body = brotli.compress(body)[3:]
+    compressed_body = b"invalid"
```

**Comment by mgorny** [comment]
>     * We could just always `brotlicffi` in the tests instead of `brotli`. (Because we value platform independence over c-performance here.)

That would work for us since we care about `brotlicffi` only but I think it'd be better to match the implementation used by `httpx`  in the more general case.

>     * We don't actually need the `brotli` dependency in the tests at all, so we could drop it outright. We only use it on 3 lines, each of which we can replace using the byte encoding directly...

Yeah, that would work for me.

Please let me know which approach you prefer and I can do it.

**Comment by tomchristie** [comment]
> Please let me know which approach you prefer and I can do it.

I'd suggest the second.
