### ISSUE TITLE
Fix `httpcore>=0.17.2` for lastest httpx version

### ISSUE THREAD

**Issue by wenceslas-sanchez** [encode/httpx#2934]
Discussed https://github.com/encode/httpx/discussions/2930

It seems the latest httpx version aris not compatible with all `httpcore` version. But in the [pyproject.toml](https://github.com/encode/httpx/blob/master/pyproject.toml) the `httpcore` version is not bounded.

After testing, it seems that the minimal compatible version of `httpcore` with httpx>=0.25.1 is `0.17.2`.

What do you think ?

**Comment by tomchristie** [comment]
From the discussion... I think the version requirement here should be `httpcore==1.*`.

**Comment by wenceslas-sanchez** [comment]
I would also prefer to set `1.*` but isn't it too restrictive since some older versions of botocore are also compatible ?

**Comment by tomchristie** [comment]
It's okay for us to be slightly overly restrictive here, there's no reason we shouldn't force a 1.* minimum version.

**Comment by wenceslas-sanchez** [comment]
Okay understood !

**Comment by tomchristie** [comment]
Closed via #2937

**Comment by ramnes** [comment]
@tomchristie this fix probably needs a release, people are getting errors due to the lack of restriction in 0.25.1: https://github.com/ramnes/notion-sdk-py/issues/213
