### ISSUE TITLE
Send http request but try tls protocol upgrade

### ISSUE THREAD

**Issue by goshut** [encode/httpx#3089]
When I use httpx to send http requests, it attempts to upgrade to the tls protocol.
I encountered an error while using the following code

```python
import requests
import httpx

url = "http://test.952918451.workers.dev"  # When using HTTPS TLS connection, it will be blocked by the GFW
headers = {
    "Accept": "application/json, text/javascript, */*; q=0.01",
    "Accept-Encoding": "gzip, deflate, br",
    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "Host": "test.952918451.workers.dev",
}
res = httpx.get(url, headers=headers)
print(res.status_code, res.text)
# res = requests.get(url, headers=headers)
# print(res.status_code, res.text)

```

```c
File "C:\Users\zhong\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\python\virtualenv\OCR\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore._exceptions.ConnectError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
```

This is caused by being intercepted by GFW.

I analyzed this phenomenon through packet capturing

<img width="942" alt="屏幕截图 2024-02-05 052137" src="https://github.com/encode/httpx/assets/45934628/6b7e4e38-6dd9-4bec-a9a0-7c0b59ff85cf">

It can be observed that it immediately attempts to upgrade the current TCP to TLS after receiving a reply from the server's syn, but I am using a URL format like HTTP.

In order to eliminate other interference, I used requests to send this request again, and everything was normal, indicating that there was no problem with the network.

**Comment by goshut** [comment]
This is the socket behavior when I send a request using Requests

![屏幕截图(32)](https://github.com/encode/httpx/assets/45934628/939ebafd-d18f-46ae-ae2e-765456834915)


It can be seen that it is a request sent to port 80, while httpx is 443. Why is this happening? How should HTTPX send a request to port 80 of the server? How to write a URL?

**Comment by goshut** [comment]
I have tried more situations, and at other times, the notation "http://" works normally (sending requests to port 80), but only when encountering a domain name like "test.952918451.workers.dev", it will be treated differently by HTTPX

I am using this writing method now: URL="http://172.67.173.170"



### **So what other domain names are being treated differently? Is this planned?**

**Comment by tomchristie** [comment]
The behavior you're seeing isn't anything to do with `httpx`... presumably you're being blocked by the ungreat firewall.
