### ISSUE TITLE
Contributing guide - Release process

### ISSUE THREAD

**Issue by florimondmanca** [encode/httpx#313]
Inspired by #311, I had been thinking that it would be good for maintainers (at least personally) to document the versioning and release process: what operations to perform, in what order, with what requirements/permissions etc.

In other projects of mine I usually add a “Notes to maintainers” section to the contributing guide (maintainers are contributors as well, right?) with this kind of information.

Of course we wouldn’t include any sensitive information there, but rather document the steps so that anyone with the appropriate permissions can create a new version, push it to PyPI, and deploy the docs.

Thoughts on this @encode/httpx-maintainers?

**Comment by tomchristie** [comment]
Yes, 100%.

Related to this: I think I would like us to bring back the `scripts/...`, in whatever way works best so that `nox` supplements them, rather than replaces them.

(Eg. pushing a release should be `scripts/release` - then we know we've got a nice reproducible process, always.)

**Comment by florimondmanca** [comment]
Cool, so https://github.com/encode/httpx/issues/239 should get in first I suppose? :)

**Comment by tomchristie** [comment]
Yeah. We probably also want to look at if we actually need the `MANIFEST.in` - that's only be introduced since 0.7.1 - not clear to me what *exactly* changed vs. prior release process.
