### ISSUE TITLE
Deletion of non-existent keys from `Headers` should raise KeyError.

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#317]
Prompted by  #310

To replicate:

```python
headers = httpx.Headers()
del headers['DOES_NOT_EXIST']  # Should raise a KeyError, but doesn't
```

To resolve this issue we'll need to:

* Ensure that deletion of non-existant keys raises a KeyError.
* Ensure that we have a `.pop(key, default)` that we can use instead for removal without KeyErrors.
* Replace instances of `del headers[key]` in our codebase with `headers.pop(key, None)` where appropriate.

**Comment by gdhameeja** [comment]
I would like to work on this.

**Comment by sethmlarson** [comment]
Sounds good to me! :) Thanks!

You can start working on any issues without me assigning you, a comment in the issue should be enough to signal to others that you're working on it.
