### ISSUE TITLE
Away-from-origin redirects should add a new host header

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#318]
Prompted by #310

Away-from-origin redirects currently remove the `Host` header, without adding a new one.
I think we ought to be using `headers['Host'] = url.authority.encode("ascii")` instead of simply deleting the header.

**Comment by gdhameeja** [comment]
I would like to work on this.

**Comment by sethmlarson** [comment]
@gdhameeja Consider the task yours :) Thanks for taking this on!
