### ISSUE TITLE
 error: "HTTPError" has no attribute "response"  [attr-defined]

### ISSUE THREAD

**Issue by dazzag24** [encode/httpx#3277]
```
except httpx.HTTPError as exc:
            logger.error(
                f"Error response {exc.response.status_code} while requesting {exc.request.url!r}."
            )
```

Docs [show](https://www.python-httpx.org/quickstart/#response-status-codes) example using `exc.response.status_code`. 
This [issue](https://github.com/encode/httpx/issues/2157) makes me wonder if it should in fact be:
`exc.request.status_code`

Thanks

**Comment by tomchristie** [comment]
`exc.response.status_code` is correct.

**Comment by dazzag24** [comment]
Is there anything to help prevent the mypy typing error?

**Comment by tomchristie** [comment]
https://github.com/encode/httpx/discussions/2151 suggests this is resolved. Let's take any further discussion on this over there.

**Comment by dazzag24** [comment]
I would but #2151 is locked ;-)

[image: image.png]

**Comment by svm-zhang** [comment]
@dazzag24, I just encountered the same mypy error when I try to log the exception with both `exc.request.url` and `exc.response.status_code`, inside the `HTTPError` exception block. The code can be executable without problem.

I digged a little bit into [the source code](https://github.com/encode/httpx/blob/609df7ecc0f7cb10a1c998aa9c269bba77337c5f/httpx/_exceptions.py). The `HTTPError` class does only have the `request` attribute, although its child class `HTTPStatusError` has the `response` one. I think this is the reason why mypy complains while the code is still executable.

My solution is to capture two exception separately as shown in the [quick start on exception](https://www.python-httpx.org/quickstart/#exceptions).

I am not sure if you have solved the issue (which I would like to know). I did follow the #2151 ticket and think it was a slightly different problem.

**Comment by tomchristie** [comment]
> I just encountered the same mypy error when I try to log the exception with both exc.request.url and exc.response.status_code, inside the HTTPError exception block. The code can be executable without problem.

Yep. It'll execute okay, unless you get an exception such as connection failure. Then logging `exc.response.status_code`, will fail with an AttributeError, because there's no `response` associated with the exception. mypy is correctly highlighting that.

**Comment by svm-zhang** [comment]
@tomchristie Thanks for confirming it. If I may, I would suggest add one sentence in the doc saying this explicitly to avoid the confusion for someone like me :) Or perhaps simply add link to this ticket to the doc.
