### ISSUE TITLE
Missing requests' elapsed property on Response object. 

### ISSUE THREAD

**Issue by jaredcm** [encode/httpx#338]
The requests Response object has an elapsed property which returns a datetime.timedelta instance. This appears to be missing from the httpx Response.

A nice to have feature would be to break elapsed into more fine-grained timings similar to Firefox's web inspector (Blocked, DNS resolution, Connecting, TLS setup, Sending, Waiting and Receiving).

**Comment by rowillia** [comment]
I can take a crack at this!  This project looks super interesting and looking to get started.
