### ISSUE TITLE
Cleanup `_utils.py` functions. ✨🧹✨

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#3381]
Possibly a good issue for new contributors?...

The `_utils.py` module has a smorgasbord of utility functions. Many of these are only used in one place in `httpx` and it would be easier to comprehend if they were inlined, or refactored closer to where they're being used. ✨🧹✨

Pull requests for this should typically tackle one item at a time for easier review. 🤓

**Comment by RafaelWO** [comment]
I'm happy to take a look at this 🙂 

> Pull requests for this should typically tackle one item at a time for easier review

I'm not fully sure if I understand this correctly. Do you mean per function or per "topic"?

**Comment by tomchristie** [comment]
@RafaelWO Wonderful, thanks. 😊

> Do you mean per function or per "topic"?

Use your own judgement I guess, we can have a conversation if there's any awkward points.
As a guideline, simpler PRs tend to be more easily acceptable.

**Comment by RafaelWO** [comment]
@tomchristie I think we can close this as completed, correct? :slightly_smiling_face:

**Comment by tomchristie** [comment]
Complete enough for now, yep. ☺️
