### ISSUE TITLE
Drop-in replacement for `proxies` argument in (httpx.post)

### ISSUE THREAD

**Issue by qqaatw** [encode/httpx#3424]
Hi,

Since version `0.28`, the `proxies` argument is fully deprecated and removed. #2879 indicates that we should use `mounts` if we have multiple schemas to be proxied over. However, `httpx.post` doesn't have `mounts` argument.

Is there a way to

1. use the new `proxy` argument, specifying both `http` & `https` schemas?
2. add an argument `mounts` to `httpx.post` and relevant methods?

Thanks.

**Comment by Lroemon** [comment]
Removing an argument & doing a minor update is criminal. Lost all the day yesterday to figure out why opanai library was not working in the new build for the production environment...

**Comment by tomchristie** [comment]
Do you know what version range of httpx the openai client currently pinned against?

**Comment by tomchristie** [comment]
@qqaatw 👉 `client = httpx.Client()`

**Comment by qqaatw** [comment]
Can I please re-open the issue? I meant, is there a way not explicitly creating `Client()` and also able to use the functionality of the previous `proxies` argument?

**Comment by tomchristie** [comment]
> I meant, is there a way not explicitly creating Client() and also able to use the functionality of the previous proxies argument?

Appreciate the clear question.

There is not. You’ll need an explicit client instance to do that.

**Comment by ChillarAnand** [comment]
> Removing an argument & doing a minor update is criminal. Lost all the day yesterday to figure out why opanai library was not working in the new build for the production environment...

This was marked as deprecated in 0.26.0 version itself.

https://github.com/encode/httpx/releases/tag/0.26.0

**Comment by dgellow** [comment]
@Lroemon openai-python has been updated to support httpx v0.28.0 with the release [v1.55.3](https://github.com/openai/openai-python/pull/1905)
