### ISSUE TITLE
 from httpx._types import AuthTypes, CertTypes, CookieTypes, HeaderTypes, VerifyTypes ImportError: cannot import name 'VerifyTypes' from 'httpx._types' (/usr/local/lib/python3.11/site-packages/httpx/_types.py)

### ISSUE THREAD

**Issue by maryam123errami** [encode/httpx#3443]
I get an error when I try to build a Docker image. Can someone please help me? 
 from langserve import add_routes
  File "/usr/local/lib/python3.11/site-packages/langserve/__init__.py", line 8, in <module>
    from langserve.client import RemoteRunnable
  File "/usr/local/lib/python3.11/site-packages/langserve/client.py", line 24, in <module>
    from httpx._types import AuthTypes, CertTypes, CookieTypes, HeaderTypes, VerifyTypes
ImportError: cannot import name 'VerifyTypes' from 'httpx._types' (/usr/local/lib/python3.11/site-packages/httpx/_types.py)

langchain-community
psycopg2-binary
tenacity
scikit-learn
pydantic
fastapi
langchain_google_genai
httpx==0.27.2
langgraph
langserve
uvicorn
langchain
langchain-cli
langchain-core
langchain-openai==0.2.10

**Comment by tomchristie** [comment]
Hiya... could you follow this up with the langserve team? Thanks.

There're using a private import there, which isn't in the codebase in 0.28.0.
They can either switch that annotation to `bool | str | ssl.SSLContext`, or pin their `httpx` dependency.

**Comment by maryam123errami** [comment]
So should I contact langserve team
