### ISSUE TITLE
httpx.AsyncClient stream on different os, data different

### ISSUE THREAD

**Issue by H0nGzA1** [encode/httpx#3446]
on my mac m1 pro python3.9.6

<img width="1959" alt="image" src="https://github.com/user-attachments/assets/f2079c36-e178-433a-be4b-eabbd0602a3c">

on my local ubuntu python3.11
<img width="1959" alt="image" src="https://github.com/user-attachments/assets/92a0f796-8aa9-4f0b-8bfa-6cce6f160ddb">

also test in centos , docker container，only on my mac，data can be correct parse，why?

**Comment by GreyElaina** [comment]
The images seems to be the same one, check?
