### ISSUE TITLE
Does detection of lost connections implicitly depend on asyncio?

### ISSUE THREAD

**Issue by florimondmanca** [encode/httpx#346]
I'm mostly opening this to track the issue — I'll try to tackle this based on the trio backend in #276, and see what could work, e.g. setting up a background task to check for socket readability.

Worth mentioning though that [anyio already seems to handle this quite well](https://anyio.readthedocs.io/en/latest/api.html#anyio.wait_socket_readable).

---

The `Stream` interface exposes a `is_connection_dropped()` method which the `ConnectionPool` uses to know whether it can reuse a connection when acquiring a new one.

https://github.com/encode/httpx/blob/f1dde95d358a5a707d75e6d61f912224ed65ee8e/httpx/dispatch/connection_pool.py#L130-L139

Also noted by @njsmith in https://github.com/encode/httpx/pull/276#discussion_r322000402:

> asyncio always keeps reading from the socket in the background, whether you call read or not, as long as the loop is running. Trio and sync code don't. Unfortunately, httpx currently relies on the asyncio behavior to detect when an idle connection has gone stale. IMO this is a bug in httpx's idle connection handling, but that's the current state [...].

Also in https://github.com/encode/httpx/pull/276#discussion_r322004378:

>  [A]rguably it's a bug that when we want to detect if a connection is reusable, then the asyncio backend checks for EOF, when ideally it should be checking for readability. 

Indeed, that's what we do:

https://github.com/encode/httpx/blob/f1dde95d358a5a707d75e6d61f912224ed65ee8e/httpx/concurrency/asyncio.py#L124-L125

There was an entire discussion about readable vs closed before, see for example https://github.com/encode/httpx/pull/143#issuecomment-515181778. Counter-intuitively, it seems that when the other end has closed the conection then a socket is said to be *readable* (`.recv()` would return immediately with `b""`).

I guess the tl;dr here is that the way we implement `.is_connection_closed()` for asyncio is *good enough* (if the socket was closed, asyncio's background socket checker will mark at as having reached EOF), but we *might* need to change the way we check for dropped connections.

**Comment by florimondmanca** [comment]
It seems I tangled myself up on the previous discussions and the counter-intuitive notion of *readability*. As I said, in the asyncio case checking for EOF is *good enough*, because a socket that reached EOF in the sense of asyncio is also readable (right?). So the code might just need some comments, which I added in https://github.com/encode/httpx/pull/276/commits/c5427357fa568e1571ec2d17a4d16298adf3de6e.

Provided my understanding of these subtle notions is correct (i.e. if a socket is readable then the connection was dropped), the implementation in #276 should be correct, so I'll close this since there doesn't turn out to be any immediate issue with our asyncio implementation.

**Comment by njsmith** [comment]
Yeah, the current way of detecting stale connections on asyncio isn't *optimal*, in the sense that it will occasionally think a connection is ok when it's actually been closed by the server. But it's just a bug in that backend, that doesn't affect other backends, and the impact is just that this heuristic is a bit less reliable than it could be.

In particular, this thing that I said and you quoted is wrong, and I retracted it later in the original thread:

> Unfortunately, httpx currently relies on the asyncio behavior

**Comment by florimondmanca** [comment]
Yes, I think I understand that there’s actually not really a dependency there. Thanks for clarifying!
