### ISSUE TITLE
Close all outstanding responses on client close

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#35]
Client close currently [closes off any keep-alive connections](https://github.com/encode/httpx/blob/master/httpx/dispatch/connection_pool.py#L171).
Actually the behavior would be more neatly bounded if we forcibly close off *all* connections.

```python
with SyncClient() as client:
    response = client.get(..., stream=True)
response.read()  # This should raise an error.
```

**Comment by jhtimmins** [comment]
@florimondmanca is this still up for grabs? And if so, would it make a good first issue?

**Comment by florimondmanca** [comment]
Hi @jhtimmins! There's already a PR for this over at https://github.com/encode/httpx/pull/322, but unfortunately it seems to have slipped through.

So feel free to take it up. I don't think the fix will be trivial, but you can take a crack at it and see where you end up. :)

**Comment by jhtimmins** [comment]
Thanks @florimondmanca! Sounds great. I'll do that.

**Comment by tomchristie** [comment]
Obsoleted by the more tightly bounded `stream()` API. (Which ensures that connections can only be held open within a `stream()` context block)
