### ISSUE TITLE
Change trustme.CA() usage to mimic real-life

### ISSUE THREAD

**Issue by sethmlarson** [encode/httpx#354]
We need to change our usage of `trustme.CA()` to allow doing TLS verifications within the unit test suite.

What this would look like:
- Global level `CA` object
- Fixture for an issued cert
- The private key and public PEM `.tempfile()` calls for these two components
- Switch the `https_server` instance to use the issued private key and public PEM.
- Switch all HTTPS tests to use the CA's PEM (not the issued PEM) as `verify=...`

We shouldn't be using verify=False within the test suite unless we're testing that specific behavior.

**Comment by JayH5** [comment]
@sethmlarson this looks (hopefully) straightforward. I can give it a go as my first issue if you like?

**Comment by sethmlarson** [comment]
That would be awesome! Reach out if you run into any roadblocks or have questions. :)
