### ISSUE TITLE
Add a new backend to be tested with asyncio+uvloop

### ISSUE THREAD

**Issue by sethmlarson** [encode/httpx#355]
Since we have the niceness of multiple backends getting tested in our test suite it'd be nice to add asyncio+uvloop to the list to ensure compatibility.

**Comment by gdhameeja** [comment]
I'd like to work on this.

**Comment by tomchristie** [comment]
I think this would bring extra gumpf, without adding benefit.
uvloop (or any other loop policy) ought to be completely transparent to use from the POV of  `httpx`.
Would you be okay with us dropping this?

**Comment by sethmlarson** [comment]
The reason I wanted to add the case is uvloop is independent of Python so is free to add features that are in asyncio for Python 3.8 but it's still installable on Python 3.6 like .start_tls(), singular Stream interface, etc.

**Comment by tomchristie** [comment]
Presumably that's still transparent to us right? (Or not?)
uvloop doesn't document any extra interfaces that it makes available, other than just setting the loop policy.

**Comment by sethmlarson** [comment]
We look for [`start_tls()`](https://github.com/MagicStack/uvloop/blob/46c5e9ebe45c7d5aa8777ad1add6656e349528ab/uvloop/loop.pyx#L1492) opportunistically on the loop interface within the HTTP proxy for tunneling TLS.

Available for Python 3.7+ or Python 3.6+ uvloop.

**Comment by tomchristie** [comment]
If it works with 3.7+ then I'm okay that we've tested it.
