### ISSUE TITLE
Should `BaseTCPStream.is_connection_dropped` be async?

### ISSUE THREAD

**Issue by rowillia** [encode/httpx#356]
Looking at the urllib3 implementation of `is_connection_dropped` (https://github.com/urllib3/urllib3/blob/f7a4bed04085975918b3469bf94e195df9faf29a/src/urllib3/util/connection.py#L7-L26) it looks like their (pretty robust and battle tested 😄) implementation will sometimes block when testing if a connection is dropped (eventually calls into https://github.com/urllib3/urllib3/blob/f7a4bed04085975918b3469bf94e195df9faf29a/src/urllib3/util/wait.py#L105).

It looks like https://github.com/encode/httpx/issues/346 was closed, deciding the current implementation is good enough for now with some great research, but it sounds like you may want to improve this API in the future in a way that might require blocking.  Given you're pre-1.0 it would be good to get the APIs solid on what can eventually be async before 1.0 so you can more easily use a blocking implementation in the future.

I'm new here and just poking around so please LMK if there's any context I'm missing!

**Comment by florimondmanca** [comment]
Interesting point! The fact that [trio.hazmat.wait_readable() is async too](https://trio.readthedocs.io/en/stable/reference-hazmat.html#trio.hazmat.wait_readable) seems to support this. :)

> I'm new here and just poking around

Please do! Questions and suggestions from fresh eyes are invaluable. 🙌

**Comment by sethmlarson** [comment]
Deferring these changes until we need them, thanks @rowillia! :heart:
