### ISSUE TITLE
Releasing 0.7.3

### ISSUE THREAD

**Issue by florimondmanca** [encode/httpx#359]
Hi @encode/httpx-maintainers!

It’s been 21 days since 0.7.2 was released, and we’ve got [a bunch of features](https://github.com/encode/httpx/compare/0.7.2...HEAD) ready for 0.7.3 already, eg:

- Digest auth
- SSLKEYLOGFILE
- Response.elapsed
- A host of bug fixes

So regardless of what gets merged until then I think it’s time to release the next version. :)

As suggested by @sethmlarson I-cant-remember-where I’d like to take on this release. I’ll probably take the opportunity to document the release process as well - #313. 👍

Probably will do tonight.

**Comment by sethmlarson** [comment]
Yep, definitely time to release. Maybe I'll try to get the proxy config PR in before but if not it's fine to ship without. :)

**Comment by florimondmanca** [comment]
Yes, it can make it in 0.7.4 too. :)

I was wondering — what’s the policy for minor bumps? Breaking changes I guess?

**Comment by sethmlarson** [comment]
I guess so? There aren't any API guarantees for 0.X under SemVer though.

**Comment by sethmlarson** [comment]
@florimondmanca FYI I added you to the PyPI project along with @yeraydiazdiaz. Didn't realize I was an Owner! :)
