### ISSUE TITLE
Add support for the NO_PROXY environment variable

### ISSUE THREAD

**Issue by sethmlarson** [encode/httpx#360]
The `NO_PROXY` environment variable is described here:

- http://www.gnu.org/software/wget/manual/html_node/Proxies.html
- https://github.com/psf/requests/blob/840540b6b1f07ef87faab73392c03fbef0dcc9fe/requests/utils.py#L395

In order to accomplish this task we'd need:
- Implementing NO_PROXY, a list of hosts that will bypass the proxy if found within the list.
- Only enabled if `trust_env=True`
- Documentation updates for the new environment variable.
- Test cases for all code branches.

**Comment by elwinmartin** [comment]
@sethmlarson Hi Seth! 

I would love to work on this if I could! 

I'm mostly familiar with this library as a user but I think the context provided should be clear enough to adapt this for httpx.

**Comment by sethmlarson** [comment]
That would be awesome!! I'll assign the issue to you :)

If you have questions or doubts feel free to reach out here and we'll try our best to help.

**Comment by tomchristie** [comment]
Looks good.
Related to #404. I wonder if [cURL would be a good baseline set of environment variables](https://curl.haxx.se/libcurl/c/libcurl-env.html) to adhere too? That's probably more robust and mature than any other tooling out there, so I'd be okay with us *explicitly* following their lead.

**Comment by mariaS210** [comment]
@sethmlarson hello! is someone working on this? if not, i'd like to try it

**Comment by florimondmanca** [comment]
Feel free to go ahead @mariaS210! 🎉

**Comment by yeraydiazdiaz** [comment]
Closed via https://github.com/encode/httpx/pull/471

**Comment by tomchristie** [comment]
Reopening this, since it's evidently been closed in error - #471 adds `NO_PROXY` handling utility functions, but doesn't tie it in to the client.

**Comment by pawamoy** [comment]
Is there another way to bypass the proxies while waiting for `NO_PROXY` to be tied into the client?

**Comment by tomchristie** [comment]
You can use `trust_env=False` to disable system proxies.

https://www.python-httpx.org/environment_variables/

**Comment by evanlurvey** [comment]
I have addressed this in https://github.com/encode/httpx/pull/835

**Comment by evanlurvey** [comment]
@florimondmanca Would you want to close this issue now?
