### ISSUE TITLE
Query params should support list-of-strings values.

### ISSUE THREAD

**Issue by Senpos** [encode/httpx#366]
Hi,

I recently tried to use `httpx` instead of `requests` in my simple app that calls few API endpoints and  suddenly it did not work.

The problem here is that `httpx` and `requests` process query parameters differently.

Here's a simple script to see how both libraries process `params`:
```python
from httpx.models import QueryParams
from requests.models import RequestEncodingMixin

dict_params = {
    "documentIds": ["a55b2f894b90dd1213201471_25", "b54b2f894b90dd1213201471_9"]
}

httpx_params = str(QueryParams(dict_params))
print("httpx", httpx_params)

requests_params = RequestEncodingMixin._encode_params(dict_params)
print("requests", requests_params)
```

Results:
```
httpx documentIds=%5B%27a55b2f894b90dd1213201471_25%27%2C+%27b54b2f894b90dd1213201471_9%27%5D
requests documentIds=a55b2f894b90dd1213201471_25&documentIds=b54b2f894b90dd1213201471_9
```

If we try to parse the query string `httpx` produced, here's what we get:
```python
from urllib.parse import parse_qs

httpx_params_parsed = parse_qs('documentIds=%5B%27a55b2f894b90dd1213201471_25%27%2C+%27b54b2f894b90dd1213201471_9%27%5D')
print(httpx_params_parsed )
```
Result:
```
{'documentIds': ["['a55b2f894b90dd1213201471_25', 'b54b2f894b90dd1213201471_9']"]}
```
Which is not what you would expect, I guess. At least, it works differently than in `requests`.

If it is an intended behavior, can you please recommend me the proper way of passing a list into the query params?

Thanks!

**Comment by Senpos** [comment]
Here's a bit more "live" example:
```python
import httpx
import requests

params = {"documentIds": ["a55b2f894b90dd1213201471_25", "b54b2f894b90dd1213201471_9"]}

URL = "https://httpbin.org/get"
r = requests.get(URL, params=params)
print("requests", r.json()["args"])

r = httpx.get(URL, params=params)
print("httpx", r.json()["args"])


```

Results:
```
requests {'documentIds': ['a55b2f894b90dd1213201471_25', 'b54b2f894b90dd1213201471_9']}
httpx {'documentIds': "['a55b2f894b90dd1213201471_25', 'b54b2f894b90dd1213201471_9']"}
```

**Comment by florimondmanca** [comment]
Hi @Senpos! Thank you for reporting this.

I can confirm this is a bug: multivalued query params are encoded in the form of a Python list. I discovered it in #298 but didn't think about open an issue:

https://github.com/encode/httpx/blob/39348dd969a8900b682921566456342881ce396f/tests/compat/test_requests.py#L1006-L1019

**Comment by sethmlarson** [comment]
We should look at adding some requests compatibility tests for this if they exist. :)

**Comment by tomchristie** [comment]
Thanks for opening the issue!
Retitled to make this more clearly specific.
