### ISSUE TITLE
HTTPError should be importable frop the top-level httpx package

### ISSUE THREAD

**Issue by florimondmanca** [encode/httpx#367]
From #365:

> `HTTPError` is not available at the top level like the other exceptions and like it was in requests. This is a somewhat common exception to catch raise_for_status, so having to add another import statement for it is a bit odd if intentional.

Put differently, `HTTPError` is missing from `httpx/__init__.py`. Adding it would allow us to do:

```python
import httpx

try:
    r = httpx.get("https://example.org")
    r.raise_for_status()
except httpx.HTTPError:
    ...
```

**Comment by gdhameeja** [comment]
I'd like to work on this.

**Comment by sethmlarson** [comment]
The issue is yours! Thanks @gdhameeja
