### ISSUE TITLE
Disallow setting Cookies on domains suffixes on the Public Suffix List

### ISSUE THREAD

**Issue by sethmlarson** [encode/httpx#370]
This feature prevents putting a cookie on a domain prefix that multiple parties are capable of registering sub-domains with.

Public Suffix List: https://publicsuffix.org

There are two libraries in existence already (`publicsuffix` and `publicsuffixlist`) however they both are in the same boat of not providing a sans-I/O way of updating the list when it's too old and also don't update their pre-packaged list very often.

My proposed solution is to create a library with automated deployments similar to `hstspreload` and then also providing a mechanism that any HTTP library can update the packaged list via their own fetching mechanism.

**Comment by sethmlarson** [comment]
The "psl" package has been published to PyPI.  After a successful automated deploy I'll be moving the package under the python-http org.

GitHub: https://github.com/sethmlarson/psl
PyPI: https://pypi.org/project/psl

**Comment by tomchristie** [comment]
Okay, that's interesting.
Not entirely obvious to me that we need to treat this as a requirement, but possibly.
