### ISSUE TITLE
Prepare for Hacktoberfest

### ISSUE THREAD

**Issue by sethmlarson** [encode/httpx#385]
Information:
- https://hacktoberfest.digitalocean.com/details
```
Recommendations for creating a good Hacktoberfest issue in your project:

● Apply the "Hacktoberfest" label to issues in your GitHub project that are ready for new contributors to work on.
● Add a CONTRIBUTING.md file with contribution guidelines to your repo.
● Choose issues that have a well-defined scope and are self-contained.
● Adopt a code of conduct to foster a greater sense of inclusion and community.
```

- [x] We should complete  #311 
- [x] Make sure all the issues within our tracker have enough scope to them for new contributors   to be able to pick them up and run with them.
- [x] We should also get our coverage to 100% and then merge #380.
- [x] Hacktoberfest labels for issues that we believe can be taken up
- [x] Create new issues that we need to complete that aren't in our tracker yet
- [x] Write one (or more!) blog post(s) on DEV using the `#hacktoberfest` tag. See also the [Hacktoberfest introduction post](https://dev.to/devteam/hacktoberfest-starts-in-six-days-3hi2) on DEV.

**Comment by florimondmanca** [comment]
Hacktoberfest is co-presented by DEV this year. They’ve got a special #hacktoberfest hashtag and will be promoting it as well, probably on site and on Twitter. [Source](https://dev.to/devteam/hacktoberfest-starts-in-six-days-3hi2)

I think it can be a cool idea to post something about HTTPXand a recap of our Hacktoberfest-friendly issues there! I will gladly take that up.

**Comment by sethmlarson** [comment]
That's an awesome idea, I've been wanting to write a blog post about HTTPX on my DEV account too about what sets it apart. :)

Do you want to add an item to my list for the blog post?

**Comment by sethmlarson** [comment]
Coverage is at ~100%, or as close as we're going to get with our current setup. Reviewers should check codecov until the reports are showing up in PRs.

**Comment by sethmlarson** [comment]
Removing the Hacktoberfest label to not confuse outside contributors.

**Comment by SatoshiNakamotogmx** [comment]
Lol got me debating to help with that title lol

**Comment by florimondmanca** [comment]
A first DEV post on HTTPX + Hacktoberfest has been published here:

[HTTPX: Help Build The Future Of Python HTTP](https://dev.to/florimondmanca/httpx-for-hacktoberfest-help-build-the-future-of-python-http-16pj)

**Comment by thebigmunch** [comment]
So, for my first Hacktoberfest PR, I submitted httpx to the [awesome-python](https://github.com/vinta/awesome-python) list. The template suggests that it needs some number of 👍 emotes to be added. So, if people would be so kind as to go to the [pull request](https://github.com/vinta/awesome-python/pull/1381) and give it a 👍, I'd love to see it added.

**Comment by florimondmanca** [comment]
Awesome, @thebigmunch!

**Comment by SatoshiNakamotogmx** [comment]
I'm rdy to get this going it's been 10 years since I have shown my face lol

**Comment by SatoshiNakamotogmx** [comment]
In la

**Comment by sethmlarson** [comment]
Gonna close this issue as we're in full swing. :)
