### ISSUE TITLE
HTTPProxy targetting IPv6 host via CONNECT tunnel is missing square braces around host

### ISSUE THREAD

**Issue by sethmlarson** [encode/httpx#392]
When I have an `httpx.HTTPProxy` configured and then make a request to an IPv6 host there are no square braces around the host component of the CONNECT target.

The request should look like this:
```
CONNECT [::1]:443 HTTP/1.1\r\n
```

Currently looks like this:
```
CONNECT ::1:443 HTTP/1.1\r\n
...
```

This issue required very similar functionality to #391 but requires a flag to say that the port should always be included even if it's the default port for the URL scheme.

**Comment by jcugat** [comment]
Hey @sethmlarson I was taking a look at this bug but I'm unable to reproduce it. I've taken as reference `test_proxy_tunnel_success` https://github.com/encode/httpx/blob/db3e3a0231538cfd4ebcec8a93906c05fc5b68a3/tests/dispatch/test_proxy_http.py#L8 and modified it to connect to an IPv6 host, and the CONNECT target has the square braces set (this test passes locally):

```py

async def test_proxy_tunnel_ipv6_correct_host(backend):
    raw_io = MockRawSocketBackend(
        data_to_send=(
            [
                b"HTTP/1.1 200 OK\r\n"
                b"Date: Sun, 10 Oct 2010 23:26:07 GMT\r\n"
                b"Server: proxy-server\r\n"
                b"\r\n",
                b"HTTP/1.1 404 Not Found\r\n"
                b"Date: Sun, 10 Oct 2010 23:26:07 GMT\r\n"
                b"Server: origin-server\r\n"
                b"\r\n",
            ]
        ),
        backend=backend,
    )
    async with httpx.HTTPProxy(
        proxy_url="http://127.0.0.1:8000",
        backend=raw_io,
        proxy_mode=httpx.HTTPProxyMode.TUNNEL_ONLY,
    ) as proxy:
        response = await proxy.request("GET", "https://[::1]")

        assert response.status_code == 404
        assert response.headers["Server"] == "origin-server"

        assert response.request.method == "GET"
        assert response.request.url == "https://[::1]"
        assert response.request.headers["Host"] == "[::1]"

    recv = raw_io.received_data
    assert len(recv) == 4
    assert recv[0] == b"--- CONNECT(127.0.0.1, 8000) ---"
    assert recv[1].startswith(
        b"CONNECT [::1]:443 HTTP/1.1\r\nhost: 127.0.0.1:8000\r\n"
    )
    assert recv[2] == b"--- START_TLS([::1]) ---"
    assert recv[3].startswith(b"GET / HTTP/1.1\r\nhost: [::1]\r\n")
```

Any idea what I'm missing to reproduce it?

**Comment by sethmlarson** [comment]
Hmm does that mean that `URL("https://[::1]:8080").origin` is `('https', '[::1]', 8080)`? Because that's not right either.

**Comment by jcugat** [comment]
Yes, this test passes:

```py

def test_url_origin_ipv6():
    url = URL("https://[::1]:8080")
    assert url.origin.scheme == 'https'
    assert url.origin.host == '[::1]'
    assert url.origin.port == 8080
```

What would be the correct output in this case?

**Comment by sethmlarson** [comment]
Nevermind I'm incorrect, the host is proper. Closing this issue, thanks for investigating!
