### ISSUE TITLE
More explicit documentation that `httpx.Client` is equivelent to `requests.Session`.

### ISSUE THREAD

**Issue by innawe** [encode/httpx#403]
This isn't an issue (sorry if i posted in a wrong place), but i read the httpx doc and didn't find yet a solution. 
In requests i use s = requests.session(), how can i do the same thing with httpx? 
it will be possible to do something like s = httpx.session()?
Thanks and sorry again.

**Comment by florimondmanca** [comment]
Hi @innawe, the equivalent of Requests' `Session` in HTTPX is the `Client` (or `AsyncClient` for async usage).

You can learn more here: [Client instances](https://www.encode.io/httpx/advanced/#client-instances). Let us know if the docs aren't giving enough details

**Comment by tomchristie** [comment]
I think the core issue here is that our "[Requests Compat Guide](https://www.encode.io/httpx/compatibility/)" doesn't yet make that explicit.

We could also have an [explicit callout in the advanced usage](https://www.encode.io/httpx/advanced/#client-instances), that Client is an equivelent to requests's Session.

**Comment by jtmiclat** [comment]
Hi, I am interested in tackling this!

**Comment by surfer190** [comment]
It's jsut when you come from a `requests` way of doing things and venacular you tend to search for the word `session` both in the borwser find and in the doc's search bar.

You will find nothing of relevance.

Lets us add an explicit line that the equavalent of `requests.Session` in `httpx` is:

`httpx.AsyncClient()`
