### ISSUE TITLE
Environment Variables docs should justify each usage case.

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#404]
Our [environment variable documentation](https://www.encode.io/httpx/environment_variables/) should include some justification or context for each case, by doing one of the following for each envvar:

* Make it clear that an environment variable is specific to HTTPX. (Probably only relevant to anything prefixed by `HTTPX_`)
* Make it clear that an environment variable is used as a convention by various tooling, with at least one relevant hyperlink.

Eg.

`SSLKEYLOGFILE` could give some more context about usage - "The keylog file is designed for debugging purposes only." doesn't make it clear how or when to use it, or which debug tooling it's usful with.

`SSL_CERT_FILE` and `SSL_CERT_DIR` can include a link to some docs about their convention. Perhaps give an example of other tooling that supports them? 

`HTTP_PROXY`, `HTTPS_PROXY`, `ALL_PROXY` can include a link to some docs about their convention. Perhaps give an example of other tooling that supports them?

**Comment by anshulxyz** [comment]
Hi @sethmlarson and @tomchristie I'd like to work on this

**Comment by mwoss** [comment]
May I take over it?

**Comment by tomchristie** [comment]
We'll happily take any contributions here yup.

**Comment by mwoss** [comment]
Ok, I will take care of it tommorow or on Friday.

**Comment by cwkang1998** [comment]
Is this task done? Does it still need help working on?

**Comment by tomchristie** [comment]
I don't think there's anything worthwhile doing here, nope.
