### ISSUE TITLE
Revert PR #369

### ISSUE THREAD

**Issue by sethmlarson** [encode/httpx#420]
See: https://github.com/encode/httpx/pull/369

This is currently failing our CI on Python 3.8 which was just released. While we're at it we can switch to 3.8 on Travis instead of 3.8-dev

**Comment by florimondmanca** [comment]
Funny — I thought I opened an issue for this this morning. Guess I forgot to press the send button? 😅 Thanks for tracking this!

**Comment by tomchristie** [comment]
Thought for the future: We ought mark any `-dev` Python builds as "allowed failure" given that API can change under our feet, until there's a fixed release to work against.

Somewhat surprised to see such a big API change land without warning, immediatly prior to the release candidate release, but there we go.
