### ISSUE TITLE
Hacktober

### ISSUE THREAD

**Issue by jaKass3** [encode/httpx#429]

**Comment by florimondmanca** [comment]
Hi @jaKass3, not sure what this issue is about? Closing now, if you have anything else to report feel free to open a new issue.

**Comment by thebigmunch** [comment]
I hope the maintainers have noticed this user spamming invalid PRs and issues to the repo to get Hacktoberfest credit. If not done already, those should be reported as spam, so they don't get credit. And the user should probably be blocked.

**Comment by yeraydiazdiaz** [comment]
Yep, we've noticed and taking action 👍

**Comment by pquentin** [comment]
@yeraydiazdiaz Don't forget to add the "invalid" label, closing isn't enough to avoid Hacktoberfest credits.

**Comment by tomchristie** [comment]
Thanks, yup. Organisation-wide blocked and reported as a troll account.
