### ISSUE TITLE
Releases to PyPI should also contain wheels

### ISSUE THREAD

**Issue by graingert** [encode/httpx#432]
This allows tools to safely parse package metadata without executing `setup.py`

**Comment by florimondmanca** [comment]
Oh, are we only shipping a source distribution right now? This sounds like a nice improvement to me.

I suppose only the `scripts/publish` would need to be modified to also build and ship the wheel with `twine`. :)

**Comment by florimondmanca** [comment]
I edited the title to more explicitly state the problem at hand. Thanks for opening!

**Comment by graingert** [comment]
is there a reason to ship the sdist?
