### ISSUE TITLE
Document how to fine-tune timeout configuration

### ISSUE THREAD

**Issue by florimondmanca** [encode/httpx#434]
Motivated by https://github.com/encode/httpx/issues/411

The current [documentation on timeout](https://www.encode.io/httpx/quickstart/#timeouts) featured in the quickstart is a bit scarce: it only shows how to override all timeouts using a float value.

We should document:

- How to fine-tune connect, read and write timeouts using `httpx.TimeoutConfig(connect=..., read=..., write=...)`.
- How to disable timeouts. (Related: #433)

Examples should ideally show how to do this on the top-level API (`httpx.(timeout=...)`) and on a client (`httpx.Client(timeout=...)`, `client.get(timeout=...)`.

To avoid clutter in the quickstart guide, this information should land in a new section in the [Advanced Usage](https://www.encode.io/httpx/advanced/) section (e.g. "Timeout fine-tuning"), and we should link to it from the timeout quickstart.

**Comment by gdhameeja** [comment]
I'd like to work on this.

**Comment by mwoss** [comment]
@gdhameeja are you working on this issue or could I take over it?

**Comment by sethmlarson** [comment]
@mwoss You can take this issue I think. :)

**Comment by florimondmanca** [comment]
Closed by #476.
