### ISSUE TITLE
Fine-tuning timeouts from the default timeout config

### ISSUE THREAD

**Issue by florimondmanca** [encode/httpx#435]
Currently, if we want to change only one of the three timeouts (connect, read, write) we need to build a full-blown `TimeoutConfig`. But there is no way to use the default timeout values.

```python
>>> import httpx
>>> httpx.config.DEFAULT_TIMEOUT_CONFIG
TimeoutConfig(timeout=5.0)
>>> httpx.TimeoutConfig(read_timeout=1)
# We'd expect connect_timeout and write_timeout to be 5 (the default)
TimeoutConfig(connect_timeout=None, read_timeout=1, write_timeout=None)
```

Changing `TimeoutConfig` to automatically use the default values in case some values aren't given is probably not the good way to go, because `TimeoutConfig` shouldn't contain any smart behavior.

Instead, we should probably allow explicitly building a `TimeoutConfig` instance from `DEFAULT_TIMEOUT_CONFIG`:

I'd see it materialize as factory method on `TimeoutConfig`:

```python
>>> httpx.TimeoutConfig.from_defaults(read_timeout=1)
TimeoutConfig(connect_timeout=5, read_timeout=1, write_timeout=5)
```

Does this sound reasonable @tomchristie?

**Comment by sethmlarson** [comment]
What about making `TimeoutConfig(read_timeout=1)` result in 5, 1, 5 instead of None, 1, None? Then you have to be explicit about the other two if you truly want "None".

**Comment by tomchristie** [comment]
Simplest question is, what do we want this to return?...

```python
>>> httpx.TimeoutConfig()
```

I *think* we should probably switch things around so that it'll give you `TimeoutConfig(timeout=5)` rather than `TimeoutConfig(timeout=None)`, right?

I guess we want something like this...


```python
DEFAULT_TIMEOUT = 5
UNSET = object()

def __init__(
    self,
    timeout: TimeoutTypes = DEFAULT_TIMEOUT,
    *,
    connect_timeout: float = UNSET,
    read_timeout: float = UNSET,
    write_timeout: float = UNSET,
):
    self.connect_timeout = timeout if connect_timeout is UNSET else connect_timeout
    self.read_timeout = timeout if read_timeout is UNSET else read_timeout
    self.write_timeout = timeout if connect_timeout is UNSET else write_timeout
```

**Comment by florimondmanca** [comment]
And so we'd have:

```python
>>> httpx.TimeoutConfig(read_timeout=1)
TimeoutConfig(connect_timeout=5, read_timeout=1, write_timeout=5)
>>> httpx.TimeoutConfig(timeout=None)  # Explicit disabled timeouts
TimeoutConfig(connect_timeout=None, read_timeout=None, write_timeout=None)
```

This looks like a nice approach to me. I suppose we'd get rid of `DEFAULT_TIMEOUT_CONFIG` entirely and use `TimeoutConfig()` instead?
