### ISSUE TITLE
Create a unified Timeout exception

### ISSUE THREAD

**Issue by sethmlarson** [encode/httpx#438]
Requests has `requests.Timeout` which is a sub-class of all (Read/Write/Connect)Timeout exceptions.

This causes an issue for users wanting to catch all timeouts: https://github.com/allisson/python-simple-rest-client/commit/b0a8c19b40477d1d9c69c3f35318c460680f41da#diff-21432cd9d3e6aeb800d660e681515b92R30

**Comment by florimondmanca** [comment]
So what I understand here is that we’d like to have a timeout exception base class?

Seems like we have it already...

```python
>>> import httpx
>>> httpx.exceptions.Timeout
<class 'httpx.exceptions.Timeout'>
```

**Comment by sethmlarson** [comment]
Oh, huh. I need to check our feature set before I decide we don't have something.
