### ISSUE TITLE
How to force Client to use a specific TLS version?

### ISSUE THREAD

**Issue by GnubiBORED** [encode/httpx#469]
So basically im migrating from requests to httpx and i see i was forcing tlsv1_2  with requests HTTPadapter , but  i dont think these is comp with httpx, i was wondering how i can force httpx to use specific tls version

```
from requests.adapters import HTTPAdapter
from urllib3.poolmanager import PoolManager
import ssl


class MyAdapter(HTTPAdapter):
    def init_poolmanager(self, connections, maxsize, block=False):
        self.poolmanager = PoolManager(num_pools=connections,
                                       maxsize=maxsize,
                                       block=block,
                                       ssl_version=ssl.PROTOCOL_TLSv1_2)



....



session = requests.session()
session.mount('https://', MyAdapter())

```
I was doing like these in requests

**Comment by florimondmanca** [comment]
Thanks for opening. Since I believe TLS v1.2 is considered insecure, I suppose you were forcing 1.2 because the client you’re connecting to is exposing that version of TLS? If you don’t have such a requirement anymore I’d advocate in favor of using 1.3.

If you really need it though, there may be an undocumented API (most likely SSLConfig) that you *could* somehow override, but I can’t dig it out right now.

**Comment by sethmlarson** [comment]
TLSv1.2 is totally secure and recommended, we enforce TLSv1.2+ for all of our connections by default.

**Comment by GnubiBORED** [comment]
> 
> 
> TLSv1.2 is totally secure and recommended, we enforce TLSv1.2+ for all of our connections by default.
> 
> @GnubiBORED Are you trying to enforce exactly TLSv1.2 (meaning explicitly excluding TLSv1.3?)

Yes, i need to in all my http calls just use TLSv1.2 never 1.3 atleast from now, cause the android app im sniffing uses 1.2 and i want to make the calls in the same way, with requests and httpadapter was easy to do. What im asking is if its possible to force specific tls version while making calls

**Comment by GnubiBORED** [comment]
@sethmlarson but i need to verify request with charlesproxy ssl certificate too, these will be a problem?

**Comment by sethmlarson** [comment]
You can pass `verify=[path to cert]` into the constructor of the `httpx.SSLConfig()` and that should work.

**Comment by sethmlarson** [comment]
Either that or you can call `ssl_context.load_verify_locations([path to cert])` on the SSLContext object. That'll also work.

**Comment by GnubiBORED** [comment]
Thanks for everything as always, i will close the issue

**Comment by GnubiBORED** [comment]
> 
> 
> So the way I'd recommend accomplishing this:
> 
> ```python
> >>> import ssl
> >>> import httpx
> >>> ssl_config = httpx.SSLConfig()
> >>> ssl_context = ssl_config.load_ssl_context()
> >>> ssl_context.options |= getattr(ssl, "OP_NO_TLSv1_3", 0)
> >>> client = httpx.Client(verify=ssl_context)
> >>> resp = client.get("https://howsmyssl.com/a/check")
> >>> print(resp.json()["tls_version"])
> 'TLSv1.2'
> ```
> 
> Currently we don't allow passing an `SSLConfig` object to `verify=` (which maybe we should because this is painful)


my code:

```
class test_client():
    def start(self, headers_pass, body_pass, params, url, ip, method, cookies):

        #todo aun falta configurar las cookies en las llamadas que faltan ya que no tengo claro que llamadas meten cookies y cuales no, la mayoria de gets llevan cookies


        #configuramos ssl para poder forzar a cliente a usar solo la version de tls que usa la app del tribalwars(TLSv1.2)
        #pasamos como parametro el directorio donde tenemos nuestro certificado, en mi caso el de charlesproxy que uso para debugear las llamadas que hago con el bot


        ssl_config = httpx.SSLConfig()
        #dentro de esta variable esta configurada el certificado que vamos a utilizar, con la configuracion cargada para luego solo usar la version de tls necesaria
        ssl_context = ssl_config.load_ssl_context()


        #con esta linea forzamos a usar tls 1.2, puesto que httpx no soporta 1.1 ya que es inseguro
        ssl_context.options |= getattr(ssl, "OP_NO_TLSv1_3", 0)
        ssl_context.load_verify_locations(r'C:\Users\localhost\Documents\Enrique\charlesproxy.pem')
        try:
            # usamos la libreria collections el metodo OrderedDict de esta manera ordenamos el diccionario y el cliente enviara los headers en el orden que nosotros le ponemos
            headers = collections.OrderedDict(headers_pass)
            #si la IP es 127.0.0.1 significa que no usaremos proxy en esa cuenta, asi que configuramos el cliente http sin proxy, solo con el certificado ssl
            if '127.0.0.1' not in ip:
                # configuramos los proxys que le pasamos en el cliente
                proxy = httpx.HTTPProxy(
                    #la variable ip que pasamos a la funcion es el proxy
                    "http://{}".format(ip),
                    #y aqui añadimos los headers especificos que llevan las peticiones CONNECT cuanndo usamos proxy
                    proxy_headers={"Host": url+':443',
                                   "Proxy-Connection":"Keep-Alive"}
                )
                #configuramos el proxy en el cliente
                client = httpx.Client(proxies={
                    "http": proxy,
                    "https": proxy


                #configuramos ssl en el cliente

                },verify=ssl_context)
            else:
                #asi configuramos el cliente solo con ssl cuando la ip es 127.0.0.1,es decir que no usamos proxy
                client = httpx.Client(verify=ssl_context)



            if method == 'get':

                response = client.get(url,headers= collections.OrderedDict(headers_pass),params=params)

                if response.history and 'login.php?mobile&sid' in url:

                    for resp in response.history:
                        zero_test = resp.headers['set-cookie']
                        sid_split = zero_test.split('=')
                        sid = sid_split[1].split(';')[0]
                        cid = sid_split[3].split(';')[0]

                        return {'sid': sid, 'cid': cid, 'html_response': response.text}
                else:

                    json_data = json.loads(response)

                    return json_data


            elif method == 'post':

                        #pasamos a texto  cualquier cosa dentro de el body
                        body = str(body_pass)
                        #mandamos a el cliente ha hacer el post
                        response = client.post(url, headers=collections.OrderedDict(headers_pass),params=params,data=body)
                        print(response.url)
                        json_data = json.loads(response)
                        return json_data

        except Exception as e:
            print(e.args)
            print(traceback.print_exc())

```

**Comment by alie42** [comment]
> لذا، بشكل أساسي، أقوم بالانتقال من الطلبات إلى httpx وأرى أنني كنت أجبر tlsv1_2 باستخدام طلبات HTTPadapter، لكنني لا أعتقد أن هذا متوافق مع httpx، كنت أتساءل كيف يمكنني إجبار httpx على استخدام إصدار tls محدد
> 
> ```
> from requests.adapters import HTTPAdapter
> from urllib3.poolmanager import PoolManager
> import ssl
> 
> 
> class MyAdapter(HTTPAdapter):
>     def init_poolmanager(self, connections, maxsize, block=False):
>         self.poolmanager = PoolManager(num_pools=connections,
>                                        maxsize=maxsize,
>                                        block=block,
>                                        ssl_version=ssl.PROTOCOL_TLSv1_2)
> 
> 
> 
> ....
> 
> 
> 
> session = requests.session()
> session.mount('https://', MyAdapter())
> ```
> 
> كنت أفعل مثل هذه في الطلبات
