### ISSUE TITLE
SSLV3_ALTER_BAD_CERTIFICATE being raised on valid certificate

### ISSUE THREAD

**Issue by lafrenierejm** [encode/httpx#478]
`ssl.SSLError [SSL: SSLV3_ALERT_BAD_CERTIFICATE]` is being raised when passing a path to a valid certificate.  `requests` accepts the certificate without error when performing the exact same call. The fact that this appears to be SSLv3-related is surprising;  the host I am attempting to connect to accepts TLS1.2 only.

- macOS 10.14.6 (Mojave)
- Python 3.7.4 installed using (pyenv)[https://github.com/pyenv/pyenv]
  - Built against OpenSSL 1.1
- httpx 0.7.5

Please let me know if any other information is needed for troubleshooting.  And thank you very much to all contributors to this project. :)

**Comment by sethmlarson** [comment]
Thanks for opening this! Is it possible to upload the certificate you're using?

**Comment by lafrenierejm** [comment]
@sethmlarson Unfortunately, no. The certificate is for one of my employer's internal use.

Is there any specific information about it that I could provide you with in lieu of the certificate itself?

**Comment by sethmlarson** [comment]
That's what I was afraid of. I'll have to investigate the call chain for requests versus HTTPX on specifying a `cert=` parameter.

**Comment by florimondmanca** [comment]
Closing this one as I assume the original problem has been dealt with/worked around since. If there's any similar issue in the future let's open a new issue. :-)
