### ISSUE TITLE
Drop proxies argument from top-level API functions.

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#480]
Somehow the `proxies` argument has crept into our top-level API functions (eg. `httpx.get()`).
It's not actually wired up anyplace. We should drop the argument for now.

We *will* want per-request control for proxies, but that should be implemented alongside adding support for `proxies=...` on the Client methods (eg. `client.get(...)`), which we currently erronously document, but do not support.

**Comment by yeraydiazdiaz** [comment]
> We will want per-request control for proxies, but that should be implemented alongside adding support for proxies=... on the Client methods (eg. client.get(...))

Is it worth creating a separate issue for this?
