### ISSUE TITLE
Logging levels

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#495]
I've been spending some time looking at logging levels with `uvicorn` lately, see eg. https://github.com/encode/uvicorn/pull/474 and would like to take a consistent approach across other projects in `encode`.

We've currently got some very detailed logging, that's available, tho it's really at a "dig into the internals" level, rather than general purpose log outputs.

Something that would tie in really nicely with the approach I'm taking elsewhere would be to have DEBUG-level outputs that issue a single line per-request...

`[DEBUG] HTTP Request: "GET https://api.github.com/user HTTP/1.1" 200 OK`

And then have a `TRACE` level outputs reserved for the really low-level stuff.

**Comment by florimondmanca** [comment]
100% yes for me. We currently have very verbose debug logs, which does seem to hint that they should be traces for low-level debugging (e.g. for bug reports etc.). A debug level with just a summary of requests would be enough to address "are my HTTP requests being fired at all?".

**Comment by florimondmanca** [comment]
I see this approach has already been implemented in a few other Encode projects:

- Uvicorn: https://github.com/encode/uvicorn/pull/474
- Databases: https://github.com/encode/databases/pull/156

I think I'll take a look at adding this to HTTPX. :-)
