### ISSUE TITLE
Async parallel request do not work

### ISSUE THREAD

**Issue by ThomasSchoenbeck** [encode/httpx#539]
i am trying to execute parallel requests. for that i looked at one of your docs/tutorials. link to the page https://www.encode.io/httpx/async/

got this when executing:

```python
    async with client.parallel() as parallel:
AttributeError: 'AsyncClient' object has no attribute 'parallel'
```

my code:
```python
import httpx
import os
import uvicorn
from fastapi import FastAPI

app = FastAPI()

@app.get("/")
async def process_text():
    async with httpx.AsyncClient() as client:
        async with client.parallel() as parallel:
            pending_one = await parallel.get('https://example.com/1')
            pending_two = await parallel.get('https://example.com/2')
            response_one = await pending_one.get_response()
            response_two = await pending_two.get_response()

    print(response_one, response_two)


if __name__ == "__main__":
    uvicorn.run(app, port=os.environ.get("PORT", 8080))
```

**Comment by florimondmanca** [comment]
Hi @ThomasSchoenbeck,

As documented on [this page](https://www.encode.io/httpx/parallel/), parallel requests are a proposed API that has not been implemented yet (and is not yet certain to be implemented in the currently documented form). See #50 for the relevant issue.

At this point, if you'd like to issue requests concurrently then you should use APIs provided by your async library (e.g. `asyncio`).

For example:

```python
responses = await asyncio.gather(
    client.get("https://example1.com"),
    client.get("https://example2.com"),
)
```

I think the fact that the parallel requests aren't marked as "still TODO" in the async client guide can indeed be confusing though.

So, @tomchristie what are your thoughts on removing the notes on parallel requests in the [API differences](https://www.encode.io/httpx/async/#api-differences) section, for now?

**Comment by tomchristie** [comment]
@florimondmanca - We should just drop any it flat-out - it's confusing users, and we don't need it for async cases.

**Comment by tomchristie** [comment]
Dropped from the docs as of #544.
