### ISSUE TITLE
Add equivalent to requests.response `ok` property

### ISSUE THREAD

**Issue by vyahello** [encode/httpx#543]
Hey there, I'm wondering do we have some equivalent of `requests.response:ok` property in `httpx` library? If no, Is it planning to be added sometime in the future? thx!

**Comment by StephenBrown2** [comment]
Not a core dev, so I can't comment on adding that particular feature, but the status codes are accessible via their upper and lower-case names in `httpx.codes`:
```py
In [1]: import httpx
   ...:
   ...: print(httpx.codes.ok)
200
```
So you can do:
```py
assert response.status_code == httpx.codes.ok
```
And also, the compatible `response.raise_for_status()` exists, so you can do:
```py
try:
	response = httpx.get(...)
	response.raise_for_status()
except httpx.HTTPError as ex:
    ...
```
Personally I've not used `response.ok` before, and only done `raise_for_status()`, but I can see why that might be a handy check while developing.

**Comment by thebigmunch** [comment]
> So you can do:
> 
> 
> ```python
> assert response.status_code == httpx.codes.ok
> # or
> if response.status_code != httpx.codes.ok:
>     ...
> ```

That is not equivalent to what ``response.ok`` does in ``requests``.

> And also, the compatible `response.raise_for_status()` exists, so you can do:
> 
> 
> ```python
> try:
> 	response = httpx.get(...)
> 	response.raise_for_status()
> except httpx.HTTPError as ex:
>     ...
> ```

``requests.ok`` just calls ``response.raise_for_status`` in a try/except and returns a boolean based on that. ``raise_for_status`` is equivalent between ``httpx`` and ``requests``.

> Personally I've not used `response.ok` before, and only done `raise_for_status()`, but I can see why that might be a handy check while developing.

I've never used ``response.ok`` from ``requests`` either.

**Comment by tomchristie** [comment]
I think it’s a bit confusing, as the naming kinda points towards “True if the status code was 200 OK”

I’d probably be okay with something like an `is_error` property, mirroring our existing `is_redirect` property.

I’m not sure about an `is_success`?

**Comment by vyahello** [comment]
Yeah agree with posts above, @tomchristie I guess both `is_error` and `is_success` methods would be useful!

**Comment by StephenBrown2** [comment]
> `response.ok` in `requests` just calls `response.raise_for_status` in a try/except and returns a boolean based on that. `raise_for_status` is equivalent between `httpx` and `requests`.

Good point. Here's the relevant snippet:
https://github.com/psf/requests/blob/428f7a275914f60a8f1e76a7d69516d617433d30/requests/models.py#L697-L710

`is_error` and `is_success` could be good aliases, would need to be documented in compatibility.md
