### ISSUE TITLE
Too many open files '/Users/vic/.netrc'

### ISSUE THREAD

**Issue by WoodyFleurant** [encode/httpx#556]
Using pip 19.0.3 and python 3.7
Full trace

  File "/Users/vic/projects/venvs/rasa/lib/python3.7/site-packages/httpx/utils.py", line 114, in get_netrc
  File "/Users/vic/.pyenv/versions/3.7.4/lib/python3.7/netrc.py", line 29, in __init__
OSError: [Errno 24] Too many open files: '/Users/vic/.netrc'

It happens whenever executing this code many times 

```
def _post(self, event):
        asyncio.ensure_future(self._post_async(event))

async def _post_async(self, event):
     await httpx.post(self.host, json=event)
```

**Comment by tomchristie** [comment]
That's surprising. Does it always fail with the `.netrc` file, or sometimes with other files?
Python's netrc handling closes the file once it's been used, so it's not obvious why that'd be happening.

Perhaps there's something weird happening related to state that `functools.lrucache` was hanging onto. There's a refactoring of the netrc in #558, I guess it's feasible that could resolve the issue.

Incidentally, you really ought to be using a single client to make all the calls, eg...

```python
client = httpx.Client()

def _post(self, event):
        asyncio.ensure_future(self._post_async(event))

async def _post_async(self, event):
     await client.post(self.host, json=event)
```

I think we need to do a better job in the documentation of leading our users down that path.

**Comment by tomchristie** [comment]
I'm going to assume that this is resolved in master, with our NetRC refactoring in #558.
Please do let us know if that's not the case.
