### ISSUE TITLE
Drop `MessageLoggerASGIMiddleware`

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#571]
It makes sense for uvicorn to provide that level of logging for ASGI, but I don't think it properly belongs in `httpx`, and we should keep our ASGI implementation (and any WSGI implementation once we've got sync support back) as absoultely slim and minimal as possible.

If users want any extra smarts they can use it as third party middleware (eg. import it from uvicorn instead, and wrap up the application explicitly.)

Would you be okay with that @florimondmanca?

**Comment by florimondmanca** [comment]
Makes sense! Especially this:

> If users want any extra smarts they can use it as third party middleware
