### ISSUE TITLE
Update documentation Re: Multipart File Encoding

### ISSUE THREAD

**Issue by Mattwmaster58** [encode/httpx#579]
Current documentation is incomplete. 
 - Doesn't correctly specify how `content-type` header is is determined

**Comment by tomchristie** [comment]
As it stands I'm closing this ticket out of hand, as "current issue description is incomplete".

Very happy to reconsider if there's a clear, postive, actionable description of what you'd like to see improved in that section of the documentation.

**Comment by tomchristie** [comment]
Related: The bullet points [in the docs section there](https://www.encode.io/httpx/advanced/#multipart-file-encoding) didn't appear to be well formatted.

Eg....

![Screen Shot 2019-11-30 at 21 47 28](https://user-images.githubusercontent.com/647359/69906432-0dd38700-13bb-11ea-8e07-b0772444283a.png)

vs.

![Screen Shot 2019-11-30 at 21 47 35](https://user-images.githubusercontent.com/647359/69906434-14fa9500-13bb-11ea-90b6-8601e5d537b6.png)

I've tweaked https://github.com/encode/httpx/blob/master/docs/advanced.md#multipart-file-encoding so they ought to display properly on the next docs build.

**Comment by Mattwmaster58** [comment]
Updated issue

**Comment by tomchristie** [comment]
Fab, thanks.
