### ISSUE TITLE
ImportError: cannot import name 'Middleware' from 'httpx.middleware'  (Windows)

### ISSUE THREAD

**Issue by lpellis** [encode/httpx#613]
I'm getting the following error trying to import httpx on Windows (python 3.8 and python 3.7 tested)
`ImportError: cannot import name 'Middleware' from 'httpx.middleware'`

It seems to be due to httpx containing both a package (httpx/middleware/__init__.py) and a module (httpx/middleware.py) of the same name, which is probably not a good idea.
A fix would be to simply rename middleware.py to something else, but I'm kinda confused why it would load at all though for other people?

**Comment by lpellis** [comment]
Looking at it some more, it looks like it might be a build artifact?  The middleware directory is not present in the sourcecode or in the  tar.gz package, but if I look at the the .whl it is there.  ( https://pypi.org/project/httpx/#files )

**Comment by florimondmanca** [comment]
@lpellis I *think* this was resolved as of 0.9.1, can you confirm?

**Comment by remarkov** [comment]
@florimondmanca I just updated from 0.8.0 to 0.9.1 and got this problem. Downgrading to 0.8.0 fixed it. I also tried 0.9.0 but it's there too.

**Comment by lpellis** [comment]
It is still present in 0.9.1

**Comment by michaelschmit** [comment]
I'm seeing this error as well running on a mac.

**Comment by petermorrow** [comment]
I'm also seeing this error on Amazon Linux with httpx==0.9.1. Switching to 0.8.0 fixed it as well.

**Comment by Punizione** [comment]
I'm running 0.9.1 on Windows and seeing this error, downgrading to 0.8.0 to fix it...

**Comment by florimondmanca** [comment]
Hi, seems this issue is resolved in v0.9.2 - thanks @tomchristie!

**Comment by tomchristie** [comment]
With a further uncaught issue resolved in 0.9.3. Phew. 😅
