### ISSUE TITLE
Allow Headers to tolerate other types than str (& bytes) 

### ISSUE THREAD

**Issue by taoufik07** [encode/httpx#638]
Currently Headers only accept str (and tolerate bytes in init) and as user I would expect the interface to accept other types (e.g. int) and try to stringify and encode them.

So what are your thoughts on changing Headers behavior and allowing it to tolerate other types at least some primitives like ints ?

- We could either allow other types only in init (get and set will keep accepting only strings)
- Or store the values as given by the user and add a method that returns the encoded items

**Comment by tomchristie** [comment]
Fari question, but I don't really want us to do this, no.

We shouldn't abstract away the HTTP semantics here - HTTP headers are not a general purpose data-transfer mechanism.

**Comment by taoufik07** [comment]
I totally understand the HTTP headers semantics, but coming from other http clients e.g. request, I would expect it to do the magic for me.

Fair answer tho
