### ISSUE TITLE
Drop `httpxprof`

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#654]
I think we should probably drop the `httpxprof` tooling from this reop.

It's okay for that to be a standalone tool, if needed.

**Comment by florimondmanca** [comment]
> It's okay for that to be a standalone tool, if needed.

Yup, that’s actually what it originally was - [httpx-profile](https://github.com/florimondmanca/httpx-profile).

I can move things we’ve got here over there, then remove it from here. :-)
