### ISSUE TITLE
AsnycIteratorStream should error if `__iter__` called twice.

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#668]
For defensive programming, the `AsyncIteratorStream` implementation should track `.stream_consumed` in `__iter__`, and raise a `RuntimeError` if it is called twice.

**Comment by gdhameeja** [comment]
Hello, I wanna work on this, but didn't understand the issue. As far as I explored the code, `is_stream_consumed flag` is on the `Response` class. And it seems everywhere this flag is being used, errors are raised appropriately. how would `AsyncIteratorStream` get access to this flag? The only connection I see between `Response` and `AsyncIteratorStream` is `HTTP2Connection` and `HTTP11Connection`

**Comment by tomchristie** [comment]
Heya. I didn't explain this fully - the class should have it's own `.is_stream_consumed` boolean.

Something along these lines...

```python
def __init__():
    self.is_stream_consumed = False

def __iter__():
    if self.is_stream_consumed:
        raise RuntimeError(...)
    self.is_stream_consumed = True
    ...  #OK
```

Plus a test in `test_content_streams.py` to ensure that it's working as expected.
