### ISSUE TITLE
DigestAuth should raise a clear error if the request cannot replay.

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#670]
Our DigestAuth implementation cannot work with non-replayable requests.
We ought to raise a nice clear error if `request.stream.is_replayable` is not True.

**Comment by tomchristie** [comment]
See the client redirect code for an equivelent case with redirects.

Potentially a reasonable first issue.

**Comment by kousikmitra** [comment]
hey can I work on this?

**Comment by florimondmanca** [comment]
@kousikmitra Feel free to! We don’t tend to assign people to issues so feel free to go ahead and open a PR when you’d like to get feedback. :)
