### ISSUE TITLE
test_client.py should be merged and dedup'd into test_async_client.py

### ISSUE THREAD

**Issue by florimondmanca** [encode/httpx#681]
This is a piece of technical debt remaining from #544: tests for `Client` are present (and mostly duplicated) across `test_async_client.py` and `test_client.py`.

I've been feeling we should clean that up for a while, and we do need to address it before re-introducing sync, so just tracking it here. :-)

**Comment by tomchristie** [comment]
I think we’ll likely end up going the other way on this - leave it in because a sync client is imminent (even if the sync dispatch isn’t quite there)

**Comment by tomchristie** [comment]
Now redundant given #735 (Which reintroduces proper sync tests in `test_client.py`.)
