### ISSUE TITLE
Consider explicitly allowing usage of insecure SSL/TLS versions

### ISSUE THREAD

**Issue by freis** [encode/httpx#736]
How would I be able to get some sort of ssl context to work when I get this sslerror? Any ideas? fyi the ip that I'm trying to connect to is: 62.28.216.189 as an example.

**Comment by florimondmanca** [comment]
Hi @freis,

Yes, we're currently not wrapping SSL errors — and I'd agree they can get somewhat cryptic — and that's definitely something we'd want to look at, but not sure where that lands in terms of priority.

I remember we had some discussion about SSL errors with you in #646. Could it be the case this time that the host is not supporting the TLS versions that HTTPX uses? See https://github.com/encode/httpx/issues/646#issuecomment-566942505

**Comment by florimondmanca** [comment]
@freis Is this issue linked to https://github.com/encode/httpx/issues/646#issuecomment-571667397?

**Comment by freis** [comment]
This time I think that the problem is indeed that the is is not supporting the TLS versions that HTTPX uses, that's why I opened a new issue to try to understand how could I get  hold of the context to change and force TLS1 or even SSLv2/v3.

**Comment by florimondmanca** [comment]
I see… As of 0.10.1 I don't think there's a way to do this easily.

On master you *could* reach into undocumented APIs with…

```python
import ssl
import httpx
from httpx.dispatch.connection_pool import ConnectionPool

connection_pool = ConnectionPool()
connection_pool.ssl.ssl_context.options &= ~ssl.OP_NO_TLSv1_1

async with httpx.AsyncClient(dispatch=connection_pool) as client:
    ...
```

I guess we could consider making `SSLConfig` public at some point, with an additional API to allow insecure versions we blacklist by default…

```python
import httpx

ssl = httpx.SSLConfig(allowed_insecure_versions=["SSLv3", "TLSv1_1"])
async with httpx.AsyncClient(ssl=ssl) as client:
    ...
```

**Comment by florimondmanca** [comment]
Changed the issue title to better reflect what I think is the requested feature here, sounds good?

**Comment by tomchristie** [comment]
You can pass a raw `SSLContext` instance for `httpx` to use, with `verify=[SSLContext]`.

We don't have any public API for *just* changing the SSL/TLS versions, but you could use something like this...

```python
from httpx.config import SSLConfig  # Careful, anything outside the top-level `httpx` is private API.
import ssl

ssl_config = SSLConfig()
ssl_config.ssl_context.options &= ~ssl.OP_NO_TLSv1_1

async with httpx.AsyncClient(verify=ssl_config.ssl_context):
    ...
```

(Similar to @florimondmanca's answer, but a slightly different approach.)

**Comment by freis** [comment]
For some reason I can't get ssl_context from both:
from httpx.config import SSLConfig or
from httpx.dispatch.connection_pool import ConnectionPool

**Comment by florimondmanca** [comment]
@freis What do you mean by "*can't get*"? Are they not importable? As I noted the snippets above should mostly only work on the master version of the repo (or the next release).

**Comment by florimondmanca** [comment]
Since we've given fairly reasonable workaround for this, I'm going to close this off. Thanks!

**Comment by tomchristie** [comment]
Good call. It’s feasible that we could promote `SSLconfig` into public API at some point, but let’s leave this as is for now.
