### ISSUE TITLE
Allow the specifying of which system IP address to use for client connections. 

### ISSUE THREAD

**Issue by eparra** [encode/httpx#755]
Allow the specifying of which system IP address to use for client connections.  If you look at http.client.HTTPConnection, it allows you pass a source address:

class http.client.HTTPConnection(host, port=None, [timeout, ]**source_address**=None, blocksize=8192) 

https://docs.python.org/3/library/http.client.html

**Comment by tomchristie** [comment]
Thanks, that's a really interesting request.

I think we're *likely* at a stage in the project where we'd probably push back on new API unless we consider it absolutely clear-cut must have functionality, and that some things that don't fall into that category could go into a *maybe later, but let's get more real-world feedback first*, so my initial reaction would probably be to put this into the "interesting, maybe later" pile...

For a bit of context, what's the motivation / use-case here?
Are there other high-level Python HTTP clients that make this available?

**Comment by thebigmunch** [comment]
> Are there other high-level Python HTTP clients that make this available?

* urllib3
* requests
* asks
* tornado.httpclient
* aiohttp
* treq through ``reactor`` parameter

**Comment by tomchristie** [comment]
I can find it in `urllib3`, https://urllib3.readthedocs.io/en/latest/reference/#urllib3.connection.HTTPConnection but I can't find it in `requests`?

**Comment by tomchristie** [comment]
Closed as "out of scope" for requests, https://github.com/psf/requests/issues/394 but available in the toolbelt... https://toolbelt.readthedocs.io/en/latest/adapters.html#sourceaddressadapter

**Comment by thebigmunch** [comment]
https://github.com/urllib3/urllib3/blob/063d888bc247eb6bd7aedcd32412bbb53c3c6ffb/src/urllib3/connection.py#L77

I assumed for requests itself. But, yeah. Still available in semi-official capacity.

**Comment by eparra** [comment]
> Thanks, that's a really interesting request.
> 
> I think we're _likely_ at a stage in the project where we'd probably push back on new API unless we consider it absolutely clear-cut must have functionality, and that some things that don't fall into that category could go into a _maybe later, but let's get more real-world feedback first_, so my initial reaction would probably be to put this into the "interesting, maybe later" pile...
> 
> For a bit of context, what's the motivation / use-case here?
> Are there other high-level Python HTTP clients that make this available?

The use case I have run into many times now is the need to simulate a pool of users, sourcing from unique IP addresses, for simulating users.  This is not possible with requests and has been requested as an enhancement many times.  Today I find users spawning off multiple containers to accomplish this vs. using a single machine, with multiple secondary IP addresses bound to the NIC, to accomplish this.   To add more color to the use case: testing a web proxy, FW, wan optimized, and network traffic probe, whereby a single IP requesting many webpages.

**Comment by bwelling** [comment]
I was just looking for this functionality in httpx, for a use case of sending DoH (DNS over HTTPS) requests, from dnspython.  Currently, dnspython uses requests to send queries, and requests_toolbelt.adapters.source.SourceAddressAdapter (when necessary) to set the source address, but since DoH is supposed to use HTTP/2, it would be nice to use httpx instead.

**Comment by tomchristie** [comment]
I'm going to currently close this off as out of scope.

We *might* be able to consider a nicely done PR to `httpcore` that implements this, but I don't want to consider it a priority unless someone's willing to step up and take it on.

**Comment by kotori2** [comment]
Since there is no proper documentation for this, here is how to use local address:
```
>>> import httpx
>>> from httpcore import SyncConnectionPool
>>> transport = SyncConnectionPool(local_address="xxxx:xxxx:xxxx:xxxx:f3d2:3ef7:28cd:7b60", http2=True)
>>> client = httpx.Client(transport=transport)
>>> r = client.get("https://api6.ipify.org")
>>> r.text
'xxxx:xxxx:xxxx:xxxx:f3d2:3ef7:28cd:7b60'
```

**Comment by p-i-** [comment]
To answer earlier question: how to do it with requests: https://stackoverflow.com/questions/48776564/python-and-c-sharing-the-same-memory-resources

**Comment by tomchristie** [comment]
You need to be using `async with httpx.HTTPTransport(local_address=ip, http2=True) as transport:`

**Comment by p-i-** [comment]
Thanks!
However if I switch that out, I now get:
```
  File "trio_scraper.py", line 20, in run_client
    async with httpx.HTTPTransport(local_address=ip, http2=True) as transport:
AttributeError: __aexit__
```

**Comment by p-i-** [comment]
ok gottit!
Here's how to do async:
```
import trio
import httpx

URL = 'https://api4.ipify.org/'
IP = '...'  # use your box's public IPv4

async def run_client(ip):
    async with httpx.AsyncHTTPTransport(local_address=ip, http2=True) as transport:
        async with httpx.AsyncClient(transport=transport) as client:
            response = await client.get(URL)
            print(ip, response.status_code, len(response.content))

async def main():
    async with trio.open_nursery() as n:
        n.start_soon(run_client, IP)

trio.run(main)
```

Thanks @tomchristie for shaking it loose

**Comment by p-i-** [comment]
Just a note that trying a different target URL I ran into `ModuleNotFoundError: No module named 'h2'` and needed `pip install h2`.
As per guidelines I floated it on https://gitter.im/encode/community rather than file an issue.

**Comment by mimi89999** [comment]
> Since there is no proper documentation for this, here is how to use local address:

Thanks for that example. I ended on this issue after a quick search and I had to make some adjustments to that example for it to work:
```
import httpx

transport = httpx.HTTPTransport(local_address="2001:bc8:1d90:11c0::24")

client = httpx.Client(transport=transport)

response = client.get("https://api6.ipify.org")

print(response.text)
```

This use case is also documented in https://www.python-httpx.org/advanced/transports/, but for some reason I found this issue first.
