### ISSUE TITLE
DecodingError with zlib-compressed responses

### ISSUE THREAD

**Issue by j4mie** [encode/httpx#756]
Using the following minimal WSGI app:

```python
import zlib

def app(environ, start_response):
    start_response("200 OK", [("Content-Encoding", "deflate")])
    return [zlib.compress(b"hello world")]
```

This works fine in a web browser.

Requests is quite happy:

```
>>> import requests
>>> requests.get("http://localhost:9999")
<Response [200]>
>>> requests.get("http://localhost:9999").text
'hello world'
```

httpx says:

```
>>> httpx.get('http://localhost:9999')
Traceback (most recent call last):
  File "/Users/jamie/code/httpx/httpx/decoders.py", line 52, in decode
    return self.decompressor.decompress(data)
zlib.error: Error -3 while decompressing data: invalid stored block lengths

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jamie/code/httpx/httpx/api.py", line 170, in get
    trust_env=trust_env,
  File "/Users/jamie/code/httpx/httpx/api.py", line 96, in request
    allow_redirects=allow_redirects,
  File "/Users/jamie/code/httpx/httpx/client.py", line 568, in request
    request, auth=auth, allow_redirects=allow_redirects, timeout=timeout,
  File "/Users/jamie/code/httpx/httpx/client.py", line 593, in send
    response.read()
  File "/Users/jamie/code/httpx/httpx/models.py", line 900, in read
    self._content = b"".join([part for part in self.iter_bytes()])
  File "/Users/jamie/code/httpx/httpx/models.py", line 900, in <listcomp>
    self._content = b"".join([part for part in self.iter_bytes()])
  File "/Users/jamie/code/httpx/httpx/models.py", line 912, in iter_bytes
    yield self.decoder.decode(chunk)
  File "/Users/jamie/code/httpx/httpx/decoders.py", line 54, in decode
    raise DecodingError from exc
httpx.exceptions.DecodingError
```

The reason this is an issue and not a PR is because I don't understand the code in `decoders.py` - it very explicitly says `self.decompressor = zlib.decompressobj(-zlib.MAX_WBITS)`, which according to [the Python docs](https://docs.python.org/3/library/zlib.html#zlib.compressobj) means "Uses the absolute value of wbits as the window size logarithm, while producing a raw output stream with no header or trailing checksum." I don't know enough about zlib to understand this, but it looks very deliberate so I thought I'd better ask.

**Comment by tomchristie** [comment]
Heya!

So, there's some useful context on this here... https://stackoverflow.com/questions/1838699/how-can-i-decompress-a-gzip-stream-with-zlib#answer-22311297

I think "deflate" encoding is supposed to use the style that we've currently implemented, but that actually "zlib" encoding also gets used for deflate in the wild. Certainly urllib3 handles both cases... https://github.com/urllib3/urllib3/blob/6322ad570c55fc0b51097ffcaeb9836358f27adb/src/urllib3/response.py#L32

For context, how did you bump into this - is one of the Python WSGI servers applying `zlib` compression automatically, or were you encoding the responses yourself?

**Comment by j4mie** [comment]
@tomchristie bit of a long story, but in short I'm trying to serve a file in chunks that's already been deflated and stored on disk. So I don't want to have to load the whole file into memory, re-encode, and then compress in the "right" way. I just want to send the chunks straight through. So yes, I'm doing something weird and this is an edge case.

Looks like urllib3's approach is probably the way to go?

**Comment by j4mie** [comment]
Thanks!
