### ISSUE TITLE
Using vpn endpoints as proxies.

### ISSUE THREAD

**Issue by Directory** [encode/httpx#759]
For my specific use case im using nordvpn endpoints. i parsed these endpoints from the openvpn filenames that you can download in bulk. an example of what these vpn endpoints look like are `us4138.nordvpn.com`. How would i make an http request that can proxy through this endpoint with authentication.

**Comment by tomchristie** [comment]
Is this what you're looking for?... https://www.python-httpx.org/advanced/#http-proxying

**Comment by Directory** [comment]
no that doesn't answer my question at all

**Comment by tomchristie** [comment]
> no that doesn't answer my question at all

That's not a very helpful follow-up. 🤣

What authentication? If not HTTP proxying, then what? Are you saying that the documentation isn't sufficiently helpful, or that it is but you're trying to do something else?

**Comment by Directory** [comment]
yes. ive described my issue. im trying to use a vpn endpoint as a proxy. that would both requirue authentication and idk how to do that

**Comment by HarrySky** [comment]
NordVPN is not a proxy, it is an OpenVPN server, you need to connect to it the other way (using `nordvpn connect` or `openvpn --config your_vpn_config.conf`. I doubt that you can use OpenVPN server as HTTP proxy with httpx

**Comment by Directory** [comment]
ive did it with the requests library but encountered a complicated issue were the connection stayed connected. i asked stackoverflow about the issue but no solution. https://stackoverflow.com/q/56934030/11358868

**Comment by tomchristie** [comment]
Everything you’ve described in that stackoverflow question is exactly the same in httpx as it would be in requests.

**Comment by Directory** [comment]
httpx does not take proxies in the same way that requests does. how can i make an httpx proxy object to pass with the proper authentication.

**Comment by tomchristie** [comment]
`httpx.Proxy(headers=...)`
