### ISSUE TITLE
Is SSL certificate pinning supported?

### ISSUE THREAD

**Issue by kr-deps** [encode/httpx#761]
I need SSL pinning for my app, does `httpx` support it? Is there a way to add logic to break the connection when I don't like the certificate?

**Comment by tomchristie** [comment]
You can use `httpx.Client(verify=<certfile>)`, which I assume is what you're asking for, right? https://www.python-httpx.org/advanced/#ssl-certificates

**Comment by kr-deps** [comment]
Basically I want to reject custom certificates that the user might have installed into the trusted store (to discourage the most casual reverse engineering). I used to do this by limiting the accepted certificates to a few well-known authorities (identified by fingerprints).

I think your solution should work. I thought about something a bit more flexible, though, like the [`checkServerIdentity`](https://nodejs.org/api/tls.html#tls_tls_checkserveridentity_hostname_cert) callback in Node.js. Some sort of function that, in addition to the default verification, inspects the certificate chain as it pleases.

**Comment by florimondmanca** [comment]
Do you have an example of another HTTP client library supporting this feature, if any? How were you achieving this 👇 before?

> I used to do this by limiting the accepted certificates to a few well-known authorities (identified by fingerprints).

**Comment by kr-deps** [comment]
I used this from the standard `https` module of Node.js (a desktop Electron app). The module has the use case of SSL pinning described in [the docs](https://nodejs.org/api/https.html#https_https_request_url_options_callback).

Pinning is not often available from 3rd-party libraries for Node, though.

Not sure if this is very important, but such a place to add extra certificate verification is helpful.

**Comment by florimondmanca** [comment]
@kr-deps Thanks for the link, those docs are very helpful.

As far as I’m aware, we don’t support that in HTTPX, no.

**Comment by tomchristie** [comment]
> Some sort of function that, in addition to the default verification, inspects the certificate chain as it pleases.

I think we ought to consider that as out of scope at this point in time. If we did want to explore it further, I think a good starting point would be putting togeter a concrete example use-case, along with a proposal for an API that would satisfy that use case.

**Comment by pquentin** [comment]
For reference, since Florimond asked:

 * aiohttp added fingerprints in 2017: https://github.com/aio-libs/aiohttp/issues/1965
 * urllib3 (and by extension requests) added fingerprints in 2013: https://github.com/urllib3/urllib3/pull/140
