### ISSUE TITLE
urllib3.ProxyManager() instantiation is broken.

### ISSUE THREAD

**Issue by ushuz** [encode/httpx#762]
python 3.7.5
httpx 0.11.0
urllib3 1.25.7

```
$ ipython3 -c 'import httpx; r = httpx.get("https://www.google.com")'
parse_url http://127.0.0.1:1234 <class 'httpx.models.URL'>
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-d6fe3101235f> in <module>
----> 1 import httpx; r = httpx.get("https://www.google.com")

/usr/local/lib/python3.7/site-packages/httpx/api.py in get(url, params, headers, cookies, auth, allow_redirects, cert, verify, timeout, trust_env)
    168         verify=verify,
    169         timeout=timeout,
--> 170         trust_env=trust_env,
    171     )
    172

/usr/local/lib/python3.7/site-packages/httpx/api.py in request(method, url, params, data, files, json, headers, cookies, auth, timeout, allow_redirects, verify, cert, trust_env)
     82     """
     83     with Client(
---> 84         cert=cert, verify=verify, timeout=timeout, trust_env=trust_env,
     85     ) as client:
     86         return client.request(

/usr/local/lib/python3.7/site-packages/httpx/client.py in __init__(self, auth, params, headers, cookies, verify, cert, proxies, timeout, pool_limits, max_redirects, base_url, dispatch, app, trust_env)
    477                 trust_env=trust_env,
    478             )
--> 479             for key, proxy in proxy_map.items()
    480         }
    481

/usr/local/lib/python3.7/site-packages/httpx/client.py in <dictcomp>(.0)
    477                 trust_env=trust_env,
    478             )
--> 479             for key, proxy in proxy_map.items()
    480         }
    481

/usr/local/lib/python3.7/site-packages/httpx/client.py in init_proxy_dispatch(self, proxy, verify, cert, pool_limits, trust_env)
    512             cert=cert,
    513             pool_limits=pool_limits,
--> 514             trust_env=trust_env,
    515         )
    516

/usr/local/lib/python3.7/site-packages/httpx/dispatch/urllib3.py in __init__(self, proxy, verify, cert, trust_env, pool_limits)
     58             num_pools=num_pools,
     59             maxsize=maxsize,
---> 60             block=block,
     61         )
     62

/usr/local/lib/python3.7/site-packages/httpx/dispatch/urllib3.py in init_pool_manager(self, proxy, ssl_context, num_pools, maxsize, block)
     83                 num_pools=num_pools,
     84                 maxsize=maxsize,
---> 85                 block=block,
     86             )
     87

/usr/local/lib/python3.7/site-packages/urllib3/poolmanager.py in __init__(self, proxy_url, num_pools, headers, proxy_headers, **connection_pool_kw)
    412                 proxy_url.port,
    413             )
--> 414         proxy = parse_url(proxy_url)
    415         if not proxy.port:
    416             port = port_by_scheme.get(proxy.scheme, 80)

/usr/local/lib/python3.7/site-packages/urllib3/util/url.py in parse_url(url)
    361     print('parse_url', url, type(url))
    362     source_url = url
--> 363     if not SCHEME_RE.search(url):
    364         url = "//" + url
    365

TypeError: expected string or bytes-like object
```

**Comment by ushuz** [comment]
Besides, unlike most CLI tools, httpx uses OS system proxy settings (at least on macOS, because of `urllib.request.getproxies()`) regardless of envvar, which is surprising and unexpected.

**Comment by yorushika** [comment]
Same issue here after updating to 0.11.0, good job. I changed the code by myself.

On the other hand, this issue **DID NOT** appear on my CentOS7 VPS, which using such environment:
    * Python 3.7.3 (default, Mar 27 2019, 22:11:17) [GCC 7.3.0] :: Anaconda
    * IPython 7.4.0
    * httpx 0.11.0

But on my MacBook this issue occurs. Even after creating a same Python 3.7.3 & IPython 7.4.0 & httpx 0.11.0. So confusing.

**Comment by tomchristie** [comment]
@yorushika - The issue only occurs when proxies are in use - presumably you've got some different `HTTP_PROXY` / `HTTPS_PROXY` / `ALL_PROXY` environment settings on those two machines.

**Comment by yorushika** [comment]
> @yorushika - The issue only occurs when proxies are in use - presumably you've got some different `HTTP_PROXY` / `HTTPS_PROXY` / `ALL_PROXY` environment settings on those two machines.

Jeez, absolutely, I'm using proxy on my Mac. I'll check it out, thank you!

**Comment by yorushika** [comment]
> @yorushika - The issue only occurs when proxies are in use - presumably you've got some different `HTTP_PROXY` / `HTTPS_PROXY` / `ALL_PROXY` environment settings on those two machines.

Strange. I checked by `export -p` and found nothing about proxy. I used to set proxy settings by `export`, yes, but removed them days before I remember.
I'm using Surge & ShadowSocks on my Mac but they have no effect on console(iterm2).

**Comment by tomchristie** [comment]
@yorushika Maybe try `python -c "import urllib.request; print(urllib.request.getproxies())"` to inspect your system proxy configuration.

**Comment by yorushika** [comment]
@tomchristie Well yes, I got this:
`{'http': 'http://127.0.0.1:8888', 'https': 'http://127.0.0.1:8888'}`

Confusing me how to remove this...

By the way,
> Besides, unlike most CLI tools, and unlike **requests**, httpx uses OS system proxy settings over envvar (at least on macOS), which is surprising and unexpected.

Is this the reason of this result?

**Comment by tomchristie** [comment]
> Confusing me how to remove this...

You can use `trust_env=False` if you want to disable the system's defaults.

**Comment by yorushika** [comment]
Emm I was just wondering how it appears. I inspected settings of Surge and found they are proxies provided by it. So it's no need to disable them and all I need is just an update.....

Thank you for helping!

**Comment by ushuz** [comment]
> Besides, unlike most CLI tools, and unlike **requests**, httpx uses OS system proxy settings over envvar (at least on macOS), which is surprising and unexpected.

@tomchristie I think @yorushika's responses demonstrated "surprising and unexpected" I mentioned above. Adopting the [proxy bypass logic](https://github.com/psf/requests/blob/a9ee0eef5a70acb9ed35622b3675574b11f92cb4/requests/utils.py#L699-L757) from requests might make httpx more requests-compatible and less surprising IMO.

**Comment by tomchristie** [comment]
@ushuz It's certainly worth some conversation, yup. (Tho let's treat it as a seperate issue from this.)
