### ISSUE TITLE
Proxies defaults should be env-var based, rather than env-var + system config.

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#764]
Our proxy configuration uses `urllib.requests.getproxies()`, which as-per the Python docs...

> It scans the environment for variables named <scheme>_proxy, in a case insensitive approach, for all operating systems first, and when it cannot find it, looks for proxy information from Mac OSX System Configuration for Mac OS X and Windows Systems Registry for Windows. If both lowercase and uppercase environment variables exist (and disagree), lowercase is preferred.

By contrast `requests` *only* uses environment variables.

Some things to dig into here:

* What was requests' motivation for only using envvars, rather than falling back to the system config?
* Did *we* make a deliberate design choice to fall back to the system config, or is this just what we ended up with?
* Which of these two approachs should be prefered?

Then we should either:

* Document the difference from requests here, possibly document the fallback in the envvars docs section.
* *Or*: Implement an envvars-only approach instead of the existing behavior.

Raised via: https://github.com/encode/httpx/issues/762#issuecomment-573987002

**Comment by yorushika** [comment]
This strategy is good I think. Considering different circumstances, document it and provide an option to switch it off/on is suitable enough -- my personal idea.

Besides: httpx is s∞ cool, especially after this topic.

**Comment by ushuz** [comment]
> What was requests' motivation for only using envvars, rather than falling back to the system config?

Quick guesses from requests' commit history (https://github.com/psf/requests/pull/1951) and `getproxies()` implementation:
- make requests more predictable cross platform as `getproxies()` implementation varies from platform to platform
https://github.com/python/cpython/blob/fad8b5674c66d9e00bb788e30adddb0c256c787b/Lib/urllib/request.py#L2731-L2734
- refine `no_proxy` envvar support
https://github.com/Lukasa/requests/blob/90f73378582e4e2cbc75a189a2cfa7826824f29e/requests/utils.py#L480-L496
- workaround some buggy behavoirs of stdlib
https://github.com/Lukasa/requests/blob/90f73378582e4e2cbc75a189a2cfa7826824f29e/requests/utils.py#L500-L501

> Did we make a deliberate design choice to fall back to the system config, or is this just what we ended up with?

Not sure, I'm new to httpx. While my bet is the latter, that this what we ended up with, causes implementation is always simple and navie in the beginning, and httpx is still young.

> Which of these two approachs should be prefered?

I suggest we match requests' behavior. As Python 2 EOLed, more people are getting onboard async-capable Python 3 and people will want to use async. Considering requests' popularity, "a **drop-in** and **async** replacement for requests" would be a strong selling point for httpx. Less differences, less surprises, more like **drop-in**, easier for the whole Python community to get asynced.

**Comment by j178** [comment]
> By contrast `requests` _only_ uses environment variables.

I find something different...

According to this:
https://github.com/psf/requests/blob/48237afd9d064c639b9c2bcea7e75ab7b717b181/requests/utils.py#L760-L769

`requests` is actually using `urllib.request.getproxies()` to fetch proxies from env-vars *and* system-wise config, this is same behavior as `httpx`.

Correct me if I am getting something wrong...

**Comment by tomchristie** [comment]
@j178 Right I've had a look over, and come to the same conclusion as you. Nicely done.

It's confusing because the util function in `requests` is named `get_environ_proxies()`, but it's calling stdlib's `getproxies()`, and only calls into `getproxies_environment()` in one particular case within some complicated windows proxy bypass code, that I'd really rather not know anything about right now. (And that might perfectly well no longer be a relevant stdlib issue anymore?)

In that case I think we should close this one off as a WONTFIX.

We made the wrong call first time around - it's good, it's wonderful, let's leave it as it is.
