### ISSUE TITLE
Handle redirects with missing hostname in `Location:`  header.

### ISSUE THREAD

**Issue by fbexiga** [encode/httpx#771]
While doing something like this:

```
import httpx

def run_sync(url):
    with httpx.Client(verify=False) as client:
        response = client.get(url)
        print(response)

run_sync('http://62.28.16.253')
```

I get a `httpx.exceptions.InvalidURL: No host included in URL.`

However `curl -vLk http://62.28.16.253` works like normal, as well as other HTTP clients. I think this might be another sketchy server misconfiguration, but should work nonetheless.

**Comment by tomchristie** [comment]
Thanks so much for the report!

> I think this might be another sketchy server misconfiguration, but should work nonetheless.

Indeed. Appears to be a malformed 'Location' header in the response...

```shell
Pragma: no-cache
Location: https://:443/
Content-Type: text/html
```

We ought to handle that case gracefully, tho.
