### ISSUE TITLE
Is there an easy way to set a timeout for the entire request?

### ISSUE THREAD

**Issue by Recursing** [encode/httpx#776]
I was reading the excellent https://medium.com/@shnatsel/smoke-testing-rust-http-clients-b8f2ee5db4e6 and wanted to test the awesome httpx just for fun

It mentions this issue https://github.com/algesten/ureq/issues/28 about setting a timeout for request completion, which would make sense for both the sync and the async case, which I think would be a nice addition the the high level api (I think it can already be done with the stream api and read_timeouts, I was wondering if there was a higher level way)

Edit: see how aiohttp handles timeouts https://docs.aiohttp.org/en/stable/client_quickstart.html#timeouts

**Comment by florimondmanca** [comment]
Hi!

In the async case, IMO async libraries already provide sufficient primitives for this...

```python
import asyncio
import trio
import httpx


async def main_asyncio():
    async with httpx.AsyncClient() as client:
        r = await asyncio.wait_for(client.get('https://www.example.org'), timeout=10)


async def main_trio():
    async with httpx.AsyncClient() as client:
        with trio.fail_after(10):
            r = await client.get('https://www.example.org')

```

In the sync case, I don't think a global timeout in threaded code can be sanely implemented, can it.

I managed to put together an outrageous signal hack, but…

- It only works with integer timeouts, not floats (a limitation of the underlying `alarm()` syscall).
- If the code running within the block silences the exception raised by the signal handler, we're doomed.
- It's probably a bad idea.

```python
import contextlib
import signal
import time

import httpx


@contextlib.contextmanager
def fail_after(seconds):
    def handler(signum, frame):
        raise TimeoutError

    initial_handler = signal.getsignal(signal.SIGALRM)
    signal.signal(signal.SIGALRM, handler)
    signal.alarm(seconds)

    try:
        yield
    except TimeoutError:
        raise TimeoutError from None
    except BaseException:
        signal.alarm(0)
    else:
        signal.alarm(0)
    finally:
        signal.signal(signal.SIGALRM, initial_handler)


def app(environ, start_response):
    # Simulate a very-long-to-respond server that blocks the main thread...
    time.sleep(10)


def main() -> None:
    with httpx.Client(app=app) as client:
        with fail_after(1):
            r = client.get("https://www.example.org")
            print(r)

if __name__ == "__main__":
    main()
```

So, uh… _personally_ not super keen on supporting this in core, but my recommendation would be to use async and their native timeout APIs? 😄

**Comment by Recursing** [comment]
Hi! Thanks for the quick and detailed reply (and for the awesome library)!

For some reason I didn't think of the obvious way in async, I agree that it's absolutely nice enough, thank you for that, I will definitely use it often!

For the sync case other libraries manage to do it with less hacky methods, maybe by using a timeout (max_final_time - current_time) on every wait for new data which could be a good approximation, but I don't know if it's actually that easy or at all worth it, I think you guys should decide based on the linked ureq issue.

Feel free to close this issue if you decide it's not worth it, as the question is very nicely answered. Thanks again!

**Comment by Shnatsel** [comment]
I'm aware of two approaches to a timeout for the entire request in sync code:

1. Readjust the read timeout to `request_deadline - current_time` once in a while - say, every 200ms or so
2. Spawn a thread that shuts down the socket after a timeout has elapsed

Sample implementations: https://github.com/neonmoe/minreq/commit/41ef16e33501712e64a5711a7f4bc132d9bfbe40 for approach 1 (although this readjusts on every read, which is slow) and https://github.com/sbstp/attohttpc/pull/47 for approach 2
