### ISSUE TITLE
Incremental changelog additions?

### ISSUE THREAD

**Issue by yeraydiazdiaz** [encode/httpx#781]
In the ["releasing" section of the docs](https://www.python-httpx.org/contributing/#releasing) we mention maintainers should go over the changes and add entries to the changelog.

I noticed [other projects](https://github.com/hynek/structlog/blob/master/CHANGELOG.rst) add entries to it [as part of PRs](https://github.com/hynek/structlog/pull/240/files) which seemed like an idea we could adopt to reduce the amount of work on a release?

I realize that exact example this doesn't play very well with SemVer as it forces us to write a version number that might be change depending on other PRs that are merged. Though we could simply state `## UNRELEASED` or something until we actually cut the release.

Thoughts?

**Comment by thebigmunch** [comment]
> Though we could simply state `## UNRELEASED` or something until we actually cut the release.

HTTPX uses the Keep a Changelog format which [specifically states](https://keepachangelog.com/en/1.0.0/#effort) to do just that for unreleased changes.

**Comment by florimondmanca** [comment]
I think we already discussed this idea back in #148, and the rationale was that adding changelog entries as part of PRs might not be as easier when we take into account the burden of making sure each PR complies with that policy. (IMO it would put extra burden on both contributors and maintainers.) So far I'm good with reviewing the commit history since the last version — made easier by the fact that we squash commits anyway. :-)

**Comment by tomchristie** [comment]
Reasonable suggestion, yup. I'm happy with our workflow at the moment, but also don't have any big aversion to tweaking things.

Pros:

* Always up to date.
* Less chance of missing things in a new release.

Cons:

* Introduces more drag on PRs.
* Tends to introduce merge conflicts.

I'm probably lightly on the "draw them up at release", given that we force sqaush merging, so reviewing at that point has felt pretty easy, but I'll leave this one with @florimondmanca to take the call on for now.

**Comment by yeraydiazdiaz** [comment]
Sounds like you're in agreement, if it ever changes we can revisit 🙂 

Thanks!

**Comment by florimondmanca** [comment]
Sure, thanks for opening the discussion @yeraydiazdiaz!

**Comment by StephenBrown2** [comment]
`towncrier` was suggested and would probably be the recommended way to go about avoiding merge conflicts, but so far the "maintainers review and add changelog entries" has worked well enough so far.
