### ISSUE TITLE
Drop `backend=...` argument.

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#782]
Now that we have async autodetection, I think we ought to consider dropping the `backend` argument from `AsyncClient.__init__(...)`, since it's not really required.

If anything it'd be better to find out if/when there are any cases that `sniffio` isn't able to correctly detect, and fix them, rather than having users be able to flick an override switch.

(It'd also potentially make it easier to have a clear split if we wanted to factor the dispatch out into an entirely independant package at some point, since we'd want the backend implementations to reside in the core networking package, rather than in `httpx`.)

**Comment by dalf** [comment]
Note: I use a custom Backend to record the certificates of the HTTPS requetsts.
This backend behaves a proxy to a real backend, but record the ssl.SSLObject

Code:
* https://github.com/dalf/searx-stats2/blob/master/searxstats/common/ssl_info.py#L85
* https://github.com/dalf/searx-stats2/blob/master/searxstats/common/http.py#L70

**Comment by tomchristie** [comment]
@dalf - That's a really useful (surprising) bit of feedback, thanks!

(And yes, you've got the right approach there, but make sure you're pinning your dependencies tightly if you're relying on private API!)
