### ISSUE TITLE
Docs page about community/third-party resources

### ISSUE THREAD

**Issue by florimondmanca** [encode/httpx#805]
There's a [Third party packages](https://www.starlette.io/third-party-packages/) page in the Starlette docs — I think it might be a good idea to start one for HTTPX?

Perhaps even more general than third-party packages, e.g.:

- Third-party packages
- Blog posts/articles
- Talks
- Mentions in podcasts
- ...

Possible entries already:

- [Authlib: OAuth for HTTPX](https://docs.authlib.org/en/latest/client/httpx.html)
- [RESPX](https://github.com/lundberg/respx)
- [Quick and dirty mock service with Starlette](https://www.mattlayman.com/blog/2019/starlette-mock-service/) (and HTTPX)
- [Django's Async Future](https://djangochat.com/episodes/django-async-future-tom-christie-cK1OMcGh) (includes a good chunk about HTTPX & its development)
- @tomchristie's past and upcoming talks on the topic :)

Thoughts?

**Comment by hugovk** [comment]
Looking at the "Used by" tab above, here's some with over 1,000 stars:

* https://github.com/huge-success/sanic
* https://github.com/biolab/orange3
* https://github.com/Netflix/dispatch

**Comment by florimondmanca** [comment]
@hugovk Thanks! Those are good findings. Wondering if we'd want to add some kind of "Used by these big-name projects" sometime in the future… Might be too much of a marketing push in my view (high quality standards + word of mouth has worked well so far!), but it's an interesting idea.
