### ISSUE TITLE
Proxies defined in env var should be allowed without scheme

### ISSUE THREAD

**Issue by Colin-b** [encode/httpx#806]
Current httpx expectation/behavior: 

If you set an environment variable such as HTTP_PROXY or HTTPS_PROXY you have to specify a scheme in the value.

> httpx\client.py:466: in __init__
>     proxy_map = self.get_proxy_map(proxies, trust_env)
> httpx\client.py:93: in get_proxy_map
>     return {
> httpx\client.py:94: in <dictcomp>
>     key: Proxy(url=url)
> httpx\config.py:320: in __init__
>     url = URL(url)
> httpx\models.py:106: InvalidURL

Expected behavior:

I assume that in requests, http scheme is used by default ?

**Comment by tomchristie** [comment]
> I assume that in requests, http scheme is used by default?

No idea.

It'd be worth testing the behavior against both `curl` and `requests`, since both of those use these environment variables.

**Comment by yeraydiazdiaz** [comment]
From the [proxies section of the documentation](https://requests.readthedocs.io/en/master/user/advanced/#proxies)

> Note that proxy URLs must include the scheme

I think we should mimic this behaviour so I'm closing this issue. Thanks @Colin-b for bringing it up 👍
