### ISSUE TITLE
Is it planned to implement __bool__ on Response?

### ISSUE THREAD

**Issue by Colin-b** [encode/httpx#809]
The same way it's done on [requests](https://github.com/psf/requests/blob/master/requests/models.py#L673).

I saw that [response.is_error](https://github.com/encode/httpx/issues/543) is available, I was wondering if it was planned or not (as I was considering httpx some kind of drop-in replacement for requests)?

Thanks again

**Comment by tomchristie** [comment]
Nope, I doubt we’d do that.

**Comment by florimondmanca** [comment]
I'm inclined towards a "no" too, basically for the same reason as we don't have `response.ok`: ambiguity, and possibly error-prone.

(Eg. if you use `if not response: ...` would that be to check whether `response` is set, or whether the response is "falsy"? What would "falsy" mean? `response.is_error`? Then we should access this attribute explicitly.)
