### ISSUE TITLE
Add ujson support

### ISSUE THREAD

**Issue by dmig-alarstudios** [encode/httpx#812]
Currently, there are 2 places with hardcoded `json` reference:

https://github.com/encode/httpx/blob/b3db9ff0b6554ed3a48ff912682f4a7d10c3f3f8/httpx/_models.py#L4
https://github.com/encode/httpx/blob/b3db9ff0b6554ed3a48ff912682f4a7d10c3f3f8/httpx/_content_streams.py#L6

these can be changed as:
```py
try:
 import ujson as jsonlib
except ImportError:
 import json as jsonlib 
```
and
```py
try:
 from ujson import dumps as json_dumps 
except ImportError:
 from json import dumps as json_dumps 
```
To allow `ujson` library usage. A better approach would be to allow the user to specify custom serializer/deserializer functions.

**Comment by tomchristie** [comment]
I doubt we'd want to support this.
Use something like `ujson.loads(response.content)` if you need customized JSON handling.

**Comment by dmig-alarstudios** [comment]
The main reason for my case -- use it for encoding to avoid adhoc conversion for fields like date or set().
Is there a way to use custom encoder in this case?
```py
client.post(f"{services['SOME_SERVICE_URL']}/update/", json=params)
```

**Comment by tomchristie** [comment]
Sure thing, encode the json explicitly, and post that data. This sort of thing...

```python
data = json.dumps(...)
client.post(url, data=data, headers={'Content-Type': 'application/json'})`
```

**Comment by injust** [comment]
> Sure thing, encode the json explicitly, and post that data. This sort of thing...
> 
> ```python
> data = json.dumps(...)
> client.post(url, data=data, headers={'Content-Type': 'application/json'})`
> ```

I think this should be `content=data` instead of `data=data`?

`data` takes a mapping, whereas `content` takes `str` or `bytes` (among other types).

**Comment by tomchristie** [comment]
Yes.
