### ISSUE TITLE
Add TODOs Badge

### ISSUE THREAD

**Issue by patrickdevivo** [encode/httpx#816]
Hi there! I wanted to propose adding the following badge to the README to indicate how many `TODO` comments are in this codebase:

[![TODOs](https://img.shields.io/endpoint?url=https://api.tickgit.com/badge?repo=github.com/encode/httpx)](https://www.tickgit.com/browse?repo=github.com/encode/httpx)

The badge links to `tickgit.com` which is a free service that indexes and displays TODO comments in public github repos. It can help surface latent work and be a way for contributors to find areas of code to improve, that might not be otherwise documented.

The markdown is:

```
[![TODOs](https://img.shields.io/endpoint?url=https://api.tickgit.com/badge?repo=github.com/encode/httpx)](https://www.tickgit.com/browse?repo=github.com/encode/httpx)
```

Thanks for considering, feel free to close this issue if it's not appropriate or you prefer not to!

**Comment by tomchristie** [comment]
Thanks! That's an interesting tool.

I'd rather we pass on it, tho we might consider opening issues corresponding to each of those two tasks, then removing the `TODO` notes from the codebase?

**Comment by patrickdevivo** [comment]
@tomchristie thanks for considering! Just an FYI - each `TODO` card has a button that takes you directly to the "New Issue" page of a repo, with the title and body prefilled.
