### ISSUE TITLE
httpx.exceptions.RedirectLoop

### ISSUE THREAD

**Issue by adilkhash** [encode/httpx#821]
Hi there!

I stumbled upon an interesting issue with httpx.
Here is the code snippet:

```python
async def main():
    async with httpx.AsyncClient() as client:
        response = await client.get(
            'https://www.meloman.kz/',
        )

if __name__ == '__main__':
    asyncio.run(main())
```

When I execute the code I get the error `httpx.exceptions.RedirectLoop`. When you try to access meloman.kz without initial cookies it redirects you to the same location with 302 code. I have no idea why they do this but `requests` and `aiohttp` handle this situation smoothly.

Do we really need `httpx.exceptions.RedirectLoop` if httpx has `max_redirects` option ?

**Comment by yeraydiazdiaz** [comment]
Hello @adilkhash, thanks for your report.

This behaviour was raised previously in https://github.com/encode/httpx/pull/801 and its potential solution is captured in https://github.com/encode/httpx/pull/819 so I'm closing this as a duplicate.

For reference the website is redirecting to the same URL with a Set-Cookie header:

```
http https://www.meloman.kz/
HTTP/1.1 302 Found
Cache-Control: no-cache, no-store, must-revalidate, private
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 25
Content-Type: text/html; charset=UTF-8
Date: Sat, 22 Feb 2020 09:11:16 GMT
Expires: Fri, 22 Feb 2019 09:11:16 GMT
Location: https://www.meloman.kz/
Pragma: no-cache
Server: nginx
Set-Cookie: PHPSESSID=4ep0ro0r3lurk5qfremjfgqq3r; expires=Mon, 23-Mar-2020 09:11:16 GMT; Max-Age=2592000; path=/; domain=.meloman.kz; secure; HttpOnly
Set-Cookie: region_id=541; expires=Sat, 29-Feb-2020 09:11:16 GMT; Max-Age=604800; path=/; domain=.meloman.kz
Set-Cookie: region_just_set=1; expires=Sat, 22-Feb-2020 10:11:16 GMT; Max-Age=3600; path=/; domain=.meloman.kz
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: allow-from http://webvisor.com/
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
