### ISSUE TITLE
Ubuntu 16.04.6 LTS - I cannot install 

### ISSUE THREAD

**Issue by catafest** [encode/httpx#827]
I try to use pip , pip3 , install from GitHub source ( setup.py build and install)  with python 3.5 and python 3.7.
I cannot install on Ubuntu 16.04.6 LTS.
Any idea ?

**Comment by tomchristie** [comment]
What commands are you running and what output are you seeing?

**Comment by florimondmanca** [comment]
@catafest Agreed with Tom we'd need more info here — command runthrough and full traceback output would help. :+1:

(Also note that we don't officially support Python 3.5.)
