### ISSUE TITLE
Dead butterfly 🙀🦋

### ISSUE THREAD

**Issue by dimaqq** [encode/httpx#834]
Full disclosure: this is not a serious issue, more of a tongue-in-cheek :)

As posted in comments for httpx announcement(?) on reddit (https://news.ycombinator.com/item?id=22000507)

https://emilydamstra.com/news/please-enough-dead-butterflies/

In short, the images of butterflies we often see are those of pinned, posed, dried, dead butterflies.
While the living butterflies hold their wings differently.

Maybe, depending on what message the butterfly of httpx is meant to convey, the logo could be a bit more... living :)

What's the model butterfly anyway, is it Pieris rapae?

**Comment by florimondmanca** [comment]
Yup, I remember back then picking up this HN comment and making a similar note on our Gitter channel… 😄 

At that time I dug up this picture of a similar (but living) butterfly: https://www.fontainebleau-blog.com/insectes/pieride-du-navet-pieris-napi/. The author is a photographer; pictures are taken in the Fontainbleau forest, in the south-east of Paris. I could ask if he'd be okay with us using and editing that picture to extract the butterfly on a transparent background. :-)

**Comment by tomchristie** [comment]
> What's the model butterfly anyway, is it Pieris rapae?

Couldn't tell you - it comes from a 1873 illustration by A.S.Packard.

https://www.gutenberg.org/files/24409/24409-h/24409-h.htm

The associated text is wonderfully colourful too...

> When the caterpillar has ended its riotous life, for its appetite almost transforms its being into the very incarnation of gluttony, it suddenly, as if repenting of its former life as a bon vivant, seeks a solitary cell or hole where like a hermit it sits and leads apparently about as useless an existence. But meanwhile strange processes are going on beneath the skin; and after a few convulsive struggles the back splits open, and out wriggles the chrysalis, a gorgeous, mummy-like form, its body adorned with golden and silvery spots. Hence the word chrysalis (Fig. 14, b), from the Greek, meaning golden, while the Latin word pupa, meaning a baby or doll, is indicative of its youth. In this state it hangs suspended to a twig or other object; while the silk worm, and others of its kind, previous to moulting, or casting their skins, spin a silken cocoon, which envelops and protects the chrysalis.
>
> At the given time, and after the body of the adult has fully formed beneath the chrysalis skin, there is another moult, and the butterfly, with baggy, wet wings, creeps out. The body dries, the skin hardens, the wings expand, and[Pg xvi] in a few moments, sometimes an hour, the butterfly (Fig. 15) proudly sails aloft, the glory and pride of the insect world.

**Comment by florimondmanca** [comment]
Okay, I sent an email to Djamal Makhoufi, the author of the picture in the article header here https://www.fontainebleau-blog.com/insectes/pieride-du-navet-pieris-napi/. Will keep you posted! :+1:

**Comment by tomchristie** [comment]
I'm going to close this off at the moment, tho I'm not *totally* against a logo change if something fits well, and happy to consider worked through suggestions.

Google image search is pretty neat for being able to filter to public domain drawings, eg. filtering to public licensed black & white drawings...

https://www.google.com/search?q=butterfly&tbm=isch&hl=en&hl=en&chips=q%3Abutterfly%2Cg_1%3Adrawing%3AjPxzsfa14GA%3D&tbs=ic%3Agray%2Csur%3Af&ved=0CAEQpwVqFwoTCOjMqKf8_ecCFQAAAAAdAAAAABAC&biw=1587&bih=1100
