### ISSUE TITLE
httpx.AsyncClient(http2=True) does NOT enable http/2 ?

### ISSUE THREAD

**Issue by opstalj-nokia** [encode/httpx#844]
Hi,

According to the documentation, setting:

`httpx.AsyncClient(http2=True)`

should enable HTTP/2.
However, this is not the case: I did this:

>>> r = httpx.AsyncClient(http2=True)
>>> r = httpx.put('http://10.100.13.50:8080/nnrf-nfm/v1/nf-instances/'+my_uuid,json=data,headers=my_headers)

and this is the output:

        PUT /nnrf-nfm/v1/nf-instances/cb0aee98-c156-4515-9046-9f4513053f10 HTTP/1.1
        host: 10.100.13.50:8080
        ...

So it still uses HTTP/1.1 and not HTTP/2?

How can I get HTTP/2 for unencrypted HTTP?
Thanks in advance,

 opstalj

**Comment by tomchristie** [comment]
Setting `http2=True` does not enforce HTTP/2, but it does enable it, as we note here... https://www.python-httpx.org/http2/#inspecting-the-http-version

We're currently following browser-like behavior which is to *only* support HTTP/2 on HTTPS connections. We ought to expand the docs in that section to make that clear.

We *could* feasibly support HTTP/2 upgrades over insecure HTTP connections, but it's not clear if that's something that'd be desirable or not.

**Comment by opstalj-nokia** [comment]
Ok, thanks.

It would be cool if you could enable HTTP/2 even with insecure HTTP connections (eg: just for test purpose, it would be handy to check the HTTP/2 communication).
