### ISSUE TITLE
AsyncClient should use timeout when establishing tunnel proxy connection

### ISSUE THREAD

**Issue by daa** [encode/httpx#845]
Currently ``httpx._dispatch.proxy_http.HTTPProxy.request_tunnel_proxy_connection()`` method doesn't support timeout which results in unexpectedly long waiting time when connection to proxy cannot be established. For example this happens when packets to proxy are dropped.

My suggestion is that ``tunnel_connection()`` method should pass ``timeout`` to ``request_tunnel_proxy_connection`` and the latter function should use it when sending request to proxy server.

https://github.com/encode/httpx/blob/707e54c48415e98224ca74e67809a5593b41b03d/httpx/_dispatch/proxy_http.py#L138
https://github.com/encode/httpx/blob/707e54c48415e98224ca74e67809a5593b41b03d/httpx/_dispatch/proxy_http.py#L121

**Comment by florimondmanca** [comment]
Yes, arguably that’s a bug, especially considering we have strict timeouts by default everywhere else (and that this is one of the core promises of HTTPX).

**Comment by tomchristie** [comment]
Thanks for raising this!
We ought to double check the `httpcore` behavior here too.

**Comment by yeraydiazdiaz** [comment]
[Timeouts are used in httpcore](https://github.com/encode/httpcore/blob/master/httpcore/_async/http_proxy.py#L167).

Thanks for the report, closing.

**Comment by umruuu** [comment]
How can i change the defult timeout when the proxy is bad ? Do not wanna to wait for 60secs ,I need to change the httpx sourse code ?
