### ISSUE TITLE
Untagged releases

### ISSUE THREAD

**Issue by PromyLOPh** [encode/httpx#848]
Hi,

I’m currently packaging httpx for guix, but I need release [0.9.3](https://github.com/encode/httpx/commit/f55db15a01ce311b9d4229d9707aa58043a8eaed#diff-121ff8a507f45453fa699383654a3351), which is not tagged in git. This is true for [0.9.4](https://github.com/encode/httpx/commit/b847ab07a33e0d6a006b85130c07e71a2479d92b) as well. Please create tags for them, so checking out a specific version works.

Thanks :)

**Comment by florimondmanca** [comment]
Sure, just pushed tags https://github.com/encode/httpx/tree/0.9.3 and https://github.com/encode/httpx/tree/0.9.4. :-)
