### ISSUE TITLE
Wheel should not be tagged as universal

### ISSUE THREAD

**Issue by daa** [encode/httpx#850]
Currenlty ``httpx`` wheels are tagged as universal - ``py2.py3`` because of following configuration in ``setup.cfg``:
```
[bdist_wheel]
universal = 1
```
https://github.com/encode/httpx/blob/707e54c48415e98224ca74e67809a5593b41b03d/setup.cfg#L1

However this is incorrect because ``httpx`` uses modern Python syntax and features so its wheel must not be marked as universal.

**Comment by florimondmanca** [comment]
[Indeed](https://packaging.python.org/guides/distributing-packages-using-setuptools/#universal-wheels):

> Universal Wheels are wheels that are pure Python (i.e. contain no compiled extensions) and support Python 2 and 3.
>
> Only use the --universal setting, if:
> - Your project runs on Python 2 and 3 with no changes (i.e. it does not require 2to3).
> - Your project does not have any C extensions.

Would you like to put a PR together? :)
