### ISSUE TITLE
Accept url-encoded characters in proxy authentication strings

### ISSUE THREAD

**Issue by lethargy-navigator** [encode/httpx#858]
Certain characters such as @:!#$ break proxy authentication strings when included without url-encoding them.

I'm dealing with a service account that has # in the password and httpx is unable handle this. # breaks the URI and %23 is sent literal.

Expected behavior: In requests we can url-encode these characters in the proxy strings defined within proxies dict and they will be properly decoded before sending the request.

**Comment by tomchristie** [comment]
Related: #328
