### ISSUE TITLE
Including server response when throwing HTTPError

### ISSUE THREAD

**Issue by mosheduminer** [encode/httpx#875]
Hi, I'm delighted to have found httpx, great work!

I have a feature request: I have a server that normally provides some debugging information when returning a 4xx or 5xx status. But when I call `response.raise_for_status()`, this information is not shown in the error. I would like it to be possible to call this method, and include `response.text` in the error message.

**Comment by florimondmanca** [comment]
Hi,

(FYI, we have a chat at https://gitter.im/encode/community for quick questions like this :-))

Thanks for the kind words 😄 Actually, not really a feature request — this is already possible with a little bit of custom code.

Eg you can re-raise an exception with an updated message:

```python
try:
    response.raise_for_status()
except httpx.HTTPError as exc:
    message = f"{exc} (response content: {response.text})"
    raise httpx.HTTPError(message, response=response) from None
```

You could even make this reusable by turning this into a context manager:

```python
from contextlib import contextmanager
import httpx

@contextmanager
def include_response_text_in_errors():
    try:
        yield
    except httpx.HTTPError as exc:
        response = exc.response
        message = f"{exc} (response content: {response.text})"
        raise httpx.HTTPError(message, response=response) from None

with include_response_text_in_errors():
    ...
    response.raise_for_status()
```

Going to close for now, feel free to drop by the chat if you're running into issues!
