### ISSUE TITLE
(improvement) Accessing a private member publicly

### ISSUE THREAD

**Issue by kaypee90** [encode/httpx#893]
### Checklist

- [x] I searched the [HTTPX documentation](https://www.python-httpx.org) but couldn't find what I'm looking for.
- [x] I looked through similar issues on GitHub, but didn't find anything.
- [x] I looked up "How to do ... in HTTPX" on a search engine and didn't find any information.
- [ ] I asked the [community chat](https://gitter.im/encode/community) for help but didn't get an answer.

### Question
This is a code improvement question. The member `_request` in HttpError per the python convention is a private variable but its being accessed publicly in the code eg.
`if exc._request is None:
                exc._request = request`

**Comment by florimondmanca** [comment]
Hi!

True, but this reach into our own private API is done inside our own code, in a place that’s not meant for extension, so from my perspective it is _okay_. Going to close this for now, if this is causing you specific usage issues let’s discuss here or in the chat. :)
