### ISSUE TITLE
Hiding the request query params in DEBUG logs

### ISSUE THREAD

**Issue by foxmask** [encode/httpx#910]
### Checklist

- [x] There are no similar issues or pull requests for this yet.
- [ ] I discussed this idea on the [community chat](https://gitter.im/encode/community) and feedback is positive.

### Is your feature related to a problem? Please describe.

i'd like to be able to hide sensible data from the log 

## Describe the solution you would like.

when requesting an endpoint, all the params are displayed in the log
eg
I've hidden the param from my lib
```
2020-04-26 10:53:29,286 - DEBUG - method get path http://127.0.0.1:41184/folders/ params {'token': '***', 'fields': 'id, title, created_time, updated_time, user_created_time, user_updated_time, encryption_cipher_text, encryption_applied, parent_id'} payload {} headers {'Content-Type': 'application/json'}
method get path http://127.0.0.1:41184/folders/ params {'token': '***', 'fields': 'id, title, created_time, updated_time, user_created_time, user_updated_time, encryption_cipher_text, encryption_applied, parent_id'} payload {} headers {'Content-Type': 'application/json'}
```
but httpx show it after all
```
2020-04-26 10:53:29,299 - DEBUG - HTTP Request: GET http://127.0.0.1:41184/folders/?token=fff6170db0bbb65ff563fc5977d533a0b4a60ce3203b8c6252f500fbf9e37211a056dcc8f7cf6239e8745a90bd62da0ff328fcc6e8162552139e382301520ca8 "HTTP/1.1 200 OK"
HTTP Request: GET http://127.0.0.1:41184/folders/?token=fff6170db0bbb65ff563fc5977d533a0b4a60ce3203b8c6252f500fbf9e37211a056dcc8f7cf6239e8745a90bd62da0ff328fcc6e8162552139e382301520ca8 "HTTP/1.1 200 OK"
```
how could we hide that ?

**Comment by florimondmanca** [comment]
Hello!

Thanks for submitting this.

(If those tokens from your HTTPX logs are valid you might want to rotate them. :))

I believe you should be able to implement log filtering using the logging module, ie registering filters on the httpx logger. I can’t share code examples right now but I’d suggest searching for secret sanitization in logs on Google. If you can’t find what you’re looking for let us know. :)

**Comment by tomchristie** [comment]
You'd be better off with tokens in request headers, since they're *less* likely to be exposed by intermediaries of any kind.

I guess it'd be interesting to know what kind of logging behaviours other clients have for query parameters at DEBUG level? (Although on first pass I'd think that we've got the behaviour most folks would want here, and that you might want to just *not* log httpx at DEBUG level in rpdocution?)

**Comment by foxmask** [comment]
I can't put the token on the headers, I'm not the author of the service that responds here.
I'll suggest him to do so ;)

**Comment by tomchristie** [comment]
Updated the title here to be more specific.

I think any resolution here ought to be guided by "what do existing clients do here".

**Comment by tomchristie** [comment]
At the moment I'm going to close this off.

I'm happy to reopen this if someone's up for taking the time to dig into what other Python clients and servers do wrt. default DEBUG output including query strings, and figuring out if we're out of line with that.
