### ISSUE TITLE
Can I still use the async API out of the box somehow?

### ISSUE THREAD

**Issue by phdowling** [encode/httpx#937]
Hi all,

I started using httpx a few months back because I like the simplicity of making async requests with one line of code in the same style as I was used to making calls with `requests`. I recently updated, breaking essentially all of the projects that I used it in, since the
```
res = await httpx.get(url)
```
pattern is now gone.

I can of course easily fix the broken code by replacing those lines with 
```
async with  httpx.AsyncClient() as client:
    res = await client.get(url)
```
however, this kind of defeats the purpose of why I started using httpx to begin with (in fact this is not that much simpler than just using aiohttp). Since I'm mostly implementing servers that are completely async anyway, I have no actual use for the out-of-the-box sync default style. Also: what do the httpx sync methods improve over plain old `requests`? If the main use case is synchronous requests, isn't that still the best library to go with?

What was the rationale behind making this change? Am I missing something, is my experience actually supposed to be better now and I just don't realize it? Is there still an "async-first" API I can use?

Please don't take these questions the wrong way, I definitely appreciate the effort this community is putting in. Just see it as feedback about a fundamental API change that came as a total surprise to a relatively new user. I'm also not suggesting I know better what this library should look like, maybe I'm just using the wrong library for my use-case (i.e. have the simplest possible API for making async requests in a web server).

**Comment by tomchristie** [comment]
You don’t necessarily need to use the context block format. The simplest form of making async requests is...

```python
client = httpx.AsyncClient()
...  # You’re good to go, just use this global client instance throughout.
```

We *could* feasibly choose to reintroduce a top-level API for making async requests, but we’d need to avoid naming collisions, so for example... `res = await httpx.aget(...)`.

Personally I don’t *think* I see enough value vs the one-liner client instantiation.
