### ISSUE TITLE
Please include docs dir in PyPI tarball

### ISSUE THREAD

**Issue by sandrotosi** [encode/httpx#938]
Hello,
i'm packaging httpx for Debian; we like to provide our uses with offline documentation, so it would be extremely helpful if you could include the `docs` dir in the pypi tarball, so that we can build it and ship it with our binary packages.

thanks for considering,
Sandro

**Comment by florimondmanca** [comment]
Hi there,

Sure, that sounds sensible to me! I think it’s a matter of adding the docs/ directory to the MANIFEST - maybe with `graft`. Anyone up for a PR for this can validate locally by running `python setup.py build`.

**Comment by tomchristie** [comment]
*If* we're going to to do this, then I'd want to be doing so consistently across encode projects, so there's a fairly high bar to us accepting a change like this.

Personally I don't really understand the value or motivation in re-packaging tests & docs alongside the installable package, it just isn't clear to me why that'd be a valuable thing to do. However there'd be a case to make for it if there's clearly a strong community consensus around this, so what do the following packages do wrt. packaging tests & docs?...

* `requests`
* `pytest`
* `flask`
* `django`
