### ISSUE TITLE
Missing documentation for Exceptions

### ISSUE THREAD

**Issue by hynek** [encode/httpx#940]
So looked everywhere but I could't find _any_ information on httpx's errors at all (except of the existence of `raise_for_status()`. Is this on purpose because the design is not final? I had to read source code to get an idea which is not ideal.

**Comment by tomchristie** [comment]
Not intentional, nope.

Or, it might have been at one point, but right now anything that's visible through `__init__.py` is public API, and ought to be documented.

It'd make sense for us to prioritize this one.

**Comment by florimondmanca** [comment]
FWIW we have #884 pending to add some docs about exceptions. :)

**Comment by tomchristie** [comment]
Ah, thanks @florimondmanca

**Comment by hynek** [comment]
I have seen those but it looked like stalled attempt to refactor the exceptions, not like documentation for the status quo…

**Comment by tomchristie** [comment]
@hynek Yeah that's actually a fair comment. Opened #949 to make sure we address this comprehensively.
