### ISSUE TITLE
Fix flaky `test_write_timeout` test in CI

### ISSUE THREAD

**Issue by yeraydiazdiaz** [encode/httpx#943]
[One of our tests](https://github.com/encode/httpx/blob/master/tests/test_timeouts.py#L15-L22) has decided to start failing across different Python versions:

https://github.com/encode/httpx/pull/941/checks?check_run_id=666427391
https://github.com/encode/httpx/runs/666405754
https://github.com/encode/httpx/runs/666709254

I could not reproduce the error locally on 3.8 or 3.6 on my Mac.

**Comment by florimondmanca** [comment]
No idea yet, but maybe a change in one of our dependencies...?

- pytest-asyncio 0.12, released on May 4th?
- Regression in httpcore?

**Comment by tomchristie** [comment]
#946 might be a bit more reliable here?

Really we ought to also look at...

* Pinning the dependencies installed for the test suite.
* Using dependabot to update those as separate PRs.

And then...

* Cache the virtualenv directory between builds.

That'd help us with debugging stuff like this, even in cases where it's not obvious that it *is* related to any library changes, and could well just be an environmental issue, at least we'd have a better view onto that.

**Comment by tomchristie** [comment]
Closed via #946
