### ISSUE TITLE
[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108),when i using proxies,it show this error.

### ISSUE THREAD

**Issue by zszjszlk2** [encode/httpx#951]
![error](https://user-images.githubusercontent.com/46711557/82034665-1271ca80-96d1-11ea-8d39-29983e9c77e1.png)
My proxy has no problem,i test it in requests module,but when i using httpx with proxies,it show this,
please how to resolve it?

**Comment by tomchristie** [comment]
Presumably we use a more secure set ofSSL options than `requests` currently default to.

We ought to do some work on documenting failures here, and showing users how to tweak the finer-grained details of the SSL config if needed.

**Comment by yeraydiazdiaz** [comment]
Hi, I've seen this error when trying to connect to a host using `https` on a port that does not support it.

In your case I think the problem is that in your `proxies` dict you have a proxy URL like `https://<PROXY_IP>:80`, meaning it will try to use HTTPS on port 80, which most likely will not support TLS since it's usually port number 443.

I think you could solve it by removing the `https` from that proxy URL.

**Comment by zszjszlk2** [comment]
> proxy

![work](https://user-images.githubusercontent.com/46711557/82045358-8ddb7800-96e1-11ea-933d-d187da768dc8.png)
![pro](https://user-images.githubusercontent.com/46711557/82045391-9c299400-96e1-11ea-89ce-276aeb2c0473.png)
rovmove https like the picture?But the proxies won't work!!
The website which i crawled has wrong SSL certificate,So i add verify=False ,but it still show the error,i don't know how to resolve it?
https://jxfw.gdut.edu.cn/, a chinese web

**Comment by yeraydiazdiaz** [comment]
What I meant was for you to set `proxies` as:

```
proxies = {
}

**Comment by zszjszlk2** [comment]
> 我的意思是让你`proxies`作为：
> 
> ```
> proxies = {
>    'http': 'http://.....',
>    'https': 'http://.....',  # The same URL as above
> }
> ```

![new err](https://user-images.githubusercontent.com/46711557/82046905-689c3900-96e4-11ea-9727-82ffc8ff76a9.png)
Thank you for your help so much, but it showed another ProxyError error…

**Comment by yeraydiazdiaz** [comment]
That means the proxy is rejecting your request for some reason.

I'm sorry but since that's not an error in HTTPX anymore so I can't help you any further. Good luck!

**Comment by zszjszlk2** [comment]
> That means the proxy is rejecting your request for some reason.
> 
> I'm sorry but since that's not an error in HTTPX anymore so I can't help you any further. Good luck!
That is my proxy's problem,i changed https to http and change my proxy,it turned to OK, thank‘s for Contributor‘s help,httpx is excellent!!

**Comment by zszjszlk2** [comment]
> That means the proxy is rejecting your request for some reason.
> 
> I'm sorry but since that's not an error in HTTPX anymore so I can't help you any further. Good luck!

That is my proxy's problem,i changed https to http and change my proxy,it turned to OK, thank‘s for Contributor‘s help,httpx is excellent!!
