### ISSUE TITLE
Empty default headers?

### ISSUE THREAD

**Issue by GnubiBORED** [encode/httpx#956]
HTTPX is adding headers to my request such as accept: */* i can somehow tell httpx that i dont want to add those headers? to not pass them?

**Comment by yeraydiazdiaz** [comment]
Hey @GnubiBORED, HTTPX does indeed add headers to requests following requests/urllib3.

AFAIK there is not specific flag to prevent it from adding these default headers, but it will certainly respect the ones already present so you could control the actual values.

Alternatively, you could build the `Request` object yourself and call `Client.send` as described in the [docs](https://www.python-httpx.org/api/#request).

**Comment by florimondmanca** [comment]
Agreed with Yeray, building a `Request` instance and cleaning up any `.headers` looks like the way to go - auto headers are added inside the `Request` constructor.

```python
import httpx

request = httpx.Request(...)
request.headers.clear()
```

**Comment by florimondmanca** [comment]
Closing as I think the initial question has been answered. :-)

**Comment by GnubiBORED** [comment]
isnt possible to 

> 
> 
> Agreed with Yeray, building a `Request` instance and cleaning up any `.headers` looks like the way to go - auto headers are added inside the `Request` constructor.
> 
> ```python
> import httpx
> 
> request = httpx.Request(...)
> request.headers.clear()
> ```

Interesing, but im ussing httpx.AsyncClient something like this in the client declaration would work too?

`   client = httpx.AsyncClient(verify=False,http2=True).headers.clear()`

**Comment by GnubiBORED** [comment]
even if i call client.headers.clear() before making the async client get or post, it still sends accept */* header

import json
import ssl
import collections
import traceback
import httpx._config



```
class http_Client():
    def __init__(self):
        self.proxy = None
        self.headers = None
        self.body = None
        self.params = None
        self.url = None
        self.method = None
        self.cookies = None
        self.response = None

    def reset(self):
        self.headers = None
        self.body = None
        self.params = None
        self.url = None
        self.method = None
        self.cookies = None
        self.response = None


    async def run(self):
        if self.headers == None:
            raise Exception('Headers cant be empty')
        if self.method == 'POST' and self.body == None:
            raise Exception('HTTP body cant be empty')
        if self.url == None:
            raise Exception('URL Cant be empty')

        # todo aun falta configurar las cookies en las llamadas que faltan ya que no tengo claro que llamadas meten cookies y cuales no, la mayoria de gets llevan cookies

        ssl_config = httpx._config.SSLConfig()

        ssl_context = ssl_config.load_ssl_context()

        ssl_context.options |= getattr(ssl, "OP_NO_TLSv1_3", 0)

        ssl_context.load_verify_locations(r'C:\Users\localhost\Documents\Enrique\Programacion\Charles_Proxy_SSL.pem')

        #ssl_config = client_httpx.SSLConfig(verify=r'C:\Users\localhost\Documents\Enrique\charlesproxy.pem')

        try:
            self.headers = collections.OrderedDict(self.headers)
            if self.proxy != None:
                client = httpx.AsyncClient(proxies={
                    "http": 'http://' + self.proxy,
                    "https": 'http://' + self.proxy

                    # configuramos ssl en el cliente

                }, verify=ssl_context, http2=True)


            else:
             client = httpx.AsyncClient(verify=False,http2=True)


            if self.method == 'get':
                client.headers.clear()
                self.response = await client.get(self.url, headers=collections.OrderedDict(self.headers), params=self.params)


                if self.response.history and 'login.php?mobile&sid' in self.url:

                    for resp in self.response.history:
                        zero_test = resp.headers['set-cookie']
                        sid_split = zero_test.split('=')
                        sid = sid_split[1].split(';')[0]
                        cid = sid_split[3].split(';')[0]

                        return {'sid': sid, 'cid': cid, 'html_response': self.response.text}
                else:

                    json_data = self.response.json()

                    return json_data


            elif self.method == 'post':

                # pasamos a texto  cualquier cosa dentro de el body
                body = str(self.body)
                # mandamos a el cliente ha hacer el post
                client.headers.clear()
                self.response = await client.post(self.url, headers=collections.OrderedDict(self.headers), params=self.params, data=body)
                json_data = self.response.json()
                return json_data

        except Exception as e:
            print(e.args)
            print(traceback.print_exc())
        finally:
           self.reset()

```

**Comment by florimondmanca** [comment]
@GnubiBORED No, clearing the `client` headers is not enough - as I wrote in my previous answer, the automatic headers are added at the request level, they don't come from the client. Building and sending `Request` instances is the way to go.

**Comment by GnubiBORED** [comment]
then is not possible to use async client witouth adding this headers? i prefer using it cause for handle cookies is much easier, if i have to use plain request im gonna struggle a lot also i do a lot of request during execution of program, if i dont use async gonna need to open threads or code it myself.

Wouldnt be easier to make the posibility to do not add those headers at request level?


Also i dont see proxy support o http2 support for httpx.request. there isnt? Or edit the request before sending it to stop sending those headers in any way? I really need it but i get my request failed due to those extra headers sended, hope i can use async client and remove those headers 

@florimondmanca

**Comment by florimondmanca** [comment]
I'm not talking about `httpx.request`, but either building a `Request` instance explicitly or, if you're using a client, `client.build_request()`.

My code example didn't show the usage with a client, but here's another example:

```python
client = httpx.AsyncClient(headers={"my": "header"}, http2=True, proxies=...)

request = client.build_request("GET", "https://example.org")
request.headers.clear()  # Tada
response = await client.send(request)
```

**Comment by GnubiBORED** [comment]
@florimondmanca 
But that removes all headers, i need to send some headers to my request be succesfull i just need to remove the accept one

`         client = httpx.AsyncClient(proxies={
                    "http": 'http://' + self.proxy,
                    "https": 'http://' + self.proxy

                    # configuramos ssl en el cliente

                }, verify=ssl_context, http2=True)  

 request = client.build_request('post',self.url, headers=collections.OrderedDict(self.headers), params=self.params, data=body)
            request.headers.clear()
            self.response = await client.send(request)`



I did this and it just send the default http2 headers, i need to send some headers(the ones that are stored in self.headers) and remove the "accept" one

**Comment by florimondmanca** [comment]
You can manipulate `request.headers` however you'd like. If you just need to pop the `Accept` header then do `request.headers.pop("accept")` instead of clearing the entire dictionary.
