### ISSUE TITLE
How to set proxy connect timeout ? Got this  httpx._exceptions.NetworkError: [Errno 60] Connect call failed

### ISSUE THREAD

**Issue by umruuu** [encode/httpx#958]
I found out timeout is not working for the proxy connect , if there is not an option to set up, how can i change the defult source code in order to change the proxy connect timeout?

**Comment by florimondmanca** [comment]
Are you testing against the latest 0.13.dev2 development release?

As Yeray mentioned in #845 a proxy timeout fix was issued to HTTPCore and released in that version. Looking at master I don’t see that we’re ignoring timeouts when connecting to proxies anymore.

Going to close this for now, feel free to drop by the community chat for questions like these. :)
