### ISSUE TITLE
Direct support questions to StackOverflow?

### ISSUE THREAD

**Issue by yeraydiazdiaz** [encode/httpx#959]
I've noticed a surge in basic usage questions both in the issues and in the chat which is awesome.

However, I don't think the chat is the appropriate place for these since they won't show up in search engines, the answers (if any) may be later in the timeline, and most of the time users will just write the new question there. I think  issues are not the right place for these either since it increases the burden on maintainers.

I suggest we take a page from [Hynek's talk](https://hynek.me/talks/python-foss/) and create a tag in StackOverflow and direct usage questions there.

**Comment by florimondmanca** [comment]
Fantastic idea! In terms of workflow it wouldn’t change much, we’d be answering (and directing) questions there instead of here or on the chat. +1 :)

**Comment by florimondmanca** [comment]
Also in terms of “how would this fit within Encode” (which it seems we need to take into account every time we plan changes Ike these?), from what I’ve seen it seems that most other projects in the async stack could benefit from this too...

In this aspect HTTPX could serve as a pioneer, to see how that goes and then maybe roll out more tags for other Encode projects?

In any case I think this is definitely something to consider; the more questions people can solve by themselves by looking up SO the better for the community and the maintenance team IMO.

**Comment by yeraydiazdiaz** [comment]
There are tags for both Uvicorn and Starlette (via https://stackoverflow.com/tags).

Not for httpx though, alas:

<img width="211" alt="Screenshot 2020-05-17 at 09 17 14" src="https://user-images.githubusercontent.com/6739793/82139415-84f0c080-981f-11ea-86bf-ebaa8dfe1fa2.png">

**Comment by tomchristie** [comment]
Don't really mind. I'm probably also okay with us holding out until GitHub roll out the discussions tab... https://github.com/zeit/next.js/discussions

They've had it in closed beta on a small handful of repos since feb. so I'm assuming it's not going to be *ages* until it lands.

**Comment by yeraydiazdiaz** [comment]
In my mind discussions are more about "pre-issues" rather than usability questions.

We also have the [forum](https://discuss.encode.io/) which some users post questions to as well.

I don't mind too much either, I just think the chat is not a great experience and it's our go-to solution right now.

**Comment by florimondmanca** [comment]
Looking that the discussion dashboard from Zeit I see there are various discussion categories - help, TIL, ideas, announcements (general), thanks, etc., which is _super_ cool.

The general "question/answer" flow roughly matches that of SO, and everything's public and indexable, so I think it's a great alternative for us while not having to watch over two places (GitHub + SO).

(There's also a more political case about "it's yet another step towards more GitHub centralization and lock-in", but here we are…)

**Comment by florimondmanca** [comment]
Are we okay to close this for now?

**Comment by yeraydiazdiaz** [comment]
Yep, closing.
