### ISSUE TITLE
has_content attribute for response object?

### ISSUE THREAD

**Issue by Znunu** [encode/httpx#960]
I couldn't find anything like this in the docs
Would it maybe make sense to add something like this? That's true, when the size of the content is zero
Please forgive my ignorance, I'm not very experienced

**Comment by florimondmanca** [comment]
Hi!

Can you please follow the issue template? It’s always helpful to have context about the “why”, as in “what are you trying to achieve”.

Right now I would say if your use case is branching on whether the response body is empty, you can already do it by using `.content`, as the empty string is considered falsy:

```python
response = httpx.get(...)
if response.content:
    ...
```

Going to close this assuming this answers your question, if not please drop by [the chat](https://gitter.im/encode/community) - we try to keep GitHub issues for demonstrated bugs or agreed upon feature requests. Thanks!
