### ISSUE TITLE
Version 0.13

### ISSUE THREAD

**Issue by yeraydiazdiaz** [encode/httpx#962]
Hi all,

We've been focused lately on what should make it to 1.0 and kind of forgot about 0.13.

Is there anything outstanding for it?

**Comment by tomchristie** [comment]
Alrighty, yup let's go, so...

I'd originally planned that we just promote our currently beta release to 0.13.
Actually I think there's a couple of elements worth getting in here, to smooth the path onto our 1.0 release...

* Transport API. #768 - Let's add `transport=...`, put the `dispatch` naming on the deprecation path. Make the Transport API public.
* Scheme handling. #954 - Let's switch the HTTP Core signature to taking the port as an *optional* integer. We can leave the later part of switching `httpx` to have `URL.port` as an optional integer to a later point, the important point is getting that bit of the *interface* tied down.
* Consider if we want to push #948 into 0.13, with `hard_limit`/`soft_limit` on the deprecation path.
* Consider if we want to push #927 into 0.13, or add `AsyncTunnelProxy`, `AsyncForwardProxy`,  `SyncTunnelProxy`, `SyncForwardProxy` to httpcore interface as an interim step. (This is perhaps? a more borderline case than the others, not sure.)

**Comment by yeraydiazdiaz** [comment]
Sounds good.

I'm up for including the two last points, though we do have a few fixes in 0.13.0.dev2 that haven't landed in the main release path. Not sure if we're in a hurry to push those out.

**Comment by yeraydiazdiaz** [comment]
I've created https://github.com/encode/httpx/milestone/5 to better track this release. Thanks!
