### ISSUE TITLE
Make `urllib3` optional.

### ISSUE THREAD

**Issue by tomchristie** [encode/httpx#965]
Follow up to #963.

Let's ensure that the `urllib3` dependency is optional.

* Make sure we don't have it anymore in `setup.py`.
* Make sure it's listed as optional in the `REAEDME`/`homepage`.
* Make sure that the `urllib3.py` module passes gracefully on `ImportError`, and checks the package exists in `URLLib3Transport.__init__()`.

**Comment by yeraydiazdiaz** [comment]
The last point is [already covered](https://github.com/encode/httpx/blob/master/httpx/_transports/urllib3.py#L13-L32), unless you have a different implementation in mind?

**Comment by tomchristie** [comment]
Ah fantastic!

**Comment by tomchristie** [comment]
Have also confirmed that it's not in `setup.py`, so all we have is...

* Docs tweak in the advanced section, noting to make sure `urllib3` is installed.
* In `README.md` and `doc/index.md` update the dependencies listing. (I guess move `urllib3` to just above `brotlipy` as the other optional, and have `httpcore` with `h11`, `h2` hanging off as subdependancies, like so...

* `httpcore` - The default transport implementation for `httpx`.
  * `h11` - HTTP/1.1 support.
  * `h2` - HTTP/2 support.
* `certifi` - SSL certificates.
* `chardet` - Fallback auto-detection for response encoding.
* `hstspreload` - determines whether IDNA-encoded host should be only accessed via HTTPS.
* `idna` - Internationalized domain name support.
* `rfc3986` - URL parsing & normalization.
* `urllib3` - Support for `httpx.URLLib3Transport()`. *(Optional)*
* `brotlipy` - Decoding for "brotli" compressed responses. *(Optional)*
